// Code generated by Fern. DO NOT EDIT.

package client

import (
	cards "github.com/lealhq/leal-go-sdk/cards"
	core "github.com/lealhq/leal-go-sdk/core"
	customercards "github.com/lealhq/leal-go-sdk/customercards"
	customers "github.com/lealhq/leal-go-sdk/customers"
	internal "github.com/lealhq/leal-go-sdk/internal"
	locations "github.com/lealhq/leal-go-sdk/locations"
	option "github.com/lealhq/leal-go-sdk/option"
	posters "github.com/lealhq/leal-go-sdk/posters"
	rewards "github.com/lealhq/leal-go-sdk/rewards"
	status "github.com/lealhq/leal-go-sdk/status"
	stores "github.com/lealhq/leal-go-sdk/stores"
)

type Client struct {
	Stores        *stores.Client
	Cards         *cards.Client
	Customers     *customers.Client
	CustomerCards *customercards.Client
	Locations     *locations.Client
	Posters       *posters.Client
	Rewards       *rewards.Client
	Status        *status.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Stores:        stores.NewClient(options),
		Cards:         cards.NewClient(options),
		Customers:     customers.NewClient(options),
		CustomerCards: customercards.NewClient(options),
		Locations:     locations.NewClient(options),
		Posters:       posters.NewClient(options),
		Rewards:       rewards.NewClient(options),
		Status:        status.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
