// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

var (
	createCardsRequestFieldAccountID = big.NewInt(1 << 0)
	createCardsRequestFieldCard      = big.NewInt(1 << 1)
)

type CreateCardsRequest struct {
	// Parent store ID
	AccountID int                     `json:"-" url:"-"`
	Card      *CreateCardsRequestCard `json:"card" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateCardsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequest) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createCardsRequestFieldAccountID)
}

// SetCard sets the Card field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequest) SetCard(card *CreateCardsRequestCard) {
	c.Card = card
	c.require(createCardsRequestFieldCard)
}

func (c *CreateCardsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCardsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateCardsRequest(body)
	return nil
}

func (c *CreateCardsRequest) MarshalJSON() ([]byte, error) {
	type embed CreateCardsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getCardsRequestFieldAccountID = big.NewInt(1 << 0)
	getCardsRequestFieldID        = big.NewInt(1 << 1)
)

type GetCardsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`
	// Card ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCardsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsRequest) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getCardsRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsRequest) SetID(id int) {
	g.ID = id
	g.require(getCardsRequestFieldID)
}

var (
	listCardsRequestFieldAccountID = big.NewInt(1 << 0)
	listCardsRequestFieldScope     = big.NewInt(1 << 1)
)

type ListCardsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`
	// Filter cards by archive status. Default: active only.
	Scope *string `json:"-" url:"scope,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListCardsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsRequest) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listCardsRequestFieldAccountID)
}

// SetScope sets the Scope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsRequest) SetScope(scope *string) {
	l.Scope = scope
	l.require(listCardsRequestFieldScope)
}

var (
	createCardsRequestCardFieldAuxiliaryFields         = big.NewInt(1 << 0)
	createCardsRequestCardFieldCardColor               = big.NewInt(1 << 1)
	createCardsRequestCardFieldExpiresAt               = big.NewInt(1 << 2)
	createCardsRequestCardFieldHeaderText              = big.NewInt(1 << 3)
	createCardsRequestCardFieldInitialStamps           = big.NewInt(1 << 4)
	createCardsRequestCardFieldName                    = big.NewInt(1 << 5)
	createCardsRequestCardFieldShowMemberField         = big.NewInt(1 << 6)
	createCardsRequestCardFieldShowStampsToRewardField = big.NewInt(1 << 7)
	createCardsRequestCardFieldStampBackgroundColor    = big.NewInt(1 << 8)
	createCardsRequestCardFieldStampColor              = big.NewInt(1 << 9)
	createCardsRequestCardFieldStampIcon               = big.NewInt(1 << 10)
	createCardsRequestCardFieldStampsRequired          = big.NewInt(1 << 11)
	createCardsRequestCardFieldStripColor              = big.NewInt(1 << 12)
	createCardsRequestCardFieldStripPreset             = big.NewInt(1 << 13)
	createCardsRequestCardFieldStripType               = big.NewInt(1 << 14)
	createCardsRequestCardFieldTextColor               = big.NewInt(1 << 15)
)

type CreateCardsRequestCard struct {
	// Up to two extra front-of-pass fields. Blank values are ignored.
	AuxiliaryFields []string `json:"auxiliary_fields,omitempty" url:"auxiliary_fields,omitempty"`
	// Hex colour for the card background (e.g. '#6B4226')
	CardColor *string `json:"card_color,omitempty" url:"card_color,omitempty"`
	// Card expiry timestamp (ISO 8601)
	ExpiresAt *string `json:"expires_at,omitempty" url:"expires_at,omitempty"`
	// Optional header text displayed on the card
	HeaderText *string `json:"header_text,omitempty" url:"header_text,omitempty"`
	// Number of stamps pre-filled on new customer cards (must be >= 0 and < stamps_required)
	InitialStamps *int `json:"initial_stamps,omitempty" url:"initial_stamps,omitempty"`
	// Card name (e.g. 'Coffee Loyalty Card')
	Name string `json:"name" url:"name"`
	// Whether wallet passes show the member name field
	ShowMemberField *bool `json:"show_member_field,omitempty" url:"show_member_field,omitempty"`
	// Whether wallet passes show the stamps-to-reward field
	ShowStampsToRewardField *bool `json:"show_stamps_to_reward_field,omitempty" url:"show_stamps_to_reward_field,omitempty"`
	// Hex colour for stamp backgrounds
	StampBackgroundColor *string `json:"stamp_background_color,omitempty" url:"stamp_background_color,omitempty"`
	// Hex colour for stamp icons
	StampColor *string `json:"stamp_color,omitempty" url:"stamp_color,omitempty"`
	// Stamp icon identifier
	StampIcon *string `json:"stamp_icon,omitempty" url:"stamp_icon,omitempty"`
	// Number of stamps needed to complete the card (1–21)
	StampsRequired *int `json:"stamps_required,omitempty" url:"stamps_required,omitempty"`
	// Hex colour for the strip (used when strip_type is 'color')
	StripColor *string `json:"strip_color,omitempty" url:"strip_color,omitempty"`
	// Preset strip image identifier (used when strip_type is 'preset')
	StripPreset *string `json:"strip_preset,omitempty" url:"strip_preset,omitempty"`
	// Strip image type
	StripType *string `json:"strip_type,omitempty" url:"strip_type,omitempty"`
	// Hex colour for card text
	TextColor *string `json:"text_color,omitempty" url:"text_color,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateCardsRequestCard) GetAuxiliaryFields() []string {
	if c == nil {
		return nil
	}
	return c.AuxiliaryFields
}

func (c *CreateCardsRequestCard) GetCardColor() *string {
	if c == nil {
		return nil
	}
	return c.CardColor
}

func (c *CreateCardsRequestCard) GetExpiresAt() *string {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreateCardsRequestCard) GetHeaderText() *string {
	if c == nil {
		return nil
	}
	return c.HeaderText
}

func (c *CreateCardsRequestCard) GetInitialStamps() *int {
	if c == nil {
		return nil
	}
	return c.InitialStamps
}

func (c *CreateCardsRequestCard) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateCardsRequestCard) GetShowMemberField() *bool {
	if c == nil {
		return nil
	}
	return c.ShowMemberField
}

func (c *CreateCardsRequestCard) GetShowStampsToRewardField() *bool {
	if c == nil {
		return nil
	}
	return c.ShowStampsToRewardField
}

func (c *CreateCardsRequestCard) GetStampBackgroundColor() *string {
	if c == nil {
		return nil
	}
	return c.StampBackgroundColor
}

func (c *CreateCardsRequestCard) GetStampColor() *string {
	if c == nil {
		return nil
	}
	return c.StampColor
}

func (c *CreateCardsRequestCard) GetStampIcon() *string {
	if c == nil {
		return nil
	}
	return c.StampIcon
}

func (c *CreateCardsRequestCard) GetStampsRequired() *int {
	if c == nil {
		return nil
	}
	return c.StampsRequired
}

func (c *CreateCardsRequestCard) GetStripColor() *string {
	if c == nil {
		return nil
	}
	return c.StripColor
}

func (c *CreateCardsRequestCard) GetStripPreset() *string {
	if c == nil {
		return nil
	}
	return c.StripPreset
}

func (c *CreateCardsRequestCard) GetStripType() *string {
	if c == nil {
		return nil
	}
	return c.StripType
}

func (c *CreateCardsRequestCard) GetTextColor() *string {
	if c == nil {
		return nil
	}
	return c.TextColor
}

func (c *CreateCardsRequestCard) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateCardsRequestCard) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAuxiliaryFields sets the AuxiliaryFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetAuxiliaryFields(auxiliaryFields []string) {
	c.AuxiliaryFields = auxiliaryFields
	c.require(createCardsRequestCardFieldAuxiliaryFields)
}

// SetCardColor sets the CardColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetCardColor(cardColor *string) {
	c.CardColor = cardColor
	c.require(createCardsRequestCardFieldCardColor)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetExpiresAt(expiresAt *string) {
	c.ExpiresAt = expiresAt
	c.require(createCardsRequestCardFieldExpiresAt)
}

// SetHeaderText sets the HeaderText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetHeaderText(headerText *string) {
	c.HeaderText = headerText
	c.require(createCardsRequestCardFieldHeaderText)
}

// SetInitialStamps sets the InitialStamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetInitialStamps(initialStamps *int) {
	c.InitialStamps = initialStamps
	c.require(createCardsRequestCardFieldInitialStamps)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetName(name string) {
	c.Name = name
	c.require(createCardsRequestCardFieldName)
}

// SetShowMemberField sets the ShowMemberField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetShowMemberField(showMemberField *bool) {
	c.ShowMemberField = showMemberField
	c.require(createCardsRequestCardFieldShowMemberField)
}

// SetShowStampsToRewardField sets the ShowStampsToRewardField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetShowStampsToRewardField(showStampsToRewardField *bool) {
	c.ShowStampsToRewardField = showStampsToRewardField
	c.require(createCardsRequestCardFieldShowStampsToRewardField)
}

// SetStampBackgroundColor sets the StampBackgroundColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStampBackgroundColor(stampBackgroundColor *string) {
	c.StampBackgroundColor = stampBackgroundColor
	c.require(createCardsRequestCardFieldStampBackgroundColor)
}

// SetStampColor sets the StampColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStampColor(stampColor *string) {
	c.StampColor = stampColor
	c.require(createCardsRequestCardFieldStampColor)
}

// SetStampIcon sets the StampIcon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStampIcon(stampIcon *string) {
	c.StampIcon = stampIcon
	c.require(createCardsRequestCardFieldStampIcon)
}

// SetStampsRequired sets the StampsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStampsRequired(stampsRequired *int) {
	c.StampsRequired = stampsRequired
	c.require(createCardsRequestCardFieldStampsRequired)
}

// SetStripColor sets the StripColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStripColor(stripColor *string) {
	c.StripColor = stripColor
	c.require(createCardsRequestCardFieldStripColor)
}

// SetStripPreset sets the StripPreset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStripPreset(stripPreset *string) {
	c.StripPreset = stripPreset
	c.require(createCardsRequestCardFieldStripPreset)
}

// SetStripType sets the StripType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetStripType(stripType *string) {
	c.StripType = stripType
	c.require(createCardsRequestCardFieldStripType)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsRequestCard) SetTextColor(textColor *string) {
	c.TextColor = textColor
	c.require(createCardsRequestCardFieldTextColor)
}

func (c *CreateCardsRequestCard) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCardsRequestCard
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateCardsRequestCard(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateCardsRequestCard) MarshalJSON() ([]byte, error) {
	type embed CreateCardsRequestCard
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateCardsRequestCard) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createCardsResponseFieldArchivedAt              = big.NewInt(1 << 0)
	createCardsResponseFieldAuxiliaryFields         = big.NewInt(1 << 1)
	createCardsResponseFieldCardColor               = big.NewInt(1 << 2)
	createCardsResponseFieldCreatedAt               = big.NewInt(1 << 3)
	createCardsResponseFieldCustomerCardsCount      = big.NewInt(1 << 4)
	createCardsResponseFieldExpiresAt               = big.NewInt(1 << 5)
	createCardsResponseFieldHeaderText              = big.NewInt(1 << 6)
	createCardsResponseFieldID                      = big.NewInt(1 << 7)
	createCardsResponseFieldInitialStamps           = big.NewInt(1 << 8)
	createCardsResponseFieldName                    = big.NewInt(1 << 9)
	createCardsResponseFieldRewardsCount            = big.NewInt(1 << 10)
	createCardsResponseFieldShowMemberField         = big.NewInt(1 << 11)
	createCardsResponseFieldShowStampsToRewardField = big.NewInt(1 << 12)
	createCardsResponseFieldStampBackgroundColor    = big.NewInt(1 << 13)
	createCardsResponseFieldStampColor              = big.NewInt(1 << 14)
	createCardsResponseFieldStampIcon               = big.NewInt(1 << 15)
	createCardsResponseFieldStampsRequired          = big.NewInt(1 << 16)
	createCardsResponseFieldStripColor              = big.NewInt(1 << 17)
	createCardsResponseFieldStripPreset             = big.NewInt(1 << 18)
	createCardsResponseFieldStripType               = big.NewInt(1 << 19)
	createCardsResponseFieldTextColor               = big.NewInt(1 << 20)
	createCardsResponseFieldUpdatedAt               = big.NewInt(1 << 21)
)

type CreateCardsResponse struct {
	// ISO 8601 timestamp when the card was archived, or null if active
	ArchivedAt string `json:"archived_at" url:"archived_at"`
	// Up to two extra front-of-pass fields
	AuxiliaryFields []string `json:"auxiliary_fields" url:"auxiliary_fields"`
	// Hex colour for the card background (e.g. '#6B4226')
	CardColor string `json:"card_color" url:"card_color"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Number of customer card instances issued
	CustomerCardsCount int `json:"customer_cards_count" url:"customer_cards_count"`
	// ISO 8601 timestamp when the card expires, or null if it does not expire
	ExpiresAt string `json:"expires_at" url:"expires_at"`
	// Optional header text displayed on the card
	HeaderText string `json:"header_text" url:"header_text"`
	// Unique card ID
	ID int `json:"id" url:"id"`
	// Number of stamps pre-filled on new customer cards (0 to stamps_required - 1)
	InitialStamps int `json:"initial_stamps" url:"initial_stamps"`
	// Card name (e.g. 'Coffee Loyalty Card')
	Name string `json:"name" url:"name"`
	// Number of rewards defined for this card
	RewardsCount int `json:"rewards_count" url:"rewards_count"`
	// Whether wallet passes show the member name field
	ShowMemberField bool `json:"show_member_field" url:"show_member_field"`
	// Whether wallet passes show the stamps-to-reward field
	ShowStampsToRewardField bool `json:"show_stamps_to_reward_field" url:"show_stamps_to_reward_field"`
	// Hex colour for stamp backgrounds
	StampBackgroundColor string `json:"stamp_background_color" url:"stamp_background_color"`
	// Hex colour for stamp icons
	StampColor string `json:"stamp_color" url:"stamp_color"`
	// Icon used for stamps (e.g. 'coffee', 'heart', 'star')
	StampIcon string `json:"stamp_icon" url:"stamp_icon"`
	// Number of stamps needed to complete the card (1–21)
	StampsRequired int `json:"stamps_required" url:"stamps_required"`
	// Hex colour for the strip (when strip_type is 'color')
	StripColor string `json:"strip_color" url:"strip_color"`
	// Preset strip image identifier (when strip_type is 'preset')
	StripPreset string `json:"strip_preset" url:"strip_preset"`
	// Strip image type: 'color', 'image', or 'preset'
	StripType string `json:"strip_type" url:"strip_type"`
	// Hex colour for card text
	TextColor string `json:"text_color" url:"text_color"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateCardsResponse) GetArchivedAt() string {
	if c == nil {
		return ""
	}
	return c.ArchivedAt
}

func (c *CreateCardsResponse) GetAuxiliaryFields() []string {
	if c == nil {
		return nil
	}
	return c.AuxiliaryFields
}

func (c *CreateCardsResponse) GetCardColor() string {
	if c == nil {
		return ""
	}
	return c.CardColor
}

func (c *CreateCardsResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateCardsResponse) GetCustomerCardsCount() int {
	if c == nil {
		return 0
	}
	return c.CustomerCardsCount
}

func (c *CreateCardsResponse) GetExpiresAt() string {
	if c == nil {
		return ""
	}
	return c.ExpiresAt
}

func (c *CreateCardsResponse) GetHeaderText() string {
	if c == nil {
		return ""
	}
	return c.HeaderText
}

func (c *CreateCardsResponse) GetID() int {
	if c == nil {
		return 0
	}
	return c.ID
}

func (c *CreateCardsResponse) GetInitialStamps() int {
	if c == nil {
		return 0
	}
	return c.InitialStamps
}

func (c *CreateCardsResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateCardsResponse) GetRewardsCount() int {
	if c == nil {
		return 0
	}
	return c.RewardsCount
}

func (c *CreateCardsResponse) GetShowMemberField() bool {
	if c == nil {
		return false
	}
	return c.ShowMemberField
}

func (c *CreateCardsResponse) GetShowStampsToRewardField() bool {
	if c == nil {
		return false
	}
	return c.ShowStampsToRewardField
}

func (c *CreateCardsResponse) GetStampBackgroundColor() string {
	if c == nil {
		return ""
	}
	return c.StampBackgroundColor
}

func (c *CreateCardsResponse) GetStampColor() string {
	if c == nil {
		return ""
	}
	return c.StampColor
}

func (c *CreateCardsResponse) GetStampIcon() string {
	if c == nil {
		return ""
	}
	return c.StampIcon
}

func (c *CreateCardsResponse) GetStampsRequired() int {
	if c == nil {
		return 0
	}
	return c.StampsRequired
}

func (c *CreateCardsResponse) GetStripColor() string {
	if c == nil {
		return ""
	}
	return c.StripColor
}

func (c *CreateCardsResponse) GetStripPreset() string {
	if c == nil {
		return ""
	}
	return c.StripPreset
}

func (c *CreateCardsResponse) GetStripType() string {
	if c == nil {
		return ""
	}
	return c.StripType
}

func (c *CreateCardsResponse) GetTextColor() string {
	if c == nil {
		return ""
	}
	return c.TextColor
}

func (c *CreateCardsResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateCardsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateCardsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetArchivedAt sets the ArchivedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetArchivedAt(archivedAt string) {
	c.ArchivedAt = archivedAt
	c.require(createCardsResponseFieldArchivedAt)
}

// SetAuxiliaryFields sets the AuxiliaryFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetAuxiliaryFields(auxiliaryFields []string) {
	c.AuxiliaryFields = auxiliaryFields
	c.require(createCardsResponseFieldAuxiliaryFields)
}

// SetCardColor sets the CardColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetCardColor(cardColor string) {
	c.CardColor = cardColor
	c.require(createCardsResponseFieldCardColor)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createCardsResponseFieldCreatedAt)
}

// SetCustomerCardsCount sets the CustomerCardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetCustomerCardsCount(customerCardsCount int) {
	c.CustomerCardsCount = customerCardsCount
	c.require(createCardsResponseFieldCustomerCardsCount)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetExpiresAt(expiresAt string) {
	c.ExpiresAt = expiresAt
	c.require(createCardsResponseFieldExpiresAt)
}

// SetHeaderText sets the HeaderText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetHeaderText(headerText string) {
	c.HeaderText = headerText
	c.require(createCardsResponseFieldHeaderText)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetID(id int) {
	c.ID = id
	c.require(createCardsResponseFieldID)
}

// SetInitialStamps sets the InitialStamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetInitialStamps(initialStamps int) {
	c.InitialStamps = initialStamps
	c.require(createCardsResponseFieldInitialStamps)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetName(name string) {
	c.Name = name
	c.require(createCardsResponseFieldName)
}

// SetRewardsCount sets the RewardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetRewardsCount(rewardsCount int) {
	c.RewardsCount = rewardsCount
	c.require(createCardsResponseFieldRewardsCount)
}

// SetShowMemberField sets the ShowMemberField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetShowMemberField(showMemberField bool) {
	c.ShowMemberField = showMemberField
	c.require(createCardsResponseFieldShowMemberField)
}

// SetShowStampsToRewardField sets the ShowStampsToRewardField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetShowStampsToRewardField(showStampsToRewardField bool) {
	c.ShowStampsToRewardField = showStampsToRewardField
	c.require(createCardsResponseFieldShowStampsToRewardField)
}

// SetStampBackgroundColor sets the StampBackgroundColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStampBackgroundColor(stampBackgroundColor string) {
	c.StampBackgroundColor = stampBackgroundColor
	c.require(createCardsResponseFieldStampBackgroundColor)
}

// SetStampColor sets the StampColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStampColor(stampColor string) {
	c.StampColor = stampColor
	c.require(createCardsResponseFieldStampColor)
}

// SetStampIcon sets the StampIcon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStampIcon(stampIcon string) {
	c.StampIcon = stampIcon
	c.require(createCardsResponseFieldStampIcon)
}

// SetStampsRequired sets the StampsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStampsRequired(stampsRequired int) {
	c.StampsRequired = stampsRequired
	c.require(createCardsResponseFieldStampsRequired)
}

// SetStripColor sets the StripColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStripColor(stripColor string) {
	c.StripColor = stripColor
	c.require(createCardsResponseFieldStripColor)
}

// SetStripPreset sets the StripPreset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStripPreset(stripPreset string) {
	c.StripPreset = stripPreset
	c.require(createCardsResponseFieldStripPreset)
}

// SetStripType sets the StripType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetStripType(stripType string) {
	c.StripType = stripType
	c.require(createCardsResponseFieldStripType)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetTextColor(textColor string) {
	c.TextColor = textColor
	c.require(createCardsResponseFieldTextColor)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCardsResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createCardsResponseFieldUpdatedAt)
}

func (c *CreateCardsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCardsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateCardsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateCardsResponse) MarshalJSON() ([]byte, error) {
	type embed CreateCardsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateCardsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getCardsResponseFieldArchivedAt              = big.NewInt(1 << 0)
	getCardsResponseFieldAuxiliaryFields         = big.NewInt(1 << 1)
	getCardsResponseFieldCardColor               = big.NewInt(1 << 2)
	getCardsResponseFieldCreatedAt               = big.NewInt(1 << 3)
	getCardsResponseFieldCustomerCardsCount      = big.NewInt(1 << 4)
	getCardsResponseFieldExpiresAt               = big.NewInt(1 << 5)
	getCardsResponseFieldHeaderText              = big.NewInt(1 << 6)
	getCardsResponseFieldID                      = big.NewInt(1 << 7)
	getCardsResponseFieldInitialStamps           = big.NewInt(1 << 8)
	getCardsResponseFieldName                    = big.NewInt(1 << 9)
	getCardsResponseFieldRewardsCount            = big.NewInt(1 << 10)
	getCardsResponseFieldShowMemberField         = big.NewInt(1 << 11)
	getCardsResponseFieldShowStampsToRewardField = big.NewInt(1 << 12)
	getCardsResponseFieldStampBackgroundColor    = big.NewInt(1 << 13)
	getCardsResponseFieldStampColor              = big.NewInt(1 << 14)
	getCardsResponseFieldStampIcon               = big.NewInt(1 << 15)
	getCardsResponseFieldStampsRequired          = big.NewInt(1 << 16)
	getCardsResponseFieldStripColor              = big.NewInt(1 << 17)
	getCardsResponseFieldStripPreset             = big.NewInt(1 << 18)
	getCardsResponseFieldStripType               = big.NewInt(1 << 19)
	getCardsResponseFieldTextColor               = big.NewInt(1 << 20)
	getCardsResponseFieldUpdatedAt               = big.NewInt(1 << 21)
)

type GetCardsResponse struct {
	// ISO 8601 timestamp when the card was archived, or null if active
	ArchivedAt string `json:"archived_at" url:"archived_at"`
	// Up to two extra front-of-pass fields
	AuxiliaryFields []string `json:"auxiliary_fields" url:"auxiliary_fields"`
	// Hex colour for the card background (e.g. '#6B4226')
	CardColor string `json:"card_color" url:"card_color"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Number of customer card instances issued
	CustomerCardsCount int `json:"customer_cards_count" url:"customer_cards_count"`
	// ISO 8601 timestamp when the card expires, or null if it does not expire
	ExpiresAt string `json:"expires_at" url:"expires_at"`
	// Optional header text displayed on the card
	HeaderText string `json:"header_text" url:"header_text"`
	// Unique card ID
	ID int `json:"id" url:"id"`
	// Number of stamps pre-filled on new customer cards (0 to stamps_required - 1)
	InitialStamps int `json:"initial_stamps" url:"initial_stamps"`
	// Card name (e.g. 'Coffee Loyalty Card')
	Name string `json:"name" url:"name"`
	// Number of rewards defined for this card
	RewardsCount int `json:"rewards_count" url:"rewards_count"`
	// Whether wallet passes show the member name field
	ShowMemberField bool `json:"show_member_field" url:"show_member_field"`
	// Whether wallet passes show the stamps-to-reward field
	ShowStampsToRewardField bool `json:"show_stamps_to_reward_field" url:"show_stamps_to_reward_field"`
	// Hex colour for stamp backgrounds
	StampBackgroundColor string `json:"stamp_background_color" url:"stamp_background_color"`
	// Hex colour for stamp icons
	StampColor string `json:"stamp_color" url:"stamp_color"`
	// Icon used for stamps (e.g. 'coffee', 'heart', 'star')
	StampIcon string `json:"stamp_icon" url:"stamp_icon"`
	// Number of stamps needed to complete the card (1–21)
	StampsRequired int `json:"stamps_required" url:"stamps_required"`
	// Hex colour for the strip (when strip_type is 'color')
	StripColor string `json:"strip_color" url:"strip_color"`
	// Preset strip image identifier (when strip_type is 'preset')
	StripPreset string `json:"strip_preset" url:"strip_preset"`
	// Strip image type: 'color', 'image', or 'preset'
	StripType string `json:"strip_type" url:"strip_type"`
	// Hex colour for card text
	TextColor string `json:"text_color" url:"text_color"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetCardsResponse) GetArchivedAt() string {
	if g == nil {
		return ""
	}
	return g.ArchivedAt
}

func (g *GetCardsResponse) GetAuxiliaryFields() []string {
	if g == nil {
		return nil
	}
	return g.AuxiliaryFields
}

func (g *GetCardsResponse) GetCardColor() string {
	if g == nil {
		return ""
	}
	return g.CardColor
}

func (g *GetCardsResponse) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetCardsResponse) GetCustomerCardsCount() int {
	if g == nil {
		return 0
	}
	return g.CustomerCardsCount
}

func (g *GetCardsResponse) GetExpiresAt() string {
	if g == nil {
		return ""
	}
	return g.ExpiresAt
}

func (g *GetCardsResponse) GetHeaderText() string {
	if g == nil {
		return ""
	}
	return g.HeaderText
}

func (g *GetCardsResponse) GetID() int {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetCardsResponse) GetInitialStamps() int {
	if g == nil {
		return 0
	}
	return g.InitialStamps
}

func (g *GetCardsResponse) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetCardsResponse) GetRewardsCount() int {
	if g == nil {
		return 0
	}
	return g.RewardsCount
}

func (g *GetCardsResponse) GetShowMemberField() bool {
	if g == nil {
		return false
	}
	return g.ShowMemberField
}

func (g *GetCardsResponse) GetShowStampsToRewardField() bool {
	if g == nil {
		return false
	}
	return g.ShowStampsToRewardField
}

func (g *GetCardsResponse) GetStampBackgroundColor() string {
	if g == nil {
		return ""
	}
	return g.StampBackgroundColor
}

func (g *GetCardsResponse) GetStampColor() string {
	if g == nil {
		return ""
	}
	return g.StampColor
}

func (g *GetCardsResponse) GetStampIcon() string {
	if g == nil {
		return ""
	}
	return g.StampIcon
}

func (g *GetCardsResponse) GetStampsRequired() int {
	if g == nil {
		return 0
	}
	return g.StampsRequired
}

func (g *GetCardsResponse) GetStripColor() string {
	if g == nil {
		return ""
	}
	return g.StripColor
}

func (g *GetCardsResponse) GetStripPreset() string {
	if g == nil {
		return ""
	}
	return g.StripPreset
}

func (g *GetCardsResponse) GetStripType() string {
	if g == nil {
		return ""
	}
	return g.StripType
}

func (g *GetCardsResponse) GetTextColor() string {
	if g == nil {
		return ""
	}
	return g.TextColor
}

func (g *GetCardsResponse) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetCardsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetCardsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetArchivedAt sets the ArchivedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetArchivedAt(archivedAt string) {
	g.ArchivedAt = archivedAt
	g.require(getCardsResponseFieldArchivedAt)
}

// SetAuxiliaryFields sets the AuxiliaryFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetAuxiliaryFields(auxiliaryFields []string) {
	g.AuxiliaryFields = auxiliaryFields
	g.require(getCardsResponseFieldAuxiliaryFields)
}

// SetCardColor sets the CardColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetCardColor(cardColor string) {
	g.CardColor = cardColor
	g.require(getCardsResponseFieldCardColor)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getCardsResponseFieldCreatedAt)
}

// SetCustomerCardsCount sets the CustomerCardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetCustomerCardsCount(customerCardsCount int) {
	g.CustomerCardsCount = customerCardsCount
	g.require(getCardsResponseFieldCustomerCardsCount)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetExpiresAt(expiresAt string) {
	g.ExpiresAt = expiresAt
	g.require(getCardsResponseFieldExpiresAt)
}

// SetHeaderText sets the HeaderText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetHeaderText(headerText string) {
	g.HeaderText = headerText
	g.require(getCardsResponseFieldHeaderText)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetID(id int) {
	g.ID = id
	g.require(getCardsResponseFieldID)
}

// SetInitialStamps sets the InitialStamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetInitialStamps(initialStamps int) {
	g.InitialStamps = initialStamps
	g.require(getCardsResponseFieldInitialStamps)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetName(name string) {
	g.Name = name
	g.require(getCardsResponseFieldName)
}

// SetRewardsCount sets the RewardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetRewardsCount(rewardsCount int) {
	g.RewardsCount = rewardsCount
	g.require(getCardsResponseFieldRewardsCount)
}

// SetShowMemberField sets the ShowMemberField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetShowMemberField(showMemberField bool) {
	g.ShowMemberField = showMemberField
	g.require(getCardsResponseFieldShowMemberField)
}

// SetShowStampsToRewardField sets the ShowStampsToRewardField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetShowStampsToRewardField(showStampsToRewardField bool) {
	g.ShowStampsToRewardField = showStampsToRewardField
	g.require(getCardsResponseFieldShowStampsToRewardField)
}

// SetStampBackgroundColor sets the StampBackgroundColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStampBackgroundColor(stampBackgroundColor string) {
	g.StampBackgroundColor = stampBackgroundColor
	g.require(getCardsResponseFieldStampBackgroundColor)
}

// SetStampColor sets the StampColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStampColor(stampColor string) {
	g.StampColor = stampColor
	g.require(getCardsResponseFieldStampColor)
}

// SetStampIcon sets the StampIcon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStampIcon(stampIcon string) {
	g.StampIcon = stampIcon
	g.require(getCardsResponseFieldStampIcon)
}

// SetStampsRequired sets the StampsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStampsRequired(stampsRequired int) {
	g.StampsRequired = stampsRequired
	g.require(getCardsResponseFieldStampsRequired)
}

// SetStripColor sets the StripColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStripColor(stripColor string) {
	g.StripColor = stripColor
	g.require(getCardsResponseFieldStripColor)
}

// SetStripPreset sets the StripPreset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStripPreset(stripPreset string) {
	g.StripPreset = stripPreset
	g.require(getCardsResponseFieldStripPreset)
}

// SetStripType sets the StripType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetStripType(stripType string) {
	g.StripType = stripType
	g.require(getCardsResponseFieldStripType)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetTextColor(textColor string) {
	g.TextColor = textColor
	g.require(getCardsResponseFieldTextColor)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCardsResponse) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getCardsResponseFieldUpdatedAt)
}

func (g *GetCardsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCardsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCardsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCardsResponse) MarshalJSON() ([]byte, error) {
	type embed GetCardsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetCardsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listCardsResponseItemFieldArchivedAt              = big.NewInt(1 << 0)
	listCardsResponseItemFieldAuxiliaryFields         = big.NewInt(1 << 1)
	listCardsResponseItemFieldCardColor               = big.NewInt(1 << 2)
	listCardsResponseItemFieldCreatedAt               = big.NewInt(1 << 3)
	listCardsResponseItemFieldCustomerCardsCount      = big.NewInt(1 << 4)
	listCardsResponseItemFieldExpiresAt               = big.NewInt(1 << 5)
	listCardsResponseItemFieldHeaderText              = big.NewInt(1 << 6)
	listCardsResponseItemFieldID                      = big.NewInt(1 << 7)
	listCardsResponseItemFieldInitialStamps           = big.NewInt(1 << 8)
	listCardsResponseItemFieldName                    = big.NewInt(1 << 9)
	listCardsResponseItemFieldRewardsCount            = big.NewInt(1 << 10)
	listCardsResponseItemFieldShowMemberField         = big.NewInt(1 << 11)
	listCardsResponseItemFieldShowStampsToRewardField = big.NewInt(1 << 12)
	listCardsResponseItemFieldStampBackgroundColor    = big.NewInt(1 << 13)
	listCardsResponseItemFieldStampColor              = big.NewInt(1 << 14)
	listCardsResponseItemFieldStampIcon               = big.NewInt(1 << 15)
	listCardsResponseItemFieldStampsRequired          = big.NewInt(1 << 16)
	listCardsResponseItemFieldStripColor              = big.NewInt(1 << 17)
	listCardsResponseItemFieldStripPreset             = big.NewInt(1 << 18)
	listCardsResponseItemFieldStripType               = big.NewInt(1 << 19)
	listCardsResponseItemFieldTextColor               = big.NewInt(1 << 20)
	listCardsResponseItemFieldUpdatedAt               = big.NewInt(1 << 21)
)

type ListCardsResponseItem struct {
	// ISO 8601 timestamp when the card was archived, or null if active
	ArchivedAt string `json:"archived_at" url:"archived_at"`
	// Up to two extra front-of-pass fields
	AuxiliaryFields []string `json:"auxiliary_fields" url:"auxiliary_fields"`
	// Hex colour for the card background (e.g. '#6B4226')
	CardColor string `json:"card_color" url:"card_color"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Number of customer card instances issued
	CustomerCardsCount int `json:"customer_cards_count" url:"customer_cards_count"`
	// ISO 8601 timestamp when the card expires, or null if it does not expire
	ExpiresAt string `json:"expires_at" url:"expires_at"`
	// Optional header text displayed on the card
	HeaderText string `json:"header_text" url:"header_text"`
	// Unique card ID
	ID int `json:"id" url:"id"`
	// Number of stamps pre-filled on new customer cards (0 to stamps_required - 1)
	InitialStamps int `json:"initial_stamps" url:"initial_stamps"`
	// Card name (e.g. 'Coffee Loyalty Card')
	Name string `json:"name" url:"name"`
	// Number of rewards defined for this card
	RewardsCount int `json:"rewards_count" url:"rewards_count"`
	// Whether wallet passes show the member name field
	ShowMemberField bool `json:"show_member_field" url:"show_member_field"`
	// Whether wallet passes show the stamps-to-reward field
	ShowStampsToRewardField bool `json:"show_stamps_to_reward_field" url:"show_stamps_to_reward_field"`
	// Hex colour for stamp backgrounds
	StampBackgroundColor string `json:"stamp_background_color" url:"stamp_background_color"`
	// Hex colour for stamp icons
	StampColor string `json:"stamp_color" url:"stamp_color"`
	// Icon used for stamps (e.g. 'coffee', 'heart', 'star')
	StampIcon string `json:"stamp_icon" url:"stamp_icon"`
	// Number of stamps needed to complete the card (1–21)
	StampsRequired int `json:"stamps_required" url:"stamps_required"`
	// Hex colour for the strip (when strip_type is 'color')
	StripColor string `json:"strip_color" url:"strip_color"`
	// Preset strip image identifier (when strip_type is 'preset')
	StripPreset string `json:"strip_preset" url:"strip_preset"`
	// Strip image type: 'color', 'image', or 'preset'
	StripType string `json:"strip_type" url:"strip_type"`
	// Hex colour for card text
	TextColor string `json:"text_color" url:"text_color"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListCardsResponseItem) GetArchivedAt() string {
	if l == nil {
		return ""
	}
	return l.ArchivedAt
}

func (l *ListCardsResponseItem) GetAuxiliaryFields() []string {
	if l == nil {
		return nil
	}
	return l.AuxiliaryFields
}

func (l *ListCardsResponseItem) GetCardColor() string {
	if l == nil {
		return ""
	}
	return l.CardColor
}

func (l *ListCardsResponseItem) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListCardsResponseItem) GetCustomerCardsCount() int {
	if l == nil {
		return 0
	}
	return l.CustomerCardsCount
}

func (l *ListCardsResponseItem) GetExpiresAt() string {
	if l == nil {
		return ""
	}
	return l.ExpiresAt
}

func (l *ListCardsResponseItem) GetHeaderText() string {
	if l == nil {
		return ""
	}
	return l.HeaderText
}

func (l *ListCardsResponseItem) GetID() int {
	if l == nil {
		return 0
	}
	return l.ID
}

func (l *ListCardsResponseItem) GetInitialStamps() int {
	if l == nil {
		return 0
	}
	return l.InitialStamps
}

func (l *ListCardsResponseItem) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListCardsResponseItem) GetRewardsCount() int {
	if l == nil {
		return 0
	}
	return l.RewardsCount
}

func (l *ListCardsResponseItem) GetShowMemberField() bool {
	if l == nil {
		return false
	}
	return l.ShowMemberField
}

func (l *ListCardsResponseItem) GetShowStampsToRewardField() bool {
	if l == nil {
		return false
	}
	return l.ShowStampsToRewardField
}

func (l *ListCardsResponseItem) GetStampBackgroundColor() string {
	if l == nil {
		return ""
	}
	return l.StampBackgroundColor
}

func (l *ListCardsResponseItem) GetStampColor() string {
	if l == nil {
		return ""
	}
	return l.StampColor
}

func (l *ListCardsResponseItem) GetStampIcon() string {
	if l == nil {
		return ""
	}
	return l.StampIcon
}

func (l *ListCardsResponseItem) GetStampsRequired() int {
	if l == nil {
		return 0
	}
	return l.StampsRequired
}

func (l *ListCardsResponseItem) GetStripColor() string {
	if l == nil {
		return ""
	}
	return l.StripColor
}

func (l *ListCardsResponseItem) GetStripPreset() string {
	if l == nil {
		return ""
	}
	return l.StripPreset
}

func (l *ListCardsResponseItem) GetStripType() string {
	if l == nil {
		return ""
	}
	return l.StripType
}

func (l *ListCardsResponseItem) GetTextColor() string {
	if l == nil {
		return ""
	}
	return l.TextColor
}

func (l *ListCardsResponseItem) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListCardsResponseItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListCardsResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetArchivedAt sets the ArchivedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetArchivedAt(archivedAt string) {
	l.ArchivedAt = archivedAt
	l.require(listCardsResponseItemFieldArchivedAt)
}

// SetAuxiliaryFields sets the AuxiliaryFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetAuxiliaryFields(auxiliaryFields []string) {
	l.AuxiliaryFields = auxiliaryFields
	l.require(listCardsResponseItemFieldAuxiliaryFields)
}

// SetCardColor sets the CardColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetCardColor(cardColor string) {
	l.CardColor = cardColor
	l.require(listCardsResponseItemFieldCardColor)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetCreatedAt(createdAt string) {
	l.CreatedAt = createdAt
	l.require(listCardsResponseItemFieldCreatedAt)
}

// SetCustomerCardsCount sets the CustomerCardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetCustomerCardsCount(customerCardsCount int) {
	l.CustomerCardsCount = customerCardsCount
	l.require(listCardsResponseItemFieldCustomerCardsCount)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetExpiresAt(expiresAt string) {
	l.ExpiresAt = expiresAt
	l.require(listCardsResponseItemFieldExpiresAt)
}

// SetHeaderText sets the HeaderText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetHeaderText(headerText string) {
	l.HeaderText = headerText
	l.require(listCardsResponseItemFieldHeaderText)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetID(id int) {
	l.ID = id
	l.require(listCardsResponseItemFieldID)
}

// SetInitialStamps sets the InitialStamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetInitialStamps(initialStamps int) {
	l.InitialStamps = initialStamps
	l.require(listCardsResponseItemFieldInitialStamps)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetName(name string) {
	l.Name = name
	l.require(listCardsResponseItemFieldName)
}

// SetRewardsCount sets the RewardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetRewardsCount(rewardsCount int) {
	l.RewardsCount = rewardsCount
	l.require(listCardsResponseItemFieldRewardsCount)
}

// SetShowMemberField sets the ShowMemberField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetShowMemberField(showMemberField bool) {
	l.ShowMemberField = showMemberField
	l.require(listCardsResponseItemFieldShowMemberField)
}

// SetShowStampsToRewardField sets the ShowStampsToRewardField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetShowStampsToRewardField(showStampsToRewardField bool) {
	l.ShowStampsToRewardField = showStampsToRewardField
	l.require(listCardsResponseItemFieldShowStampsToRewardField)
}

// SetStampBackgroundColor sets the StampBackgroundColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStampBackgroundColor(stampBackgroundColor string) {
	l.StampBackgroundColor = stampBackgroundColor
	l.require(listCardsResponseItemFieldStampBackgroundColor)
}

// SetStampColor sets the StampColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStampColor(stampColor string) {
	l.StampColor = stampColor
	l.require(listCardsResponseItemFieldStampColor)
}

// SetStampIcon sets the StampIcon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStampIcon(stampIcon string) {
	l.StampIcon = stampIcon
	l.require(listCardsResponseItemFieldStampIcon)
}

// SetStampsRequired sets the StampsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStampsRequired(stampsRequired int) {
	l.StampsRequired = stampsRequired
	l.require(listCardsResponseItemFieldStampsRequired)
}

// SetStripColor sets the StripColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStripColor(stripColor string) {
	l.StripColor = stripColor
	l.require(listCardsResponseItemFieldStripColor)
}

// SetStripPreset sets the StripPreset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStripPreset(stripPreset string) {
	l.StripPreset = stripPreset
	l.require(listCardsResponseItemFieldStripPreset)
}

// SetStripType sets the StripType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetStripType(stripType string) {
	l.StripType = stripType
	l.require(listCardsResponseItemFieldStripType)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetTextColor(textColor string) {
	l.TextColor = textColor
	l.require(listCardsResponseItemFieldTextColor)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCardsResponseItem) SetUpdatedAt(updatedAt string) {
	l.UpdatedAt = updatedAt
	l.require(listCardsResponseItemFieldUpdatedAt)
}

func (l *ListCardsResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListCardsResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListCardsResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListCardsResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListCardsResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListCardsResponseItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	updateCardsRequestCardFieldAuxiliaryFields         = big.NewInt(1 << 0)
	updateCardsRequestCardFieldCardColor               = big.NewInt(1 << 1)
	updateCardsRequestCardFieldExpiresAt               = big.NewInt(1 << 2)
	updateCardsRequestCardFieldHeaderText              = big.NewInt(1 << 3)
	updateCardsRequestCardFieldInitialStamps           = big.NewInt(1 << 4)
	updateCardsRequestCardFieldName                    = big.NewInt(1 << 5)
	updateCardsRequestCardFieldShowMemberField         = big.NewInt(1 << 6)
	updateCardsRequestCardFieldShowStampsToRewardField = big.NewInt(1 << 7)
	updateCardsRequestCardFieldStampBackgroundColor    = big.NewInt(1 << 8)
	updateCardsRequestCardFieldStampColor              = big.NewInt(1 << 9)
	updateCardsRequestCardFieldStampIcon               = big.NewInt(1 << 10)
	updateCardsRequestCardFieldStampsRequired          = big.NewInt(1 << 11)
	updateCardsRequestCardFieldStripColor              = big.NewInt(1 << 12)
	updateCardsRequestCardFieldStripPreset             = big.NewInt(1 << 13)
	updateCardsRequestCardFieldStripType               = big.NewInt(1 << 14)
	updateCardsRequestCardFieldTextColor               = big.NewInt(1 << 15)
)

type UpdateCardsRequestCard struct {
	// Up to two extra front-of-pass fields. Blank values are ignored.
	AuxiliaryFields []string `json:"auxiliary_fields,omitempty" url:"auxiliary_fields,omitempty"`
	// Hex colour for the card background
	CardColor *string `json:"card_color,omitempty" url:"card_color,omitempty"`
	// Card expiry timestamp (ISO 8601)
	ExpiresAt *string `json:"expires_at,omitempty" url:"expires_at,omitempty"`
	// Optional header text displayed on the card
	HeaderText *string `json:"header_text,omitempty" url:"header_text,omitempty"`
	// Pre-filled stamps (must be >= 0 and < stamps_required)
	InitialStamps *int `json:"initial_stamps,omitempty" url:"initial_stamps,omitempty"`
	// Card name
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Whether wallet passes show the member name field
	ShowMemberField *bool `json:"show_member_field,omitempty" url:"show_member_field,omitempty"`
	// Whether wallet passes show the stamps-to-reward field
	ShowStampsToRewardField *bool `json:"show_stamps_to_reward_field,omitempty" url:"show_stamps_to_reward_field,omitempty"`
	// Hex colour for stamp backgrounds
	StampBackgroundColor *string `json:"stamp_background_color,omitempty" url:"stamp_background_color,omitempty"`
	// Hex colour for stamp icons
	StampColor *string `json:"stamp_color,omitempty" url:"stamp_color,omitempty"`
	// Stamp icon identifier
	StampIcon *string `json:"stamp_icon,omitempty" url:"stamp_icon,omitempty"`
	// Number of stamps needed (1–21)
	StampsRequired *int `json:"stamps_required,omitempty" url:"stamps_required,omitempty"`
	// Hex colour for the strip
	StripColor *string `json:"strip_color,omitempty" url:"strip_color,omitempty"`
	// Preset strip image identifier
	StripPreset *string `json:"strip_preset,omitempty" url:"strip_preset,omitempty"`
	// Strip image type
	StripType *string `json:"strip_type,omitempty" url:"strip_type,omitempty"`
	// Hex colour for card text
	TextColor *string `json:"text_color,omitempty" url:"text_color,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateCardsRequestCard) GetAuxiliaryFields() []string {
	if u == nil {
		return nil
	}
	return u.AuxiliaryFields
}

func (u *UpdateCardsRequestCard) GetCardColor() *string {
	if u == nil {
		return nil
	}
	return u.CardColor
}

func (u *UpdateCardsRequestCard) GetExpiresAt() *string {
	if u == nil {
		return nil
	}
	return u.ExpiresAt
}

func (u *UpdateCardsRequestCard) GetHeaderText() *string {
	if u == nil {
		return nil
	}
	return u.HeaderText
}

func (u *UpdateCardsRequestCard) GetInitialStamps() *int {
	if u == nil {
		return nil
	}
	return u.InitialStamps
}

func (u *UpdateCardsRequestCard) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateCardsRequestCard) GetShowMemberField() *bool {
	if u == nil {
		return nil
	}
	return u.ShowMemberField
}

func (u *UpdateCardsRequestCard) GetShowStampsToRewardField() *bool {
	if u == nil {
		return nil
	}
	return u.ShowStampsToRewardField
}

func (u *UpdateCardsRequestCard) GetStampBackgroundColor() *string {
	if u == nil {
		return nil
	}
	return u.StampBackgroundColor
}

func (u *UpdateCardsRequestCard) GetStampColor() *string {
	if u == nil {
		return nil
	}
	return u.StampColor
}

func (u *UpdateCardsRequestCard) GetStampIcon() *string {
	if u == nil {
		return nil
	}
	return u.StampIcon
}

func (u *UpdateCardsRequestCard) GetStampsRequired() *int {
	if u == nil {
		return nil
	}
	return u.StampsRequired
}

func (u *UpdateCardsRequestCard) GetStripColor() *string {
	if u == nil {
		return nil
	}
	return u.StripColor
}

func (u *UpdateCardsRequestCard) GetStripPreset() *string {
	if u == nil {
		return nil
	}
	return u.StripPreset
}

func (u *UpdateCardsRequestCard) GetStripType() *string {
	if u == nil {
		return nil
	}
	return u.StripType
}

func (u *UpdateCardsRequestCard) GetTextColor() *string {
	if u == nil {
		return nil
	}
	return u.TextColor
}

func (u *UpdateCardsRequestCard) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateCardsRequestCard) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAuxiliaryFields sets the AuxiliaryFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetAuxiliaryFields(auxiliaryFields []string) {
	u.AuxiliaryFields = auxiliaryFields
	u.require(updateCardsRequestCardFieldAuxiliaryFields)
}

// SetCardColor sets the CardColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetCardColor(cardColor *string) {
	u.CardColor = cardColor
	u.require(updateCardsRequestCardFieldCardColor)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetExpiresAt(expiresAt *string) {
	u.ExpiresAt = expiresAt
	u.require(updateCardsRequestCardFieldExpiresAt)
}

// SetHeaderText sets the HeaderText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetHeaderText(headerText *string) {
	u.HeaderText = headerText
	u.require(updateCardsRequestCardFieldHeaderText)
}

// SetInitialStamps sets the InitialStamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetInitialStamps(initialStamps *int) {
	u.InitialStamps = initialStamps
	u.require(updateCardsRequestCardFieldInitialStamps)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetName(name *string) {
	u.Name = name
	u.require(updateCardsRequestCardFieldName)
}

// SetShowMemberField sets the ShowMemberField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetShowMemberField(showMemberField *bool) {
	u.ShowMemberField = showMemberField
	u.require(updateCardsRequestCardFieldShowMemberField)
}

// SetShowStampsToRewardField sets the ShowStampsToRewardField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetShowStampsToRewardField(showStampsToRewardField *bool) {
	u.ShowStampsToRewardField = showStampsToRewardField
	u.require(updateCardsRequestCardFieldShowStampsToRewardField)
}

// SetStampBackgroundColor sets the StampBackgroundColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStampBackgroundColor(stampBackgroundColor *string) {
	u.StampBackgroundColor = stampBackgroundColor
	u.require(updateCardsRequestCardFieldStampBackgroundColor)
}

// SetStampColor sets the StampColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStampColor(stampColor *string) {
	u.StampColor = stampColor
	u.require(updateCardsRequestCardFieldStampColor)
}

// SetStampIcon sets the StampIcon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStampIcon(stampIcon *string) {
	u.StampIcon = stampIcon
	u.require(updateCardsRequestCardFieldStampIcon)
}

// SetStampsRequired sets the StampsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStampsRequired(stampsRequired *int) {
	u.StampsRequired = stampsRequired
	u.require(updateCardsRequestCardFieldStampsRequired)
}

// SetStripColor sets the StripColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStripColor(stripColor *string) {
	u.StripColor = stripColor
	u.require(updateCardsRequestCardFieldStripColor)
}

// SetStripPreset sets the StripPreset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStripPreset(stripPreset *string) {
	u.StripPreset = stripPreset
	u.require(updateCardsRequestCardFieldStripPreset)
}

// SetStripType sets the StripType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetStripType(stripType *string) {
	u.StripType = stripType
	u.require(updateCardsRequestCardFieldStripType)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequestCard) SetTextColor(textColor *string) {
	u.TextColor = textColor
	u.require(updateCardsRequestCardFieldTextColor)
}

func (u *UpdateCardsRequestCard) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateCardsRequestCard
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateCardsRequestCard(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateCardsRequestCard) MarshalJSON() ([]byte, error) {
	type embed UpdateCardsRequestCard
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateCardsRequestCard) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateCardsResponseFieldArchivedAt              = big.NewInt(1 << 0)
	updateCardsResponseFieldAuxiliaryFields         = big.NewInt(1 << 1)
	updateCardsResponseFieldCardColor               = big.NewInt(1 << 2)
	updateCardsResponseFieldCreatedAt               = big.NewInt(1 << 3)
	updateCardsResponseFieldCustomerCardsCount      = big.NewInt(1 << 4)
	updateCardsResponseFieldExpiresAt               = big.NewInt(1 << 5)
	updateCardsResponseFieldHeaderText              = big.NewInt(1 << 6)
	updateCardsResponseFieldID                      = big.NewInt(1 << 7)
	updateCardsResponseFieldInitialStamps           = big.NewInt(1 << 8)
	updateCardsResponseFieldName                    = big.NewInt(1 << 9)
	updateCardsResponseFieldRewardsCount            = big.NewInt(1 << 10)
	updateCardsResponseFieldShowMemberField         = big.NewInt(1 << 11)
	updateCardsResponseFieldShowStampsToRewardField = big.NewInt(1 << 12)
	updateCardsResponseFieldStampBackgroundColor    = big.NewInt(1 << 13)
	updateCardsResponseFieldStampColor              = big.NewInt(1 << 14)
	updateCardsResponseFieldStampIcon               = big.NewInt(1 << 15)
	updateCardsResponseFieldStampsRequired          = big.NewInt(1 << 16)
	updateCardsResponseFieldStripColor              = big.NewInt(1 << 17)
	updateCardsResponseFieldStripPreset             = big.NewInt(1 << 18)
	updateCardsResponseFieldStripType               = big.NewInt(1 << 19)
	updateCardsResponseFieldTextColor               = big.NewInt(1 << 20)
	updateCardsResponseFieldUpdatedAt               = big.NewInt(1 << 21)
)

type UpdateCardsResponse struct {
	// ISO 8601 timestamp when the card was archived, or null if active
	ArchivedAt string `json:"archived_at" url:"archived_at"`
	// Up to two extra front-of-pass fields
	AuxiliaryFields []string `json:"auxiliary_fields" url:"auxiliary_fields"`
	// Hex colour for the card background (e.g. '#6B4226')
	CardColor string `json:"card_color" url:"card_color"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Number of customer card instances issued
	CustomerCardsCount int `json:"customer_cards_count" url:"customer_cards_count"`
	// ISO 8601 timestamp when the card expires, or null if it does not expire
	ExpiresAt string `json:"expires_at" url:"expires_at"`
	// Optional header text displayed on the card
	HeaderText string `json:"header_text" url:"header_text"`
	// Unique card ID
	ID int `json:"id" url:"id"`
	// Number of stamps pre-filled on new customer cards (0 to stamps_required - 1)
	InitialStamps int `json:"initial_stamps" url:"initial_stamps"`
	// Card name (e.g. 'Coffee Loyalty Card')
	Name string `json:"name" url:"name"`
	// Number of rewards defined for this card
	RewardsCount int `json:"rewards_count" url:"rewards_count"`
	// Whether wallet passes show the member name field
	ShowMemberField bool `json:"show_member_field" url:"show_member_field"`
	// Whether wallet passes show the stamps-to-reward field
	ShowStampsToRewardField bool `json:"show_stamps_to_reward_field" url:"show_stamps_to_reward_field"`
	// Hex colour for stamp backgrounds
	StampBackgroundColor string `json:"stamp_background_color" url:"stamp_background_color"`
	// Hex colour for stamp icons
	StampColor string `json:"stamp_color" url:"stamp_color"`
	// Icon used for stamps (e.g. 'coffee', 'heart', 'star')
	StampIcon string `json:"stamp_icon" url:"stamp_icon"`
	// Number of stamps needed to complete the card (1–21)
	StampsRequired int `json:"stamps_required" url:"stamps_required"`
	// Hex colour for the strip (when strip_type is 'color')
	StripColor string `json:"strip_color" url:"strip_color"`
	// Preset strip image identifier (when strip_type is 'preset')
	StripPreset string `json:"strip_preset" url:"strip_preset"`
	// Strip image type: 'color', 'image', or 'preset'
	StripType string `json:"strip_type" url:"strip_type"`
	// Hex colour for card text
	TextColor string `json:"text_color" url:"text_color"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateCardsResponse) GetArchivedAt() string {
	if u == nil {
		return ""
	}
	return u.ArchivedAt
}

func (u *UpdateCardsResponse) GetAuxiliaryFields() []string {
	if u == nil {
		return nil
	}
	return u.AuxiliaryFields
}

func (u *UpdateCardsResponse) GetCardColor() string {
	if u == nil {
		return ""
	}
	return u.CardColor
}

func (u *UpdateCardsResponse) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateCardsResponse) GetCustomerCardsCount() int {
	if u == nil {
		return 0
	}
	return u.CustomerCardsCount
}

func (u *UpdateCardsResponse) GetExpiresAt() string {
	if u == nil {
		return ""
	}
	return u.ExpiresAt
}

func (u *UpdateCardsResponse) GetHeaderText() string {
	if u == nil {
		return ""
	}
	return u.HeaderText
}

func (u *UpdateCardsResponse) GetID() int {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateCardsResponse) GetInitialStamps() int {
	if u == nil {
		return 0
	}
	return u.InitialStamps
}

func (u *UpdateCardsResponse) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateCardsResponse) GetRewardsCount() int {
	if u == nil {
		return 0
	}
	return u.RewardsCount
}

func (u *UpdateCardsResponse) GetShowMemberField() bool {
	if u == nil {
		return false
	}
	return u.ShowMemberField
}

func (u *UpdateCardsResponse) GetShowStampsToRewardField() bool {
	if u == nil {
		return false
	}
	return u.ShowStampsToRewardField
}

func (u *UpdateCardsResponse) GetStampBackgroundColor() string {
	if u == nil {
		return ""
	}
	return u.StampBackgroundColor
}

func (u *UpdateCardsResponse) GetStampColor() string {
	if u == nil {
		return ""
	}
	return u.StampColor
}

func (u *UpdateCardsResponse) GetStampIcon() string {
	if u == nil {
		return ""
	}
	return u.StampIcon
}

func (u *UpdateCardsResponse) GetStampsRequired() int {
	if u == nil {
		return 0
	}
	return u.StampsRequired
}

func (u *UpdateCardsResponse) GetStripColor() string {
	if u == nil {
		return ""
	}
	return u.StripColor
}

func (u *UpdateCardsResponse) GetStripPreset() string {
	if u == nil {
		return ""
	}
	return u.StripPreset
}

func (u *UpdateCardsResponse) GetStripType() string {
	if u == nil {
		return ""
	}
	return u.StripType
}

func (u *UpdateCardsResponse) GetTextColor() string {
	if u == nil {
		return ""
	}
	return u.TextColor
}

func (u *UpdateCardsResponse) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateCardsResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateCardsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetArchivedAt sets the ArchivedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetArchivedAt(archivedAt string) {
	u.ArchivedAt = archivedAt
	u.require(updateCardsResponseFieldArchivedAt)
}

// SetAuxiliaryFields sets the AuxiliaryFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetAuxiliaryFields(auxiliaryFields []string) {
	u.AuxiliaryFields = auxiliaryFields
	u.require(updateCardsResponseFieldAuxiliaryFields)
}

// SetCardColor sets the CardColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetCardColor(cardColor string) {
	u.CardColor = cardColor
	u.require(updateCardsResponseFieldCardColor)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updateCardsResponseFieldCreatedAt)
}

// SetCustomerCardsCount sets the CustomerCardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetCustomerCardsCount(customerCardsCount int) {
	u.CustomerCardsCount = customerCardsCount
	u.require(updateCardsResponseFieldCustomerCardsCount)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetExpiresAt(expiresAt string) {
	u.ExpiresAt = expiresAt
	u.require(updateCardsResponseFieldExpiresAt)
}

// SetHeaderText sets the HeaderText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetHeaderText(headerText string) {
	u.HeaderText = headerText
	u.require(updateCardsResponseFieldHeaderText)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetID(id int) {
	u.ID = id
	u.require(updateCardsResponseFieldID)
}

// SetInitialStamps sets the InitialStamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetInitialStamps(initialStamps int) {
	u.InitialStamps = initialStamps
	u.require(updateCardsResponseFieldInitialStamps)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetName(name string) {
	u.Name = name
	u.require(updateCardsResponseFieldName)
}

// SetRewardsCount sets the RewardsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetRewardsCount(rewardsCount int) {
	u.RewardsCount = rewardsCount
	u.require(updateCardsResponseFieldRewardsCount)
}

// SetShowMemberField sets the ShowMemberField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetShowMemberField(showMemberField bool) {
	u.ShowMemberField = showMemberField
	u.require(updateCardsResponseFieldShowMemberField)
}

// SetShowStampsToRewardField sets the ShowStampsToRewardField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetShowStampsToRewardField(showStampsToRewardField bool) {
	u.ShowStampsToRewardField = showStampsToRewardField
	u.require(updateCardsResponseFieldShowStampsToRewardField)
}

// SetStampBackgroundColor sets the StampBackgroundColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStampBackgroundColor(stampBackgroundColor string) {
	u.StampBackgroundColor = stampBackgroundColor
	u.require(updateCardsResponseFieldStampBackgroundColor)
}

// SetStampColor sets the StampColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStampColor(stampColor string) {
	u.StampColor = stampColor
	u.require(updateCardsResponseFieldStampColor)
}

// SetStampIcon sets the StampIcon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStampIcon(stampIcon string) {
	u.StampIcon = stampIcon
	u.require(updateCardsResponseFieldStampIcon)
}

// SetStampsRequired sets the StampsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStampsRequired(stampsRequired int) {
	u.StampsRequired = stampsRequired
	u.require(updateCardsResponseFieldStampsRequired)
}

// SetStripColor sets the StripColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStripColor(stripColor string) {
	u.StripColor = stripColor
	u.require(updateCardsResponseFieldStripColor)
}

// SetStripPreset sets the StripPreset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStripPreset(stripPreset string) {
	u.StripPreset = stripPreset
	u.require(updateCardsResponseFieldStripPreset)
}

// SetStripType sets the StripType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetStripType(stripType string) {
	u.StripType = stripType
	u.require(updateCardsResponseFieldStripType)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetTextColor(textColor string) {
	u.TextColor = textColor
	u.require(updateCardsResponseFieldTextColor)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsResponse) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updateCardsResponseFieldUpdatedAt)
}

func (u *UpdateCardsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateCardsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateCardsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateCardsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateCardsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateCardsResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateCardsRequestFieldAccountID = big.NewInt(1 << 0)
	updateCardsRequestFieldID        = big.NewInt(1 << 1)
	updateCardsRequestFieldCard      = big.NewInt(1 << 2)
)

type UpdateCardsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`
	// Card ID
	ID   int                     `json:"-" url:"-"`
	Card *UpdateCardsRequestCard `json:"card" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateCardsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequest) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updateCardsRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequest) SetID(id int) {
	u.ID = id
	u.require(updateCardsRequestFieldID)
}

// SetCard sets the Card field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCardsRequest) SetCard(card *UpdateCardsRequestCard) {
	u.Card = card
	u.require(updateCardsRequestFieldCard)
}

func (u *UpdateCardsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateCardsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateCardsRequest(body)
	return nil
}

func (u *UpdateCardsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateCardsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
