// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

var (
	getCustomerCardsRequestFieldAccountID  = big.NewInt(1 << 0)
	getCustomerCardsRequestFieldCustomerID = big.NewInt(1 << 1)
	getCustomerCardsRequestFieldID         = big.NewInt(1 << 2)
)

type GetCustomerCardsRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Customer ID
	CustomerID int `json:"-" url:"-"`
	// Customer card ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCustomerCardsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsRequest) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getCustomerCardsRequestFieldAccountID)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsRequest) SetCustomerID(customerID int) {
	g.CustomerID = customerID
	g.require(getCustomerCardsRequestFieldCustomerID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsRequest) SetID(id int) {
	g.ID = id
	g.require(getCustomerCardsRequestFieldID)
}

var (
	listCustomerCardsRequestFieldAccountID  = big.NewInt(1 << 0)
	listCustomerCardsRequestFieldCustomerID = big.NewInt(1 << 1)
)

type ListCustomerCardsRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Customer ID
	CustomerID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListCustomerCardsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsRequest) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listCustomerCardsRequestFieldAccountID)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsRequest) SetCustomerID(customerID int) {
	l.CustomerID = customerID
	l.require(listCustomerCardsRequestFieldCustomerID)
}

var (
	redeemCustomerCardsRequestFieldAccountID  = big.NewInt(1 << 0)
	redeemCustomerCardsRequestFieldCustomerID = big.NewInt(1 << 1)
	redeemCustomerCardsRequestFieldID         = big.NewInt(1 << 2)
	redeemCustomerCardsRequestFieldRewardID   = big.NewInt(1 << 3)
)

type RedeemCustomerCardsRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Customer ID
	CustomerID int `json:"-" url:"-"`
	// Customer card ID
	ID int `json:"-" url:"-"`
	// Reward ID to redeem
	RewardID int `json:"reward_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RedeemCustomerCardsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsRequest) SetAccountID(accountID int) {
	r.AccountID = accountID
	r.require(redeemCustomerCardsRequestFieldAccountID)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsRequest) SetCustomerID(customerID int) {
	r.CustomerID = customerID
	r.require(redeemCustomerCardsRequestFieldCustomerID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsRequest) SetID(id int) {
	r.ID = id
	r.require(redeemCustomerCardsRequestFieldID)
}

// SetRewardID sets the RewardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsRequest) SetRewardID(rewardID int) {
	r.RewardID = rewardID
	r.require(redeemCustomerCardsRequestFieldRewardID)
}

func (r *RedeemCustomerCardsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RedeemCustomerCardsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RedeemCustomerCardsRequest(body)
	return nil
}

func (r *RedeemCustomerCardsRequest) MarshalJSON() ([]byte, error) {
	type embed RedeemCustomerCardsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	stampCustomerCardsRequestFieldAccountID         = big.NewInt(1 << 0)
	stampCustomerCardsRequestFieldCustomerID        = big.NewInt(1 << 1)
	stampCustomerCardsRequestFieldID                = big.NewInt(1 << 2)
	stampCustomerCardsRequestFieldSkipNotifications = big.NewInt(1 << 3)
	stampCustomerCardsRequestFieldStamps            = big.NewInt(1 << 4)
)

type StampCustomerCardsRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Customer ID
	CustomerID int `json:"-" url:"-"`
	// Customer card ID
	ID int `json:"-" url:"-"`
	// When true, stamp changes bypass notifications
	SkipNotifications *bool `json:"skip_notifications,omitempty" url:"-"`
	// Number of stamps to add (e.g. 1, 3)
	Stamps int `json:"stamps" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StampCustomerCardsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsRequest) SetAccountID(accountID int) {
	s.AccountID = accountID
	s.require(stampCustomerCardsRequestFieldAccountID)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsRequest) SetCustomerID(customerID int) {
	s.CustomerID = customerID
	s.require(stampCustomerCardsRequestFieldCustomerID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsRequest) SetID(id int) {
	s.ID = id
	s.require(stampCustomerCardsRequestFieldID)
}

// SetSkipNotifications sets the SkipNotifications field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsRequest) SetSkipNotifications(skipNotifications *bool) {
	s.SkipNotifications = skipNotifications
	s.require(stampCustomerCardsRequestFieldSkipNotifications)
}

// SetStamps sets the Stamps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsRequest) SetStamps(stamps int) {
	s.Stamps = stamps
	s.require(stampCustomerCardsRequestFieldStamps)
}

func (s *StampCustomerCardsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler StampCustomerCardsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = StampCustomerCardsRequest(body)
	return nil
}

func (s *StampCustomerCardsRequest) MarshalJSON() ([]byte, error) {
	type embed StampCustomerCardsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getCustomerCardsResponseFieldAccountID          = big.NewInt(1 << 0)
	getCustomerCardsResponseFieldAppleWalletURL     = big.NewInt(1 << 1)
	getCustomerCardsResponseFieldAvailableRewards   = big.NewInt(1 << 2)
	getCustomerCardsResponseFieldCardID             = big.NewInt(1 << 3)
	getCustomerCardsResponseFieldCardName           = big.NewInt(1 << 4)
	getCustomerCardsResponseFieldCreatedAt          = big.NewInt(1 << 5)
	getCustomerCardsResponseFieldCustomerID         = big.NewInt(1 << 6)
	getCustomerCardsResponseFieldGoogleWalletURL    = big.NewInt(1 << 7)
	getCustomerCardsResponseFieldID                 = big.NewInt(1 << 8)
	getCustomerCardsResponseFieldIssuedAt           = big.NewInt(1 << 9)
	getCustomerCardsResponseFieldPassInstalled      = big.NewInt(1 << 10)
	getCustomerCardsResponseFieldProgressPercentage = big.NewInt(1 << 11)
	getCustomerCardsResponseFieldStampsCount        = big.NewInt(1 << 12)
	getCustomerCardsResponseFieldStampsRemaining    = big.NewInt(1 << 13)
	getCustomerCardsResponseFieldStatus             = big.NewInt(1 << 14)
	getCustomerCardsResponseFieldUpdatedAt          = big.NewInt(1 << 15)
	getCustomerCardsResponseFieldUUID               = big.NewInt(1 << 16)
)

type GetCustomerCardsResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Link to add or view the pass in Apple Wallet
	AppleWalletURL string `json:"apple_wallet_url" url:"apple_wallet_url"`
	// Rewards this customer can redeem right now
	AvailableRewards []string `json:"available_rewards" url:"available_rewards"`
	// Loyalty card template ID
	CardID int `json:"card_id" url:"card_id"`
	// Name of the loyalty card
	CardName string `json:"card_name" url:"card_name"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Owning customer ID
	CustomerID int `json:"customer_id" url:"customer_id"`
	// Link to add or view the pass in Google Wallet
	GoogleWalletURL string `json:"google_wallet_url" url:"google_wallet_url"`
	// Customer card ID
	ID int `json:"id" url:"id"`
	// ISO 8601 timestamp the card was issued
	IssuedAt string `json:"issued_at" url:"issued_at"`
	// Whether the wallet pass has been installed
	PassInstalled bool `json:"pass_installed" url:"pass_installed"`
	// Completion towards the next reward, 0 to 100
	ProgressPercentage float64 `json:"progress_percentage" url:"progress_percentage"`
	// Stamps collected so far
	StampsCount int `json:"stamps_count" url:"stamps_count"`
	// Stamps still needed to complete the card
	StampsRemaining int `json:"stamps_remaining" url:"stamps_remaining"`
	// Current state of the customer card
	Status string `json:"status" url:"status"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`
	// Public identifier used in wallet pass URLs
	UUID string `json:"uuid" url:"uuid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetCustomerCardsResponse) GetAccountID() int {
	if g == nil {
		return 0
	}
	return g.AccountID
}

func (g *GetCustomerCardsResponse) GetAppleWalletURL() string {
	if g == nil {
		return ""
	}
	return g.AppleWalletURL
}

func (g *GetCustomerCardsResponse) GetAvailableRewards() []string {
	if g == nil {
		return nil
	}
	return g.AvailableRewards
}

func (g *GetCustomerCardsResponse) GetCardID() int {
	if g == nil {
		return 0
	}
	return g.CardID
}

func (g *GetCustomerCardsResponse) GetCardName() string {
	if g == nil {
		return ""
	}
	return g.CardName
}

func (g *GetCustomerCardsResponse) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetCustomerCardsResponse) GetCustomerID() int {
	if g == nil {
		return 0
	}
	return g.CustomerID
}

func (g *GetCustomerCardsResponse) GetGoogleWalletURL() string {
	if g == nil {
		return ""
	}
	return g.GoogleWalletURL
}

func (g *GetCustomerCardsResponse) GetID() int {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetCustomerCardsResponse) GetIssuedAt() string {
	if g == nil {
		return ""
	}
	return g.IssuedAt
}

func (g *GetCustomerCardsResponse) GetPassInstalled() bool {
	if g == nil {
		return false
	}
	return g.PassInstalled
}

func (g *GetCustomerCardsResponse) GetProgressPercentage() float64 {
	if g == nil {
		return 0
	}
	return g.ProgressPercentage
}

func (g *GetCustomerCardsResponse) GetStampsCount() int {
	if g == nil {
		return 0
	}
	return g.StampsCount
}

func (g *GetCustomerCardsResponse) GetStampsRemaining() int {
	if g == nil {
		return 0
	}
	return g.StampsRemaining
}

func (g *GetCustomerCardsResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetCustomerCardsResponse) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetCustomerCardsResponse) GetUUID() string {
	if g == nil {
		return ""
	}
	return g.UUID
}

func (g *GetCustomerCardsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetCustomerCardsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getCustomerCardsResponseFieldAccountID)
}

// SetAppleWalletURL sets the AppleWalletURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetAppleWalletURL(appleWalletURL string) {
	g.AppleWalletURL = appleWalletURL
	g.require(getCustomerCardsResponseFieldAppleWalletURL)
}

// SetAvailableRewards sets the AvailableRewards field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetAvailableRewards(availableRewards []string) {
	g.AvailableRewards = availableRewards
	g.require(getCustomerCardsResponseFieldAvailableRewards)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetCardID(cardID int) {
	g.CardID = cardID
	g.require(getCustomerCardsResponseFieldCardID)
}

// SetCardName sets the CardName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetCardName(cardName string) {
	g.CardName = cardName
	g.require(getCustomerCardsResponseFieldCardName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getCustomerCardsResponseFieldCreatedAt)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetCustomerID(customerID int) {
	g.CustomerID = customerID
	g.require(getCustomerCardsResponseFieldCustomerID)
}

// SetGoogleWalletURL sets the GoogleWalletURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetGoogleWalletURL(googleWalletURL string) {
	g.GoogleWalletURL = googleWalletURL
	g.require(getCustomerCardsResponseFieldGoogleWalletURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetID(id int) {
	g.ID = id
	g.require(getCustomerCardsResponseFieldID)
}

// SetIssuedAt sets the IssuedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetIssuedAt(issuedAt string) {
	g.IssuedAt = issuedAt
	g.require(getCustomerCardsResponseFieldIssuedAt)
}

// SetPassInstalled sets the PassInstalled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetPassInstalled(passInstalled bool) {
	g.PassInstalled = passInstalled
	g.require(getCustomerCardsResponseFieldPassInstalled)
}

// SetProgressPercentage sets the ProgressPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetProgressPercentage(progressPercentage float64) {
	g.ProgressPercentage = progressPercentage
	g.require(getCustomerCardsResponseFieldProgressPercentage)
}

// SetStampsCount sets the StampsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetStampsCount(stampsCount int) {
	g.StampsCount = stampsCount
	g.require(getCustomerCardsResponseFieldStampsCount)
}

// SetStampsRemaining sets the StampsRemaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetStampsRemaining(stampsRemaining int) {
	g.StampsRemaining = stampsRemaining
	g.require(getCustomerCardsResponseFieldStampsRemaining)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetStatus(status string) {
	g.Status = status
	g.require(getCustomerCardsResponseFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getCustomerCardsResponseFieldUpdatedAt)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomerCardsResponse) SetUUID(uuid string) {
	g.UUID = uuid
	g.require(getCustomerCardsResponseFieldUUID)
}

func (g *GetCustomerCardsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCustomerCardsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCustomerCardsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCustomerCardsResponse) MarshalJSON() ([]byte, error) {
	type embed GetCustomerCardsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetCustomerCardsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listCustomerCardsResponseItemFieldAppleWalletURL     = big.NewInt(1 << 0)
	listCustomerCardsResponseItemFieldCardID             = big.NewInt(1 << 1)
	listCustomerCardsResponseItemFieldCardName           = big.NewInt(1 << 2)
	listCustomerCardsResponseItemFieldCreatedAt          = big.NewInt(1 << 3)
	listCustomerCardsResponseItemFieldGoogleWalletURL    = big.NewInt(1 << 4)
	listCustomerCardsResponseItemFieldID                 = big.NewInt(1 << 5)
	listCustomerCardsResponseItemFieldIssuedAt           = big.NewInt(1 << 6)
	listCustomerCardsResponseItemFieldPassInstalled      = big.NewInt(1 << 7)
	listCustomerCardsResponseItemFieldProgressPercentage = big.NewInt(1 << 8)
	listCustomerCardsResponseItemFieldStampsCount        = big.NewInt(1 << 9)
	listCustomerCardsResponseItemFieldStampsRemaining    = big.NewInt(1 << 10)
	listCustomerCardsResponseItemFieldStatus             = big.NewInt(1 << 11)
	listCustomerCardsResponseItemFieldUpdatedAt          = big.NewInt(1 << 12)
	listCustomerCardsResponseItemFieldUUID               = big.NewInt(1 << 13)
)

type ListCustomerCardsResponseItem struct {
	// Link to add or view the pass in Apple Wallet
	AppleWalletURL string `json:"apple_wallet_url" url:"apple_wallet_url"`
	// Loyalty card template ID
	CardID int `json:"card_id" url:"card_id"`
	// Name of the loyalty card
	CardName string `json:"card_name" url:"card_name"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Link to add or view the pass in Google Wallet
	GoogleWalletURL string `json:"google_wallet_url" url:"google_wallet_url"`
	// Customer card ID
	ID int `json:"id" url:"id"`
	// ISO 8601 timestamp the card was issued
	IssuedAt string `json:"issued_at" url:"issued_at"`
	// Whether the wallet pass has been installed
	PassInstalled bool `json:"pass_installed" url:"pass_installed"`
	// Completion towards the next reward, 0 to 100
	ProgressPercentage float64 `json:"progress_percentage" url:"progress_percentage"`
	// Stamps collected so far
	StampsCount int `json:"stamps_count" url:"stamps_count"`
	// Stamps still needed to complete the card
	StampsRemaining int `json:"stamps_remaining" url:"stamps_remaining"`
	// Current state of the customer card
	Status string `json:"status" url:"status"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`
	// Public identifier used in wallet pass URLs
	UUID string `json:"uuid" url:"uuid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListCustomerCardsResponseItem) GetAppleWalletURL() string {
	if l == nil {
		return ""
	}
	return l.AppleWalletURL
}

func (l *ListCustomerCardsResponseItem) GetCardID() int {
	if l == nil {
		return 0
	}
	return l.CardID
}

func (l *ListCustomerCardsResponseItem) GetCardName() string {
	if l == nil {
		return ""
	}
	return l.CardName
}

func (l *ListCustomerCardsResponseItem) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListCustomerCardsResponseItem) GetGoogleWalletURL() string {
	if l == nil {
		return ""
	}
	return l.GoogleWalletURL
}

func (l *ListCustomerCardsResponseItem) GetID() int {
	if l == nil {
		return 0
	}
	return l.ID
}

func (l *ListCustomerCardsResponseItem) GetIssuedAt() string {
	if l == nil {
		return ""
	}
	return l.IssuedAt
}

func (l *ListCustomerCardsResponseItem) GetPassInstalled() bool {
	if l == nil {
		return false
	}
	return l.PassInstalled
}

func (l *ListCustomerCardsResponseItem) GetProgressPercentage() float64 {
	if l == nil {
		return 0
	}
	return l.ProgressPercentage
}

func (l *ListCustomerCardsResponseItem) GetStampsCount() int {
	if l == nil {
		return 0
	}
	return l.StampsCount
}

func (l *ListCustomerCardsResponseItem) GetStampsRemaining() int {
	if l == nil {
		return 0
	}
	return l.StampsRemaining
}

func (l *ListCustomerCardsResponseItem) GetStatus() string {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListCustomerCardsResponseItem) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListCustomerCardsResponseItem) GetUUID() string {
	if l == nil {
		return ""
	}
	return l.UUID
}

func (l *ListCustomerCardsResponseItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListCustomerCardsResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAppleWalletURL sets the AppleWalletURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetAppleWalletURL(appleWalletURL string) {
	l.AppleWalletURL = appleWalletURL
	l.require(listCustomerCardsResponseItemFieldAppleWalletURL)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetCardID(cardID int) {
	l.CardID = cardID
	l.require(listCustomerCardsResponseItemFieldCardID)
}

// SetCardName sets the CardName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetCardName(cardName string) {
	l.CardName = cardName
	l.require(listCustomerCardsResponseItemFieldCardName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetCreatedAt(createdAt string) {
	l.CreatedAt = createdAt
	l.require(listCustomerCardsResponseItemFieldCreatedAt)
}

// SetGoogleWalletURL sets the GoogleWalletURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetGoogleWalletURL(googleWalletURL string) {
	l.GoogleWalletURL = googleWalletURL
	l.require(listCustomerCardsResponseItemFieldGoogleWalletURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetID(id int) {
	l.ID = id
	l.require(listCustomerCardsResponseItemFieldID)
}

// SetIssuedAt sets the IssuedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetIssuedAt(issuedAt string) {
	l.IssuedAt = issuedAt
	l.require(listCustomerCardsResponseItemFieldIssuedAt)
}

// SetPassInstalled sets the PassInstalled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetPassInstalled(passInstalled bool) {
	l.PassInstalled = passInstalled
	l.require(listCustomerCardsResponseItemFieldPassInstalled)
}

// SetProgressPercentage sets the ProgressPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetProgressPercentage(progressPercentage float64) {
	l.ProgressPercentage = progressPercentage
	l.require(listCustomerCardsResponseItemFieldProgressPercentage)
}

// SetStampsCount sets the StampsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetStampsCount(stampsCount int) {
	l.StampsCount = stampsCount
	l.require(listCustomerCardsResponseItemFieldStampsCount)
}

// SetStampsRemaining sets the StampsRemaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetStampsRemaining(stampsRemaining int) {
	l.StampsRemaining = stampsRemaining
	l.require(listCustomerCardsResponseItemFieldStampsRemaining)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetStatus(status string) {
	l.Status = status
	l.require(listCustomerCardsResponseItemFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetUpdatedAt(updatedAt string) {
	l.UpdatedAt = updatedAt
	l.require(listCustomerCardsResponseItemFieldUpdatedAt)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCustomerCardsResponseItem) SetUUID(uuid string) {
	l.UUID = uuid
	l.require(listCustomerCardsResponseItemFieldUUID)
}

func (l *ListCustomerCardsResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListCustomerCardsResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListCustomerCardsResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListCustomerCardsResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListCustomerCardsResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListCustomerCardsResponseItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	redeemCustomerCardsResponseFieldRedemption = big.NewInt(1 << 0)
	redeemCustomerCardsResponseFieldSuccess    = big.NewInt(1 << 1)
)

type RedeemCustomerCardsResponse struct {
	Redemption *RedeemCustomerCardsResponseRedemption `json:"redemption" url:"redemption"`
	// True when the reward was redeemed
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RedeemCustomerCardsResponse) GetRedemption() *RedeemCustomerCardsResponseRedemption {
	if r == nil {
		return nil
	}
	return r.Redemption
}

func (r *RedeemCustomerCardsResponse) GetSuccess() bool {
	if r == nil {
		return false
	}
	return r.Success
}

func (r *RedeemCustomerCardsResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RedeemCustomerCardsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRedemption sets the Redemption field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponse) SetRedemption(redemption *RedeemCustomerCardsResponseRedemption) {
	r.Redemption = redemption
	r.require(redeemCustomerCardsResponseFieldRedemption)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponse) SetSuccess(success bool) {
	r.Success = success
	r.require(redeemCustomerCardsResponseFieldSuccess)
}

func (r *RedeemCustomerCardsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RedeemCustomerCardsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RedeemCustomerCardsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RedeemCustomerCardsResponse) MarshalJSON() ([]byte, error) {
	type embed RedeemCustomerCardsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RedeemCustomerCardsResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	redeemCustomerCardsResponseRedemptionFieldID              = big.NewInt(1 << 0)
	redeemCustomerCardsResponseRedemptionFieldRedeemedAt      = big.NewInt(1 << 1)
	redeemCustomerCardsResponseRedemptionFieldRewardID        = big.NewInt(1 << 2)
	redeemCustomerCardsResponseRedemptionFieldRewardName      = big.NewInt(1 << 3)
	redeemCustomerCardsResponseRedemptionFieldStampsRemaining = big.NewInt(1 << 4)
	redeemCustomerCardsResponseRedemptionFieldStampsSpent     = big.NewInt(1 << 5)
)

type RedeemCustomerCardsResponseRedemption struct {
	// Redemption ID
	ID int `json:"id" url:"id"`
	// ISO 8601 timestamp of the redemption
	RedeemedAt string `json:"redeemed_at" url:"redeemed_at"`
	// Reward that was redeemed
	RewardID int `json:"reward_id" url:"reward_id"`
	// Display name of the reward
	RewardName string `json:"reward_name" url:"reward_name"`
	// Stamps left on the card afterwards
	StampsRemaining int `json:"stamps_remaining" url:"stamps_remaining"`
	// Stamps deducted from the card
	StampsSpent int `json:"stamps_spent" url:"stamps_spent"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RedeemCustomerCardsResponseRedemption) GetID() int {
	if r == nil {
		return 0
	}
	return r.ID
}

func (r *RedeemCustomerCardsResponseRedemption) GetRedeemedAt() string {
	if r == nil {
		return ""
	}
	return r.RedeemedAt
}

func (r *RedeemCustomerCardsResponseRedemption) GetRewardID() int {
	if r == nil {
		return 0
	}
	return r.RewardID
}

func (r *RedeemCustomerCardsResponseRedemption) GetRewardName() string {
	if r == nil {
		return ""
	}
	return r.RewardName
}

func (r *RedeemCustomerCardsResponseRedemption) GetStampsRemaining() int {
	if r == nil {
		return 0
	}
	return r.StampsRemaining
}

func (r *RedeemCustomerCardsResponseRedemption) GetStampsSpent() int {
	if r == nil {
		return 0
	}
	return r.StampsSpent
}

func (r *RedeemCustomerCardsResponseRedemption) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RedeemCustomerCardsResponseRedemption) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponseRedemption) SetID(id int) {
	r.ID = id
	r.require(redeemCustomerCardsResponseRedemptionFieldID)
}

// SetRedeemedAt sets the RedeemedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponseRedemption) SetRedeemedAt(redeemedAt string) {
	r.RedeemedAt = redeemedAt
	r.require(redeemCustomerCardsResponseRedemptionFieldRedeemedAt)
}

// SetRewardID sets the RewardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponseRedemption) SetRewardID(rewardID int) {
	r.RewardID = rewardID
	r.require(redeemCustomerCardsResponseRedemptionFieldRewardID)
}

// SetRewardName sets the RewardName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponseRedemption) SetRewardName(rewardName string) {
	r.RewardName = rewardName
	r.require(redeemCustomerCardsResponseRedemptionFieldRewardName)
}

// SetStampsRemaining sets the StampsRemaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponseRedemption) SetStampsRemaining(stampsRemaining int) {
	r.StampsRemaining = stampsRemaining
	r.require(redeemCustomerCardsResponseRedemptionFieldStampsRemaining)
}

// SetStampsSpent sets the StampsSpent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedeemCustomerCardsResponseRedemption) SetStampsSpent(stampsSpent int) {
	r.StampsSpent = stampsSpent
	r.require(redeemCustomerCardsResponseRedemptionFieldStampsSpent)
}

func (r *RedeemCustomerCardsResponseRedemption) UnmarshalJSON(data []byte) error {
	type unmarshaler RedeemCustomerCardsResponseRedemption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RedeemCustomerCardsResponseRedemption(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RedeemCustomerCardsResponseRedemption) MarshalJSON() ([]byte, error) {
	type embed RedeemCustomerCardsResponseRedemption
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RedeemCustomerCardsResponseRedemption) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	stampCustomerCardsResponseFieldAccountID          = big.NewInt(1 << 0)
	stampCustomerCardsResponseFieldAppleWalletURL     = big.NewInt(1 << 1)
	stampCustomerCardsResponseFieldAvailableRewards   = big.NewInt(1 << 2)
	stampCustomerCardsResponseFieldCardID             = big.NewInt(1 << 3)
	stampCustomerCardsResponseFieldCardName           = big.NewInt(1 << 4)
	stampCustomerCardsResponseFieldCreatedAt          = big.NewInt(1 << 5)
	stampCustomerCardsResponseFieldCustomerID         = big.NewInt(1 << 6)
	stampCustomerCardsResponseFieldGoogleWalletURL    = big.NewInt(1 << 7)
	stampCustomerCardsResponseFieldID                 = big.NewInt(1 << 8)
	stampCustomerCardsResponseFieldIssuedAt           = big.NewInt(1 << 9)
	stampCustomerCardsResponseFieldPassInstalled      = big.NewInt(1 << 10)
	stampCustomerCardsResponseFieldProgressPercentage = big.NewInt(1 << 11)
	stampCustomerCardsResponseFieldStampsCount        = big.NewInt(1 << 12)
	stampCustomerCardsResponseFieldStampsRemaining    = big.NewInt(1 << 13)
	stampCustomerCardsResponseFieldStatus             = big.NewInt(1 << 14)
	stampCustomerCardsResponseFieldUpdatedAt          = big.NewInt(1 << 15)
	stampCustomerCardsResponseFieldUUID               = big.NewInt(1 << 16)
)

type StampCustomerCardsResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Link to add or view the pass in Apple Wallet
	AppleWalletURL string `json:"apple_wallet_url" url:"apple_wallet_url"`
	// Rewards this customer can redeem right now
	AvailableRewards []string `json:"available_rewards" url:"available_rewards"`
	// Loyalty card template ID
	CardID int `json:"card_id" url:"card_id"`
	// Name of the loyalty card
	CardName string `json:"card_name" url:"card_name"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Owning customer ID
	CustomerID int `json:"customer_id" url:"customer_id"`
	// Link to add or view the pass in Google Wallet
	GoogleWalletURL string `json:"google_wallet_url" url:"google_wallet_url"`
	// Customer card ID
	ID int `json:"id" url:"id"`
	// ISO 8601 timestamp the card was issued
	IssuedAt string `json:"issued_at" url:"issued_at"`
	// Whether the wallet pass has been installed
	PassInstalled bool `json:"pass_installed" url:"pass_installed"`
	// Completion towards the next reward, 0 to 100
	ProgressPercentage float64 `json:"progress_percentage" url:"progress_percentage"`
	// Stamps collected so far
	StampsCount int `json:"stamps_count" url:"stamps_count"`
	// Stamps still needed to complete the card
	StampsRemaining int `json:"stamps_remaining" url:"stamps_remaining"`
	// Current state of the customer card
	Status string `json:"status" url:"status"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`
	// Public identifier used in wallet pass URLs
	UUID string `json:"uuid" url:"uuid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *StampCustomerCardsResponse) GetAccountID() int {
	if s == nil {
		return 0
	}
	return s.AccountID
}

func (s *StampCustomerCardsResponse) GetAppleWalletURL() string {
	if s == nil {
		return ""
	}
	return s.AppleWalletURL
}

func (s *StampCustomerCardsResponse) GetAvailableRewards() []string {
	if s == nil {
		return nil
	}
	return s.AvailableRewards
}

func (s *StampCustomerCardsResponse) GetCardID() int {
	if s == nil {
		return 0
	}
	return s.CardID
}

func (s *StampCustomerCardsResponse) GetCardName() string {
	if s == nil {
		return ""
	}
	return s.CardName
}

func (s *StampCustomerCardsResponse) GetCreatedAt() string {
	if s == nil {
		return ""
	}
	return s.CreatedAt
}

func (s *StampCustomerCardsResponse) GetCustomerID() int {
	if s == nil {
		return 0
	}
	return s.CustomerID
}

func (s *StampCustomerCardsResponse) GetGoogleWalletURL() string {
	if s == nil {
		return ""
	}
	return s.GoogleWalletURL
}

func (s *StampCustomerCardsResponse) GetID() int {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *StampCustomerCardsResponse) GetIssuedAt() string {
	if s == nil {
		return ""
	}
	return s.IssuedAt
}

func (s *StampCustomerCardsResponse) GetPassInstalled() bool {
	if s == nil {
		return false
	}
	return s.PassInstalled
}

func (s *StampCustomerCardsResponse) GetProgressPercentage() float64 {
	if s == nil {
		return 0
	}
	return s.ProgressPercentage
}

func (s *StampCustomerCardsResponse) GetStampsCount() int {
	if s == nil {
		return 0
	}
	return s.StampsCount
}

func (s *StampCustomerCardsResponse) GetStampsRemaining() int {
	if s == nil {
		return 0
	}
	return s.StampsRemaining
}

func (s *StampCustomerCardsResponse) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *StampCustomerCardsResponse) GetUpdatedAt() string {
	if s == nil {
		return ""
	}
	return s.UpdatedAt
}

func (s *StampCustomerCardsResponse) GetUUID() string {
	if s == nil {
		return ""
	}
	return s.UUID
}

func (s *StampCustomerCardsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *StampCustomerCardsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetAccountID(accountID int) {
	s.AccountID = accountID
	s.require(stampCustomerCardsResponseFieldAccountID)
}

// SetAppleWalletURL sets the AppleWalletURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetAppleWalletURL(appleWalletURL string) {
	s.AppleWalletURL = appleWalletURL
	s.require(stampCustomerCardsResponseFieldAppleWalletURL)
}

// SetAvailableRewards sets the AvailableRewards field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetAvailableRewards(availableRewards []string) {
	s.AvailableRewards = availableRewards
	s.require(stampCustomerCardsResponseFieldAvailableRewards)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetCardID(cardID int) {
	s.CardID = cardID
	s.require(stampCustomerCardsResponseFieldCardID)
}

// SetCardName sets the CardName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetCardName(cardName string) {
	s.CardName = cardName
	s.require(stampCustomerCardsResponseFieldCardName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetCreatedAt(createdAt string) {
	s.CreatedAt = createdAt
	s.require(stampCustomerCardsResponseFieldCreatedAt)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetCustomerID(customerID int) {
	s.CustomerID = customerID
	s.require(stampCustomerCardsResponseFieldCustomerID)
}

// SetGoogleWalletURL sets the GoogleWalletURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetGoogleWalletURL(googleWalletURL string) {
	s.GoogleWalletURL = googleWalletURL
	s.require(stampCustomerCardsResponseFieldGoogleWalletURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetID(id int) {
	s.ID = id
	s.require(stampCustomerCardsResponseFieldID)
}

// SetIssuedAt sets the IssuedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetIssuedAt(issuedAt string) {
	s.IssuedAt = issuedAt
	s.require(stampCustomerCardsResponseFieldIssuedAt)
}

// SetPassInstalled sets the PassInstalled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetPassInstalled(passInstalled bool) {
	s.PassInstalled = passInstalled
	s.require(stampCustomerCardsResponseFieldPassInstalled)
}

// SetProgressPercentage sets the ProgressPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetProgressPercentage(progressPercentage float64) {
	s.ProgressPercentage = progressPercentage
	s.require(stampCustomerCardsResponseFieldProgressPercentage)
}

// SetStampsCount sets the StampsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetStampsCount(stampsCount int) {
	s.StampsCount = stampsCount
	s.require(stampCustomerCardsResponseFieldStampsCount)
}

// SetStampsRemaining sets the StampsRemaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetStampsRemaining(stampsRemaining int) {
	s.StampsRemaining = stampsRemaining
	s.require(stampCustomerCardsResponseFieldStampsRemaining)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetStatus(status string) {
	s.Status = status
	s.require(stampCustomerCardsResponseFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetUpdatedAt(updatedAt string) {
	s.UpdatedAt = updatedAt
	s.require(stampCustomerCardsResponseFieldUpdatedAt)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StampCustomerCardsResponse) SetUUID(uuid string) {
	s.UUID = uuid
	s.require(stampCustomerCardsResponseFieldUUID)
}

func (s *StampCustomerCardsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler StampCustomerCardsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StampCustomerCardsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *StampCustomerCardsResponse) MarshalJSON() ([]byte, error) {
	type embed StampCustomerCardsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *StampCustomerCardsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
