// Code generated by Fern. DO NOT EDIT.

package leal

import (
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	410: func(apiError *core.APIError) error {
		return &GoneError{
			APIError: apiError,
		}
	},
	429: func(apiError *core.APIError) error {
		return &TooManyRequestsError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
	422: func(apiError *core.APIError) error {
		return &UnprocessableEntityError{
			APIError: apiError,
		}
	},
}
