// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

var (
	createLocationsRequestFieldAccountID = big.NewInt(1 << 0)
	createLocationsRequestFieldLocation  = big.NewInt(1 << 1)
)

type CreateLocationsRequest struct {
	// Parent store ID
	AccountID int                             `json:"-" url:"-"`
	Location  *CreateLocationsRequestLocation `json:"location" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateLocationsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsRequest) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createLocationsRequestFieldAccountID)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsRequest) SetLocation(location *CreateLocationsRequestLocation) {
	c.Location = location
	c.require(createLocationsRequestFieldLocation)
}

func (c *CreateLocationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateLocationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateLocationsRequest(body)
	return nil
}

func (c *CreateLocationsRequest) MarshalJSON() ([]byte, error) {
	type embed CreateLocationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteLocationsRequestFieldAccountID = big.NewInt(1 << 0)
	deleteLocationsRequestFieldID        = big.NewInt(1 << 1)
)

type DeleteLocationsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`
	// Location ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteLocationsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteLocationsRequest) SetAccountID(accountID int) {
	d.AccountID = accountID
	d.require(deleteLocationsRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteLocationsRequest) SetID(id int) {
	d.ID = id
	d.require(deleteLocationsRequestFieldID)
}

var (
	getLocationsRequestFieldAccountID = big.NewInt(1 << 0)
	getLocationsRequestFieldID        = big.NewInt(1 << 1)
)

type GetLocationsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`
	// Location ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetLocationsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsRequest) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getLocationsRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsRequest) SetID(id int) {
	g.ID = id
	g.require(getLocationsRequestFieldID)
}

var (
	listLocationsRequestFieldAccountID = big.NewInt(1 << 0)
)

type ListLocationsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListLocationsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsRequest) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listLocationsRequestFieldAccountID)
}

var (
	createLocationsRequestLocationFieldAddress = big.NewInt(1 << 0)
	createLocationsRequestLocationFieldName    = big.NewInt(1 << 1)
)

type CreateLocationsRequestLocation struct {
	// Full street address – automatically geocoded to lat/lng
	Address string `json:"address" url:"address"`
	// Location name (e.g. 'High Street Branch')
	Name string `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateLocationsRequestLocation) GetAddress() string {
	if c == nil {
		return ""
	}
	return c.Address
}

func (c *CreateLocationsRequestLocation) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateLocationsRequestLocation) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateLocationsRequestLocation) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsRequestLocation) SetAddress(address string) {
	c.Address = address
	c.require(createLocationsRequestLocationFieldAddress)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsRequestLocation) SetName(name string) {
	c.Name = name
	c.require(createLocationsRequestLocationFieldName)
}

func (c *CreateLocationsRequestLocation) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateLocationsRequestLocation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateLocationsRequestLocation(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateLocationsRequestLocation) MarshalJSON() ([]byte, error) {
	type embed CreateLocationsRequestLocation
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateLocationsRequestLocation) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createLocationsResponseFieldAccountID = big.NewInt(1 << 0)
	createLocationsResponseFieldAddress   = big.NewInt(1 << 1)
	createLocationsResponseFieldCreatedAt = big.NewInt(1 << 2)
	createLocationsResponseFieldID        = big.NewInt(1 << 3)
	createLocationsResponseFieldLatitude  = big.NewInt(1 << 4)
	createLocationsResponseFieldLongitude = big.NewInt(1 << 5)
	createLocationsResponseFieldName      = big.NewInt(1 << 6)
	createLocationsResponseFieldUpdatedAt = big.NewInt(1 << 7)
)

type CreateLocationsResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Full street address
	Address string `json:"address" url:"address"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Unique location ID
	ID int `json:"id" url:"id"`
	// Geocoded latitude (auto-derived from address)
	Latitude float64 `json:"latitude" url:"latitude"`
	// Geocoded longitude (auto-derived from address)
	Longitude float64 `json:"longitude" url:"longitude"`
	// Location name (e.g. 'Downtown Branch')
	Name string `json:"name" url:"name"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateLocationsResponse) GetAccountID() int {
	if c == nil {
		return 0
	}
	return c.AccountID
}

func (c *CreateLocationsResponse) GetAddress() string {
	if c == nil {
		return ""
	}
	return c.Address
}

func (c *CreateLocationsResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateLocationsResponse) GetID() int {
	if c == nil {
		return 0
	}
	return c.ID
}

func (c *CreateLocationsResponse) GetLatitude() float64 {
	if c == nil {
		return 0
	}
	return c.Latitude
}

func (c *CreateLocationsResponse) GetLongitude() float64 {
	if c == nil {
		return 0
	}
	return c.Longitude
}

func (c *CreateLocationsResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateLocationsResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateLocationsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateLocationsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createLocationsResponseFieldAccountID)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetAddress(address string) {
	c.Address = address
	c.require(createLocationsResponseFieldAddress)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createLocationsResponseFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetID(id int) {
	c.ID = id
	c.require(createLocationsResponseFieldID)
}

// SetLatitude sets the Latitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetLatitude(latitude float64) {
	c.Latitude = latitude
	c.require(createLocationsResponseFieldLatitude)
}

// SetLongitude sets the Longitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetLongitude(longitude float64) {
	c.Longitude = longitude
	c.require(createLocationsResponseFieldLongitude)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetName(name string) {
	c.Name = name
	c.require(createLocationsResponseFieldName)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLocationsResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createLocationsResponseFieldUpdatedAt)
}

func (c *CreateLocationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateLocationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateLocationsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateLocationsResponse) MarshalJSON() ([]byte, error) {
	type embed CreateLocationsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateLocationsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getLocationsResponseFieldAccountID = big.NewInt(1 << 0)
	getLocationsResponseFieldAddress   = big.NewInt(1 << 1)
	getLocationsResponseFieldCreatedAt = big.NewInt(1 << 2)
	getLocationsResponseFieldID        = big.NewInt(1 << 3)
	getLocationsResponseFieldLatitude  = big.NewInt(1 << 4)
	getLocationsResponseFieldLongitude = big.NewInt(1 << 5)
	getLocationsResponseFieldName      = big.NewInt(1 << 6)
	getLocationsResponseFieldUpdatedAt = big.NewInt(1 << 7)
)

type GetLocationsResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Full street address
	Address string `json:"address" url:"address"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Unique location ID
	ID int `json:"id" url:"id"`
	// Geocoded latitude (auto-derived from address)
	Latitude float64 `json:"latitude" url:"latitude"`
	// Geocoded longitude (auto-derived from address)
	Longitude float64 `json:"longitude" url:"longitude"`
	// Location name (e.g. 'Downtown Branch')
	Name string `json:"name" url:"name"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetLocationsResponse) GetAccountID() int {
	if g == nil {
		return 0
	}
	return g.AccountID
}

func (g *GetLocationsResponse) GetAddress() string {
	if g == nil {
		return ""
	}
	return g.Address
}

func (g *GetLocationsResponse) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetLocationsResponse) GetID() int {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetLocationsResponse) GetLatitude() float64 {
	if g == nil {
		return 0
	}
	return g.Latitude
}

func (g *GetLocationsResponse) GetLongitude() float64 {
	if g == nil {
		return 0
	}
	return g.Longitude
}

func (g *GetLocationsResponse) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetLocationsResponse) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetLocationsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetLocationsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getLocationsResponseFieldAccountID)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetAddress(address string) {
	g.Address = address
	g.require(getLocationsResponseFieldAddress)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getLocationsResponseFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetID(id int) {
	g.ID = id
	g.require(getLocationsResponseFieldID)
}

// SetLatitude sets the Latitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetLatitude(latitude float64) {
	g.Latitude = latitude
	g.require(getLocationsResponseFieldLatitude)
}

// SetLongitude sets the Longitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetLongitude(longitude float64) {
	g.Longitude = longitude
	g.require(getLocationsResponseFieldLongitude)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetName(name string) {
	g.Name = name
	g.require(getLocationsResponseFieldName)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLocationsResponse) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getLocationsResponseFieldUpdatedAt)
}

func (g *GetLocationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetLocationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetLocationsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetLocationsResponse) MarshalJSON() ([]byte, error) {
	type embed GetLocationsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetLocationsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listLocationsResponseItemFieldAccountID = big.NewInt(1 << 0)
	listLocationsResponseItemFieldAddress   = big.NewInt(1 << 1)
	listLocationsResponseItemFieldCreatedAt = big.NewInt(1 << 2)
	listLocationsResponseItemFieldID        = big.NewInt(1 << 3)
	listLocationsResponseItemFieldLatitude  = big.NewInt(1 << 4)
	listLocationsResponseItemFieldLongitude = big.NewInt(1 << 5)
	listLocationsResponseItemFieldName      = big.NewInt(1 << 6)
	listLocationsResponseItemFieldUpdatedAt = big.NewInt(1 << 7)
)

type ListLocationsResponseItem struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Full street address
	Address string `json:"address" url:"address"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Unique location ID
	ID int `json:"id" url:"id"`
	// Geocoded latitude (auto-derived from address)
	Latitude float64 `json:"latitude" url:"latitude"`
	// Geocoded longitude (auto-derived from address)
	Longitude float64 `json:"longitude" url:"longitude"`
	// Location name (e.g. 'Downtown Branch')
	Name string `json:"name" url:"name"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListLocationsResponseItem) GetAccountID() int {
	if l == nil {
		return 0
	}
	return l.AccountID
}

func (l *ListLocationsResponseItem) GetAddress() string {
	if l == nil {
		return ""
	}
	return l.Address
}

func (l *ListLocationsResponseItem) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListLocationsResponseItem) GetID() int {
	if l == nil {
		return 0
	}
	return l.ID
}

func (l *ListLocationsResponseItem) GetLatitude() float64 {
	if l == nil {
		return 0
	}
	return l.Latitude
}

func (l *ListLocationsResponseItem) GetLongitude() float64 {
	if l == nil {
		return 0
	}
	return l.Longitude
}

func (l *ListLocationsResponseItem) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListLocationsResponseItem) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListLocationsResponseItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListLocationsResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listLocationsResponseItemFieldAccountID)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetAddress(address string) {
	l.Address = address
	l.require(listLocationsResponseItemFieldAddress)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetCreatedAt(createdAt string) {
	l.CreatedAt = createdAt
	l.require(listLocationsResponseItemFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetID(id int) {
	l.ID = id
	l.require(listLocationsResponseItemFieldID)
}

// SetLatitude sets the Latitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetLatitude(latitude float64) {
	l.Latitude = latitude
	l.require(listLocationsResponseItemFieldLatitude)
}

// SetLongitude sets the Longitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetLongitude(longitude float64) {
	l.Longitude = longitude
	l.require(listLocationsResponseItemFieldLongitude)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetName(name string) {
	l.Name = name
	l.require(listLocationsResponseItemFieldName)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLocationsResponseItem) SetUpdatedAt(updatedAt string) {
	l.UpdatedAt = updatedAt
	l.require(listLocationsResponseItemFieldUpdatedAt)
}

func (l *ListLocationsResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListLocationsResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListLocationsResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListLocationsResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListLocationsResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListLocationsResponseItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	updateLocationsRequestLocationFieldAddress = big.NewInt(1 << 0)
	updateLocationsRequestLocationFieldName    = big.NewInt(1 << 1)
)

type UpdateLocationsRequestLocation struct {
	// Full street address – automatically geocoded to lat/lng
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Location name
	Name *string `json:"name,omitempty" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateLocationsRequestLocation) GetAddress() *string {
	if u == nil {
		return nil
	}
	return u.Address
}

func (u *UpdateLocationsRequestLocation) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateLocationsRequestLocation) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateLocationsRequestLocation) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsRequestLocation) SetAddress(address *string) {
	u.Address = address
	u.require(updateLocationsRequestLocationFieldAddress)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsRequestLocation) SetName(name *string) {
	u.Name = name
	u.require(updateLocationsRequestLocationFieldName)
}

func (u *UpdateLocationsRequestLocation) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateLocationsRequestLocation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateLocationsRequestLocation(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateLocationsRequestLocation) MarshalJSON() ([]byte, error) {
	type embed UpdateLocationsRequestLocation
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateLocationsRequestLocation) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateLocationsResponseFieldAccountID = big.NewInt(1 << 0)
	updateLocationsResponseFieldAddress   = big.NewInt(1 << 1)
	updateLocationsResponseFieldCreatedAt = big.NewInt(1 << 2)
	updateLocationsResponseFieldID        = big.NewInt(1 << 3)
	updateLocationsResponseFieldLatitude  = big.NewInt(1 << 4)
	updateLocationsResponseFieldLongitude = big.NewInt(1 << 5)
	updateLocationsResponseFieldName      = big.NewInt(1 << 6)
	updateLocationsResponseFieldUpdatedAt = big.NewInt(1 << 7)
)

type UpdateLocationsResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Full street address
	Address string `json:"address" url:"address"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// Unique location ID
	ID int `json:"id" url:"id"`
	// Geocoded latitude (auto-derived from address)
	Latitude float64 `json:"latitude" url:"latitude"`
	// Geocoded longitude (auto-derived from address)
	Longitude float64 `json:"longitude" url:"longitude"`
	// Location name (e.g. 'Downtown Branch')
	Name string `json:"name" url:"name"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateLocationsResponse) GetAccountID() int {
	if u == nil {
		return 0
	}
	return u.AccountID
}

func (u *UpdateLocationsResponse) GetAddress() string {
	if u == nil {
		return ""
	}
	return u.Address
}

func (u *UpdateLocationsResponse) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateLocationsResponse) GetID() int {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateLocationsResponse) GetLatitude() float64 {
	if u == nil {
		return 0
	}
	return u.Latitude
}

func (u *UpdateLocationsResponse) GetLongitude() float64 {
	if u == nil {
		return 0
	}
	return u.Longitude
}

func (u *UpdateLocationsResponse) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateLocationsResponse) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateLocationsResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateLocationsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updateLocationsResponseFieldAccountID)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetAddress(address string) {
	u.Address = address
	u.require(updateLocationsResponseFieldAddress)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updateLocationsResponseFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetID(id int) {
	u.ID = id
	u.require(updateLocationsResponseFieldID)
}

// SetLatitude sets the Latitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetLatitude(latitude float64) {
	u.Latitude = latitude
	u.require(updateLocationsResponseFieldLatitude)
}

// SetLongitude sets the Longitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetLongitude(longitude float64) {
	u.Longitude = longitude
	u.require(updateLocationsResponseFieldLongitude)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetName(name string) {
	u.Name = name
	u.require(updateLocationsResponseFieldName)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsResponse) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updateLocationsResponseFieldUpdatedAt)
}

func (u *UpdateLocationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateLocationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateLocationsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateLocationsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateLocationsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateLocationsResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateLocationsRequestFieldAccountID = big.NewInt(1 << 0)
	updateLocationsRequestFieldID        = big.NewInt(1 << 1)
	updateLocationsRequestFieldLocation  = big.NewInt(1 << 2)
)

type UpdateLocationsRequest struct {
	// Parent store ID
	AccountID int `json:"-" url:"-"`
	// Location ID
	ID       int                             `json:"-" url:"-"`
	Location *UpdateLocationsRequestLocation `json:"location" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateLocationsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsRequest) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updateLocationsRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsRequest) SetID(id int) {
	u.ID = id
	u.require(updateLocationsRequestFieldID)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLocationsRequest) SetLocation(location *UpdateLocationsRequestLocation) {
	u.Location = location
	u.require(updateLocationsRequestFieldLocation)
}

func (u *UpdateLocationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateLocationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateLocationsRequest(body)
	return nil
}

func (u *UpdateLocationsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateLocationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
