// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

var (
	createPostersRequestFieldAccountID = big.NewInt(1 << 0)
	createPostersRequestFieldPoster    = big.NewInt(1 << 1)
)

type CreatePostersRequest struct {
	// Store (account) ID
	AccountID int                         `json:"-" url:"-"`
	Poster    *CreatePostersRequestPoster `json:"poster" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePostersRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequest) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createPostersRequestFieldAccountID)
}

// SetPoster sets the Poster field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequest) SetPoster(poster *CreatePostersRequestPoster) {
	c.Poster = poster
	c.require(createPostersRequestFieldPoster)
}

func (c *CreatePostersRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePostersRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePostersRequest(body)
	return nil
}

func (c *CreatePostersRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePostersRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deletePostersRequestFieldAccountID = big.NewInt(1 << 0)
	deletePostersRequestFieldID        = big.NewInt(1 << 1)
)

type DeletePostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Poster ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePostersRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePostersRequest) SetAccountID(accountID int) {
	d.AccountID = accountID
	d.require(deletePostersRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePostersRequest) SetID(id int) {
	d.ID = id
	d.require(deletePostersRequestFieldID)
}

var (
	getPostersRequestFieldAccountID = big.NewInt(1 << 0)
	getPostersRequestFieldID        = big.NewInt(1 << 1)
)

type GetPostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Poster ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPostersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersRequest) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getPostersRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersRequest) SetID(id int) {
	g.ID = id
	g.require(getPostersRequestFieldID)
}

var (
	listPostersRequestFieldAccountID = big.NewInt(1 << 0)
	listPostersRequestFieldCardID    = big.NewInt(1 << 1)
	listPostersRequestFieldActive    = big.NewInt(1 << 2)
)

type ListPostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Filter posters belonging to a specific card
	CardID *int `json:"-" url:"card_id,omitempty"`
	// When present, return only active posters
	Active *string `json:"-" url:"active,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPostersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersRequest) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listPostersRequestFieldAccountID)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersRequest) SetCardID(cardID *int) {
	l.CardID = cardID
	l.require(listPostersRequestFieldCardID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersRequest) SetActive(active *string) {
	l.Active = active
	l.require(listPostersRequestFieldActive)
}

var (
	createPostersRequestPosterFieldActive                = big.NewInt(1 << 0)
	createPostersRequestPosterFieldCardID                = big.NewInt(1 << 1)
	createPostersRequestPosterFieldContactCollectionMode = big.NewInt(1 << 2)
	createPostersRequestPosterFieldMinimumAge            = big.NewInt(1 << 3)
	createPostersRequestPosterFieldPaperSize             = big.NewInt(1 << 4)
	createPostersRequestPosterFieldPrimaryColor          = big.NewInt(1 << 5)
	createPostersRequestPosterFieldRequireBirthday       = big.NewInt(1 << 6)
	createPostersRequestPosterFieldRequireEmail          = big.NewInt(1 << 7)
	createPostersRequestPosterFieldRequirePhone          = big.NewInt(1 << 8)
	createPostersRequestPosterFieldSecondaryColor        = big.NewInt(1 << 9)
	createPostersRequestPosterFieldTextColor             = big.NewInt(1 << 10)
	createPostersRequestPosterFieldTitle                 = big.NewInt(1 << 11)
)

type CreatePostersRequestPoster struct {
	// Whether the poster is active (defaults to true)
	Active *bool `json:"active,omitempty" url:"active,omitempty"`
	// ID of the loyalty card this poster links to
	CardID int `json:"card_id" url:"card_id"`
	// Which contact fields appear on the public signup form
	ContactCollectionMode *string `json:"contact_collection_mode,omitempty" url:"contact_collection_mode,omitempty"`
	// Minimum customer age required for signup. Requires require_birthday to be true.
	MinimumAge *float64 `json:"minimum_age,omitempty" url:"minimum_age,omitempty"`
	// Print size – one of: a4, a5, a6, letter
	PaperSize *string `json:"paper_size,omitempty" url:"paper_size,omitempty"`
	// Primary brand color as a hex string (e.g. '#FF5733')
	PrimaryColor *string `json:"primary_color,omitempty" url:"primary_color,omitempty"`
	// Whether date of birth is required on the public signup form
	RequireBirthday *bool `json:"require_birthday,omitempty" url:"require_birthday,omitempty"`
	// Whether email is required when it is collected
	RequireEmail *bool `json:"require_email,omitempty" url:"require_email,omitempty"`
	// Whether phone number is required when it is collected
	RequirePhone *bool `json:"require_phone,omitempty" url:"require_phone,omitempty"`
	// Secondary brand color as a hex string
	SecondaryColor *string `json:"secondary_color,omitempty" url:"secondary_color,omitempty"`
	// Text color as a hex string
	TextColor *string `json:"text_color,omitempty" url:"text_color,omitempty"`
	// Headline text displayed on the poster
	Title *string `json:"title,omitempty" url:"title,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePostersRequestPoster) GetActive() *bool {
	if c == nil {
		return nil
	}
	return c.Active
}

func (c *CreatePostersRequestPoster) GetCardID() int {
	if c == nil {
		return 0
	}
	return c.CardID
}

func (c *CreatePostersRequestPoster) GetContactCollectionMode() *string {
	if c == nil {
		return nil
	}
	return c.ContactCollectionMode
}

func (c *CreatePostersRequestPoster) GetMinimumAge() *float64 {
	if c == nil {
		return nil
	}
	return c.MinimumAge
}

func (c *CreatePostersRequestPoster) GetPaperSize() *string {
	if c == nil {
		return nil
	}
	return c.PaperSize
}

func (c *CreatePostersRequestPoster) GetPrimaryColor() *string {
	if c == nil {
		return nil
	}
	return c.PrimaryColor
}

func (c *CreatePostersRequestPoster) GetRequireBirthday() *bool {
	if c == nil {
		return nil
	}
	return c.RequireBirthday
}

func (c *CreatePostersRequestPoster) GetRequireEmail() *bool {
	if c == nil {
		return nil
	}
	return c.RequireEmail
}

func (c *CreatePostersRequestPoster) GetRequirePhone() *bool {
	if c == nil {
		return nil
	}
	return c.RequirePhone
}

func (c *CreatePostersRequestPoster) GetSecondaryColor() *string {
	if c == nil {
		return nil
	}
	return c.SecondaryColor
}

func (c *CreatePostersRequestPoster) GetTextColor() *string {
	if c == nil {
		return nil
	}
	return c.TextColor
}

func (c *CreatePostersRequestPoster) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *CreatePostersRequestPoster) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePostersRequestPoster) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetActive(active *bool) {
	c.Active = active
	c.require(createPostersRequestPosterFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetCardID(cardID int) {
	c.CardID = cardID
	c.require(createPostersRequestPosterFieldCardID)
}

// SetContactCollectionMode sets the ContactCollectionMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetContactCollectionMode(contactCollectionMode *string) {
	c.ContactCollectionMode = contactCollectionMode
	c.require(createPostersRequestPosterFieldContactCollectionMode)
}

// SetMinimumAge sets the MinimumAge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetMinimumAge(minimumAge *float64) {
	c.MinimumAge = minimumAge
	c.require(createPostersRequestPosterFieldMinimumAge)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetPaperSize(paperSize *string) {
	c.PaperSize = paperSize
	c.require(createPostersRequestPosterFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetPrimaryColor(primaryColor *string) {
	c.PrimaryColor = primaryColor
	c.require(createPostersRequestPosterFieldPrimaryColor)
}

// SetRequireBirthday sets the RequireBirthday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetRequireBirthday(requireBirthday *bool) {
	c.RequireBirthday = requireBirthday
	c.require(createPostersRequestPosterFieldRequireBirthday)
}

// SetRequireEmail sets the RequireEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetRequireEmail(requireEmail *bool) {
	c.RequireEmail = requireEmail
	c.require(createPostersRequestPosterFieldRequireEmail)
}

// SetRequirePhone sets the RequirePhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetRequirePhone(requirePhone *bool) {
	c.RequirePhone = requirePhone
	c.require(createPostersRequestPosterFieldRequirePhone)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetSecondaryColor(secondaryColor *string) {
	c.SecondaryColor = secondaryColor
	c.require(createPostersRequestPosterFieldSecondaryColor)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetTextColor(textColor *string) {
	c.TextColor = textColor
	c.require(createPostersRequestPosterFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetTitle(title *string) {
	c.Title = title
	c.require(createPostersRequestPosterFieldTitle)
}

func (c *CreatePostersRequestPoster) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePostersRequestPoster
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePostersRequestPoster(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePostersRequestPoster) MarshalJSON() ([]byte, error) {
	type embed CreatePostersRequestPoster
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePostersRequestPoster) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createPostersResponseFieldAccountID             = big.NewInt(1 << 0)
	createPostersResponseFieldActive                = big.NewInt(1 << 1)
	createPostersResponseFieldCardID                = big.NewInt(1 << 2)
	createPostersResponseFieldCollectEmail          = big.NewInt(1 << 3)
	createPostersResponseFieldCollectPhone          = big.NewInt(1 << 4)
	createPostersResponseFieldContactCollectionMode = big.NewInt(1 << 5)
	createPostersResponseFieldCreatedAt             = big.NewInt(1 << 6)
	createPostersResponseFieldDisplayURL            = big.NewInt(1 << 7)
	createPostersResponseFieldID                    = big.NewInt(1 << 8)
	createPostersResponseFieldMinimumAge            = big.NewInt(1 << 9)
	createPostersResponseFieldPaperSize             = big.NewInt(1 << 10)
	createPostersResponseFieldPrimaryColor          = big.NewInt(1 << 11)
	createPostersResponseFieldQrCodeURL             = big.NewInt(1 << 12)
	createPostersResponseFieldRequireBirthday       = big.NewInt(1 << 13)
	createPostersResponseFieldRequireEmail          = big.NewInt(1 << 14)
	createPostersResponseFieldRequirePhone          = big.NewInt(1 << 15)
	createPostersResponseFieldSecondaryColor        = big.NewInt(1 << 16)
	createPostersResponseFieldSignupURL             = big.NewInt(1 << 17)
	createPostersResponseFieldTextColor             = big.NewInt(1 << 18)
	createPostersResponseFieldTitle                 = big.NewInt(1 << 19)
	createPostersResponseFieldUpdatedAt             = big.NewInt(1 << 20)
)

type CreatePostersResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// Whether the public signup form collects email
	CollectEmail bool `json:"collect_email" url:"collect_email"`
	// Whether the public signup form collects phone number
	CollectPhone bool `json:"collect_phone" url:"collect_phone"`
	// Which contact fields appear on the public signup form: 'email_and_phone', 'email_only', or 'phone_only'
	ContactCollectionMode string `json:"contact_collection_mode" url:"contact_collection_mode"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Minimum customer age required for signup
	MinimumAge float64 `json:"minimum_age" url:"minimum_age"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Whether date of birth is required on the public signup form
	RequireBirthday bool `json:"require_birthday" url:"require_birthday"`
	// Whether email is required when it is collected
	RequireEmail bool `json:"require_email" url:"require_email"`
	// Whether phone number is required when it is collected
	RequirePhone bool `json:"require_phone" url:"require_phone"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePostersResponse) GetAccountID() int {
	if c == nil {
		return 0
	}
	return c.AccountID
}

func (c *CreatePostersResponse) GetActive() bool {
	if c == nil {
		return false
	}
	return c.Active
}

func (c *CreatePostersResponse) GetCardID() int {
	if c == nil {
		return 0
	}
	return c.CardID
}

func (c *CreatePostersResponse) GetCollectEmail() bool {
	if c == nil {
		return false
	}
	return c.CollectEmail
}

func (c *CreatePostersResponse) GetCollectPhone() bool {
	if c == nil {
		return false
	}
	return c.CollectPhone
}

func (c *CreatePostersResponse) GetContactCollectionMode() string {
	if c == nil {
		return ""
	}
	return c.ContactCollectionMode
}

func (c *CreatePostersResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreatePostersResponse) GetDisplayURL() string {
	if c == nil {
		return ""
	}
	return c.DisplayURL
}

func (c *CreatePostersResponse) GetID() int {
	if c == nil {
		return 0
	}
	return c.ID
}

func (c *CreatePostersResponse) GetMinimumAge() float64 {
	if c == nil {
		return 0
	}
	return c.MinimumAge
}

func (c *CreatePostersResponse) GetPaperSize() string {
	if c == nil {
		return ""
	}
	return c.PaperSize
}

func (c *CreatePostersResponse) GetPrimaryColor() string {
	if c == nil {
		return ""
	}
	return c.PrimaryColor
}

func (c *CreatePostersResponse) GetQrCodeURL() string {
	if c == nil {
		return ""
	}
	return c.QrCodeURL
}

func (c *CreatePostersResponse) GetRequireBirthday() bool {
	if c == nil {
		return false
	}
	return c.RequireBirthday
}

func (c *CreatePostersResponse) GetRequireEmail() bool {
	if c == nil {
		return false
	}
	return c.RequireEmail
}

func (c *CreatePostersResponse) GetRequirePhone() bool {
	if c == nil {
		return false
	}
	return c.RequirePhone
}

func (c *CreatePostersResponse) GetSecondaryColor() string {
	if c == nil {
		return ""
	}
	return c.SecondaryColor
}

func (c *CreatePostersResponse) GetSignupURL() string {
	if c == nil {
		return ""
	}
	return c.SignupURL
}

func (c *CreatePostersResponse) GetTextColor() string {
	if c == nil {
		return ""
	}
	return c.TextColor
}

func (c *CreatePostersResponse) GetTitle() string {
	if c == nil {
		return ""
	}
	return c.Title
}

func (c *CreatePostersResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreatePostersResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePostersResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createPostersResponseFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetActive(active bool) {
	c.Active = active
	c.require(createPostersResponseFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetCardID(cardID int) {
	c.CardID = cardID
	c.require(createPostersResponseFieldCardID)
}

// SetCollectEmail sets the CollectEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetCollectEmail(collectEmail bool) {
	c.CollectEmail = collectEmail
	c.require(createPostersResponseFieldCollectEmail)
}

// SetCollectPhone sets the CollectPhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetCollectPhone(collectPhone bool) {
	c.CollectPhone = collectPhone
	c.require(createPostersResponseFieldCollectPhone)
}

// SetContactCollectionMode sets the ContactCollectionMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetContactCollectionMode(contactCollectionMode string) {
	c.ContactCollectionMode = contactCollectionMode
	c.require(createPostersResponseFieldContactCollectionMode)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createPostersResponseFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetDisplayURL(displayURL string) {
	c.DisplayURL = displayURL
	c.require(createPostersResponseFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetID(id int) {
	c.ID = id
	c.require(createPostersResponseFieldID)
}

// SetMinimumAge sets the MinimumAge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetMinimumAge(minimumAge float64) {
	c.MinimumAge = minimumAge
	c.require(createPostersResponseFieldMinimumAge)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetPaperSize(paperSize string) {
	c.PaperSize = paperSize
	c.require(createPostersResponseFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetPrimaryColor(primaryColor string) {
	c.PrimaryColor = primaryColor
	c.require(createPostersResponseFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetQrCodeURL(qrCodeURL string) {
	c.QrCodeURL = qrCodeURL
	c.require(createPostersResponseFieldQrCodeURL)
}

// SetRequireBirthday sets the RequireBirthday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetRequireBirthday(requireBirthday bool) {
	c.RequireBirthday = requireBirthday
	c.require(createPostersResponseFieldRequireBirthday)
}

// SetRequireEmail sets the RequireEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetRequireEmail(requireEmail bool) {
	c.RequireEmail = requireEmail
	c.require(createPostersResponseFieldRequireEmail)
}

// SetRequirePhone sets the RequirePhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetRequirePhone(requirePhone bool) {
	c.RequirePhone = requirePhone
	c.require(createPostersResponseFieldRequirePhone)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetSecondaryColor(secondaryColor string) {
	c.SecondaryColor = secondaryColor
	c.require(createPostersResponseFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetSignupURL(signupURL string) {
	c.SignupURL = signupURL
	c.require(createPostersResponseFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetTextColor(textColor string) {
	c.TextColor = textColor
	c.require(createPostersResponseFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetTitle(title string) {
	c.Title = title
	c.require(createPostersResponseFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createPostersResponseFieldUpdatedAt)
}

func (c *CreatePostersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePostersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePostersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePostersResponse) MarshalJSON() ([]byte, error) {
	type embed CreatePostersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePostersResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getPostersResponseFieldAccountID             = big.NewInt(1 << 0)
	getPostersResponseFieldActive                = big.NewInt(1 << 1)
	getPostersResponseFieldCardID                = big.NewInt(1 << 2)
	getPostersResponseFieldCollectEmail          = big.NewInt(1 << 3)
	getPostersResponseFieldCollectPhone          = big.NewInt(1 << 4)
	getPostersResponseFieldContactCollectionMode = big.NewInt(1 << 5)
	getPostersResponseFieldCreatedAt             = big.NewInt(1 << 6)
	getPostersResponseFieldDisplayURL            = big.NewInt(1 << 7)
	getPostersResponseFieldID                    = big.NewInt(1 << 8)
	getPostersResponseFieldMinimumAge            = big.NewInt(1 << 9)
	getPostersResponseFieldPaperSize             = big.NewInt(1 << 10)
	getPostersResponseFieldPrimaryColor          = big.NewInt(1 << 11)
	getPostersResponseFieldQrCodeURL             = big.NewInt(1 << 12)
	getPostersResponseFieldRequireBirthday       = big.NewInt(1 << 13)
	getPostersResponseFieldRequireEmail          = big.NewInt(1 << 14)
	getPostersResponseFieldRequirePhone          = big.NewInt(1 << 15)
	getPostersResponseFieldSecondaryColor        = big.NewInt(1 << 16)
	getPostersResponseFieldSignupURL             = big.NewInt(1 << 17)
	getPostersResponseFieldTextColor             = big.NewInt(1 << 18)
	getPostersResponseFieldTitle                 = big.NewInt(1 << 19)
	getPostersResponseFieldUpdatedAt             = big.NewInt(1 << 20)
)

type GetPostersResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// Whether the public signup form collects email
	CollectEmail bool `json:"collect_email" url:"collect_email"`
	// Whether the public signup form collects phone number
	CollectPhone bool `json:"collect_phone" url:"collect_phone"`
	// Which contact fields appear on the public signup form: 'email_and_phone', 'email_only', or 'phone_only'
	ContactCollectionMode string `json:"contact_collection_mode" url:"contact_collection_mode"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Minimum customer age required for signup
	MinimumAge float64 `json:"minimum_age" url:"minimum_age"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Whether date of birth is required on the public signup form
	RequireBirthday bool `json:"require_birthday" url:"require_birthday"`
	// Whether email is required when it is collected
	RequireEmail bool `json:"require_email" url:"require_email"`
	// Whether phone number is required when it is collected
	RequirePhone bool `json:"require_phone" url:"require_phone"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPostersResponse) GetAccountID() int {
	if g == nil {
		return 0
	}
	return g.AccountID
}

func (g *GetPostersResponse) GetActive() bool {
	if g == nil {
		return false
	}
	return g.Active
}

func (g *GetPostersResponse) GetCardID() int {
	if g == nil {
		return 0
	}
	return g.CardID
}

func (g *GetPostersResponse) GetCollectEmail() bool {
	if g == nil {
		return false
	}
	return g.CollectEmail
}

func (g *GetPostersResponse) GetCollectPhone() bool {
	if g == nil {
		return false
	}
	return g.CollectPhone
}

func (g *GetPostersResponse) GetContactCollectionMode() string {
	if g == nil {
		return ""
	}
	return g.ContactCollectionMode
}

func (g *GetPostersResponse) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetPostersResponse) GetDisplayURL() string {
	if g == nil {
		return ""
	}
	return g.DisplayURL
}

func (g *GetPostersResponse) GetID() int {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetPostersResponse) GetMinimumAge() float64 {
	if g == nil {
		return 0
	}
	return g.MinimumAge
}

func (g *GetPostersResponse) GetPaperSize() string {
	if g == nil {
		return ""
	}
	return g.PaperSize
}

func (g *GetPostersResponse) GetPrimaryColor() string {
	if g == nil {
		return ""
	}
	return g.PrimaryColor
}

func (g *GetPostersResponse) GetQrCodeURL() string {
	if g == nil {
		return ""
	}
	return g.QrCodeURL
}

func (g *GetPostersResponse) GetRequireBirthday() bool {
	if g == nil {
		return false
	}
	return g.RequireBirthday
}

func (g *GetPostersResponse) GetRequireEmail() bool {
	if g == nil {
		return false
	}
	return g.RequireEmail
}

func (g *GetPostersResponse) GetRequirePhone() bool {
	if g == nil {
		return false
	}
	return g.RequirePhone
}

func (g *GetPostersResponse) GetSecondaryColor() string {
	if g == nil {
		return ""
	}
	return g.SecondaryColor
}

func (g *GetPostersResponse) GetSignupURL() string {
	if g == nil {
		return ""
	}
	return g.SignupURL
}

func (g *GetPostersResponse) GetTextColor() string {
	if g == nil {
		return ""
	}
	return g.TextColor
}

func (g *GetPostersResponse) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GetPostersResponse) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetPostersResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetPostersResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getPostersResponseFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetActive(active bool) {
	g.Active = active
	g.require(getPostersResponseFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetCardID(cardID int) {
	g.CardID = cardID
	g.require(getPostersResponseFieldCardID)
}

// SetCollectEmail sets the CollectEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetCollectEmail(collectEmail bool) {
	g.CollectEmail = collectEmail
	g.require(getPostersResponseFieldCollectEmail)
}

// SetCollectPhone sets the CollectPhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetCollectPhone(collectPhone bool) {
	g.CollectPhone = collectPhone
	g.require(getPostersResponseFieldCollectPhone)
}

// SetContactCollectionMode sets the ContactCollectionMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetContactCollectionMode(contactCollectionMode string) {
	g.ContactCollectionMode = contactCollectionMode
	g.require(getPostersResponseFieldContactCollectionMode)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getPostersResponseFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetDisplayURL(displayURL string) {
	g.DisplayURL = displayURL
	g.require(getPostersResponseFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetID(id int) {
	g.ID = id
	g.require(getPostersResponseFieldID)
}

// SetMinimumAge sets the MinimumAge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetMinimumAge(minimumAge float64) {
	g.MinimumAge = minimumAge
	g.require(getPostersResponseFieldMinimumAge)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetPaperSize(paperSize string) {
	g.PaperSize = paperSize
	g.require(getPostersResponseFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetPrimaryColor(primaryColor string) {
	g.PrimaryColor = primaryColor
	g.require(getPostersResponseFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetQrCodeURL(qrCodeURL string) {
	g.QrCodeURL = qrCodeURL
	g.require(getPostersResponseFieldQrCodeURL)
}

// SetRequireBirthday sets the RequireBirthday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetRequireBirthday(requireBirthday bool) {
	g.RequireBirthday = requireBirthday
	g.require(getPostersResponseFieldRequireBirthday)
}

// SetRequireEmail sets the RequireEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetRequireEmail(requireEmail bool) {
	g.RequireEmail = requireEmail
	g.require(getPostersResponseFieldRequireEmail)
}

// SetRequirePhone sets the RequirePhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetRequirePhone(requirePhone bool) {
	g.RequirePhone = requirePhone
	g.require(getPostersResponseFieldRequirePhone)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetSecondaryColor(secondaryColor string) {
	g.SecondaryColor = secondaryColor
	g.require(getPostersResponseFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetSignupURL(signupURL string) {
	g.SignupURL = signupURL
	g.require(getPostersResponseFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetTextColor(textColor string) {
	g.TextColor = textColor
	g.require(getPostersResponseFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetTitle(title string) {
	g.Title = title
	g.require(getPostersResponseFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getPostersResponseFieldUpdatedAt)
}

func (g *GetPostersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPostersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPostersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPostersResponse) MarshalJSON() ([]byte, error) {
	type embed GetPostersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPostersResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listPostersResponseItemFieldAccountID             = big.NewInt(1 << 0)
	listPostersResponseItemFieldActive                = big.NewInt(1 << 1)
	listPostersResponseItemFieldCardID                = big.NewInt(1 << 2)
	listPostersResponseItemFieldCollectEmail          = big.NewInt(1 << 3)
	listPostersResponseItemFieldCollectPhone          = big.NewInt(1 << 4)
	listPostersResponseItemFieldContactCollectionMode = big.NewInt(1 << 5)
	listPostersResponseItemFieldCreatedAt             = big.NewInt(1 << 6)
	listPostersResponseItemFieldDisplayURL            = big.NewInt(1 << 7)
	listPostersResponseItemFieldID                    = big.NewInt(1 << 8)
	listPostersResponseItemFieldMinimumAge            = big.NewInt(1 << 9)
	listPostersResponseItemFieldPaperSize             = big.NewInt(1 << 10)
	listPostersResponseItemFieldPrimaryColor          = big.NewInt(1 << 11)
	listPostersResponseItemFieldQrCodeURL             = big.NewInt(1 << 12)
	listPostersResponseItemFieldRequireBirthday       = big.NewInt(1 << 13)
	listPostersResponseItemFieldRequireEmail          = big.NewInt(1 << 14)
	listPostersResponseItemFieldRequirePhone          = big.NewInt(1 << 15)
	listPostersResponseItemFieldSecondaryColor        = big.NewInt(1 << 16)
	listPostersResponseItemFieldSignupURL             = big.NewInt(1 << 17)
	listPostersResponseItemFieldTextColor             = big.NewInt(1 << 18)
	listPostersResponseItemFieldTitle                 = big.NewInt(1 << 19)
	listPostersResponseItemFieldUpdatedAt             = big.NewInt(1 << 20)
)

type ListPostersResponseItem struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// Whether the public signup form collects email
	CollectEmail bool `json:"collect_email" url:"collect_email"`
	// Whether the public signup form collects phone number
	CollectPhone bool `json:"collect_phone" url:"collect_phone"`
	// Which contact fields appear on the public signup form: 'email_and_phone', 'email_only', or 'phone_only'
	ContactCollectionMode string `json:"contact_collection_mode" url:"contact_collection_mode"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Minimum customer age required for signup
	MinimumAge float64 `json:"minimum_age" url:"minimum_age"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Whether date of birth is required on the public signup form
	RequireBirthday bool `json:"require_birthday" url:"require_birthday"`
	// Whether email is required when it is collected
	RequireEmail bool `json:"require_email" url:"require_email"`
	// Whether phone number is required when it is collected
	RequirePhone bool `json:"require_phone" url:"require_phone"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPostersResponseItem) GetAccountID() int {
	if l == nil {
		return 0
	}
	return l.AccountID
}

func (l *ListPostersResponseItem) GetActive() bool {
	if l == nil {
		return false
	}
	return l.Active
}

func (l *ListPostersResponseItem) GetCardID() int {
	if l == nil {
		return 0
	}
	return l.CardID
}

func (l *ListPostersResponseItem) GetCollectEmail() bool {
	if l == nil {
		return false
	}
	return l.CollectEmail
}

func (l *ListPostersResponseItem) GetCollectPhone() bool {
	if l == nil {
		return false
	}
	return l.CollectPhone
}

func (l *ListPostersResponseItem) GetContactCollectionMode() string {
	if l == nil {
		return ""
	}
	return l.ContactCollectionMode
}

func (l *ListPostersResponseItem) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListPostersResponseItem) GetDisplayURL() string {
	if l == nil {
		return ""
	}
	return l.DisplayURL
}

func (l *ListPostersResponseItem) GetID() int {
	if l == nil {
		return 0
	}
	return l.ID
}

func (l *ListPostersResponseItem) GetMinimumAge() float64 {
	if l == nil {
		return 0
	}
	return l.MinimumAge
}

func (l *ListPostersResponseItem) GetPaperSize() string {
	if l == nil {
		return ""
	}
	return l.PaperSize
}

func (l *ListPostersResponseItem) GetPrimaryColor() string {
	if l == nil {
		return ""
	}
	return l.PrimaryColor
}

func (l *ListPostersResponseItem) GetQrCodeURL() string {
	if l == nil {
		return ""
	}
	return l.QrCodeURL
}

func (l *ListPostersResponseItem) GetRequireBirthday() bool {
	if l == nil {
		return false
	}
	return l.RequireBirthday
}

func (l *ListPostersResponseItem) GetRequireEmail() bool {
	if l == nil {
		return false
	}
	return l.RequireEmail
}

func (l *ListPostersResponseItem) GetRequirePhone() bool {
	if l == nil {
		return false
	}
	return l.RequirePhone
}

func (l *ListPostersResponseItem) GetSecondaryColor() string {
	if l == nil {
		return ""
	}
	return l.SecondaryColor
}

func (l *ListPostersResponseItem) GetSignupURL() string {
	if l == nil {
		return ""
	}
	return l.SignupURL
}

func (l *ListPostersResponseItem) GetTextColor() string {
	if l == nil {
		return ""
	}
	return l.TextColor
}

func (l *ListPostersResponseItem) GetTitle() string {
	if l == nil {
		return ""
	}
	return l.Title
}

func (l *ListPostersResponseItem) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListPostersResponseItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListPostersResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listPostersResponseItemFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetActive(active bool) {
	l.Active = active
	l.require(listPostersResponseItemFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetCardID(cardID int) {
	l.CardID = cardID
	l.require(listPostersResponseItemFieldCardID)
}

// SetCollectEmail sets the CollectEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetCollectEmail(collectEmail bool) {
	l.CollectEmail = collectEmail
	l.require(listPostersResponseItemFieldCollectEmail)
}

// SetCollectPhone sets the CollectPhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetCollectPhone(collectPhone bool) {
	l.CollectPhone = collectPhone
	l.require(listPostersResponseItemFieldCollectPhone)
}

// SetContactCollectionMode sets the ContactCollectionMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetContactCollectionMode(contactCollectionMode string) {
	l.ContactCollectionMode = contactCollectionMode
	l.require(listPostersResponseItemFieldContactCollectionMode)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetCreatedAt(createdAt string) {
	l.CreatedAt = createdAt
	l.require(listPostersResponseItemFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetDisplayURL(displayURL string) {
	l.DisplayURL = displayURL
	l.require(listPostersResponseItemFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetID(id int) {
	l.ID = id
	l.require(listPostersResponseItemFieldID)
}

// SetMinimumAge sets the MinimumAge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetMinimumAge(minimumAge float64) {
	l.MinimumAge = minimumAge
	l.require(listPostersResponseItemFieldMinimumAge)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetPaperSize(paperSize string) {
	l.PaperSize = paperSize
	l.require(listPostersResponseItemFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetPrimaryColor(primaryColor string) {
	l.PrimaryColor = primaryColor
	l.require(listPostersResponseItemFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetQrCodeURL(qrCodeURL string) {
	l.QrCodeURL = qrCodeURL
	l.require(listPostersResponseItemFieldQrCodeURL)
}

// SetRequireBirthday sets the RequireBirthday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetRequireBirthday(requireBirthday bool) {
	l.RequireBirthday = requireBirthday
	l.require(listPostersResponseItemFieldRequireBirthday)
}

// SetRequireEmail sets the RequireEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetRequireEmail(requireEmail bool) {
	l.RequireEmail = requireEmail
	l.require(listPostersResponseItemFieldRequireEmail)
}

// SetRequirePhone sets the RequirePhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetRequirePhone(requirePhone bool) {
	l.RequirePhone = requirePhone
	l.require(listPostersResponseItemFieldRequirePhone)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetSecondaryColor(secondaryColor string) {
	l.SecondaryColor = secondaryColor
	l.require(listPostersResponseItemFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetSignupURL(signupURL string) {
	l.SignupURL = signupURL
	l.require(listPostersResponseItemFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetTextColor(textColor string) {
	l.TextColor = textColor
	l.require(listPostersResponseItemFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetTitle(title string) {
	l.Title = title
	l.require(listPostersResponseItemFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetUpdatedAt(updatedAt string) {
	l.UpdatedAt = updatedAt
	l.require(listPostersResponseItemFieldUpdatedAt)
}

func (l *ListPostersResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPostersResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPostersResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPostersResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListPostersResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPostersResponseItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	updatePostersRequestPosterFieldActive                = big.NewInt(1 << 0)
	updatePostersRequestPosterFieldContactCollectionMode = big.NewInt(1 << 1)
	updatePostersRequestPosterFieldMinimumAge            = big.NewInt(1 << 2)
	updatePostersRequestPosterFieldPaperSize             = big.NewInt(1 << 3)
	updatePostersRequestPosterFieldPrimaryColor          = big.NewInt(1 << 4)
	updatePostersRequestPosterFieldRequireBirthday       = big.NewInt(1 << 5)
	updatePostersRequestPosterFieldRequireEmail          = big.NewInt(1 << 6)
	updatePostersRequestPosterFieldRequirePhone          = big.NewInt(1 << 7)
	updatePostersRequestPosterFieldSecondaryColor        = big.NewInt(1 << 8)
	updatePostersRequestPosterFieldTextColor             = big.NewInt(1 << 9)
	updatePostersRequestPosterFieldTitle                 = big.NewInt(1 << 10)
)

type UpdatePostersRequestPoster struct {
	// Whether the poster is active
	Active *bool `json:"active,omitempty" url:"active,omitempty"`
	// Which contact fields appear on the public signup form
	ContactCollectionMode *string `json:"contact_collection_mode,omitempty" url:"contact_collection_mode,omitempty"`
	// Minimum customer age required for signup. Requires require_birthday to be true.
	MinimumAge *float64 `json:"minimum_age,omitempty" url:"minimum_age,omitempty"`
	// Print size – one of: a4, a5, a6, letter
	PaperSize *string `json:"paper_size,omitempty" url:"paper_size,omitempty"`
	// Primary brand color as a hex string
	PrimaryColor *string `json:"primary_color,omitempty" url:"primary_color,omitempty"`
	// Whether date of birth is required on the public signup form
	RequireBirthday *bool `json:"require_birthday,omitempty" url:"require_birthday,omitempty"`
	// Whether email is required when it is collected
	RequireEmail *bool `json:"require_email,omitempty" url:"require_email,omitempty"`
	// Whether phone number is required when it is collected
	RequirePhone *bool `json:"require_phone,omitempty" url:"require_phone,omitempty"`
	// Secondary brand color as a hex string
	SecondaryColor *string `json:"secondary_color,omitempty" url:"secondary_color,omitempty"`
	// Text color as a hex string
	TextColor *string `json:"text_color,omitempty" url:"text_color,omitempty"`
	// Headline text displayed on the poster
	Title *string `json:"title,omitempty" url:"title,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePostersRequestPoster) GetActive() *bool {
	if u == nil {
		return nil
	}
	return u.Active
}

func (u *UpdatePostersRequestPoster) GetContactCollectionMode() *string {
	if u == nil {
		return nil
	}
	return u.ContactCollectionMode
}

func (u *UpdatePostersRequestPoster) GetMinimumAge() *float64 {
	if u == nil {
		return nil
	}
	return u.MinimumAge
}

func (u *UpdatePostersRequestPoster) GetPaperSize() *string {
	if u == nil {
		return nil
	}
	return u.PaperSize
}

func (u *UpdatePostersRequestPoster) GetPrimaryColor() *string {
	if u == nil {
		return nil
	}
	return u.PrimaryColor
}

func (u *UpdatePostersRequestPoster) GetRequireBirthday() *bool {
	if u == nil {
		return nil
	}
	return u.RequireBirthday
}

func (u *UpdatePostersRequestPoster) GetRequireEmail() *bool {
	if u == nil {
		return nil
	}
	return u.RequireEmail
}

func (u *UpdatePostersRequestPoster) GetRequirePhone() *bool {
	if u == nil {
		return nil
	}
	return u.RequirePhone
}

func (u *UpdatePostersRequestPoster) GetSecondaryColor() *string {
	if u == nil {
		return nil
	}
	return u.SecondaryColor
}

func (u *UpdatePostersRequestPoster) GetTextColor() *string {
	if u == nil {
		return nil
	}
	return u.TextColor
}

func (u *UpdatePostersRequestPoster) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdatePostersRequestPoster) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePostersRequestPoster) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetActive(active *bool) {
	u.Active = active
	u.require(updatePostersRequestPosterFieldActive)
}

// SetContactCollectionMode sets the ContactCollectionMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetContactCollectionMode(contactCollectionMode *string) {
	u.ContactCollectionMode = contactCollectionMode
	u.require(updatePostersRequestPosterFieldContactCollectionMode)
}

// SetMinimumAge sets the MinimumAge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetMinimumAge(minimumAge *float64) {
	u.MinimumAge = minimumAge
	u.require(updatePostersRequestPosterFieldMinimumAge)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetPaperSize(paperSize *string) {
	u.PaperSize = paperSize
	u.require(updatePostersRequestPosterFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetPrimaryColor(primaryColor *string) {
	u.PrimaryColor = primaryColor
	u.require(updatePostersRequestPosterFieldPrimaryColor)
}

// SetRequireBirthday sets the RequireBirthday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetRequireBirthday(requireBirthday *bool) {
	u.RequireBirthday = requireBirthday
	u.require(updatePostersRequestPosterFieldRequireBirthday)
}

// SetRequireEmail sets the RequireEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetRequireEmail(requireEmail *bool) {
	u.RequireEmail = requireEmail
	u.require(updatePostersRequestPosterFieldRequireEmail)
}

// SetRequirePhone sets the RequirePhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetRequirePhone(requirePhone *bool) {
	u.RequirePhone = requirePhone
	u.require(updatePostersRequestPosterFieldRequirePhone)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetSecondaryColor(secondaryColor *string) {
	u.SecondaryColor = secondaryColor
	u.require(updatePostersRequestPosterFieldSecondaryColor)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetTextColor(textColor *string) {
	u.TextColor = textColor
	u.require(updatePostersRequestPosterFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetTitle(title *string) {
	u.Title = title
	u.require(updatePostersRequestPosterFieldTitle)
}

func (u *UpdatePostersRequestPoster) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePostersRequestPoster
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePostersRequestPoster(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePostersRequestPoster) MarshalJSON() ([]byte, error) {
	type embed UpdatePostersRequestPoster
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePostersRequestPoster) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updatePostersResponseFieldAccountID             = big.NewInt(1 << 0)
	updatePostersResponseFieldActive                = big.NewInt(1 << 1)
	updatePostersResponseFieldCardID                = big.NewInt(1 << 2)
	updatePostersResponseFieldCollectEmail          = big.NewInt(1 << 3)
	updatePostersResponseFieldCollectPhone          = big.NewInt(1 << 4)
	updatePostersResponseFieldContactCollectionMode = big.NewInt(1 << 5)
	updatePostersResponseFieldCreatedAt             = big.NewInt(1 << 6)
	updatePostersResponseFieldDisplayURL            = big.NewInt(1 << 7)
	updatePostersResponseFieldID                    = big.NewInt(1 << 8)
	updatePostersResponseFieldMinimumAge            = big.NewInt(1 << 9)
	updatePostersResponseFieldPaperSize             = big.NewInt(1 << 10)
	updatePostersResponseFieldPrimaryColor          = big.NewInt(1 << 11)
	updatePostersResponseFieldQrCodeURL             = big.NewInt(1 << 12)
	updatePostersResponseFieldRequireBirthday       = big.NewInt(1 << 13)
	updatePostersResponseFieldRequireEmail          = big.NewInt(1 << 14)
	updatePostersResponseFieldRequirePhone          = big.NewInt(1 << 15)
	updatePostersResponseFieldSecondaryColor        = big.NewInt(1 << 16)
	updatePostersResponseFieldSignupURL             = big.NewInt(1 << 17)
	updatePostersResponseFieldTextColor             = big.NewInt(1 << 18)
	updatePostersResponseFieldTitle                 = big.NewInt(1 << 19)
	updatePostersResponseFieldUpdatedAt             = big.NewInt(1 << 20)
)

type UpdatePostersResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// Whether the public signup form collects email
	CollectEmail bool `json:"collect_email" url:"collect_email"`
	// Whether the public signup form collects phone number
	CollectPhone bool `json:"collect_phone" url:"collect_phone"`
	// Which contact fields appear on the public signup form: 'email_and_phone', 'email_only', or 'phone_only'
	ContactCollectionMode string `json:"contact_collection_mode" url:"contact_collection_mode"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Minimum customer age required for signup
	MinimumAge float64 `json:"minimum_age" url:"minimum_age"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Whether date of birth is required on the public signup form
	RequireBirthday bool `json:"require_birthday" url:"require_birthday"`
	// Whether email is required when it is collected
	RequireEmail bool `json:"require_email" url:"require_email"`
	// Whether phone number is required when it is collected
	RequirePhone bool `json:"require_phone" url:"require_phone"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePostersResponse) GetAccountID() int {
	if u == nil {
		return 0
	}
	return u.AccountID
}

func (u *UpdatePostersResponse) GetActive() bool {
	if u == nil {
		return false
	}
	return u.Active
}

func (u *UpdatePostersResponse) GetCardID() int {
	if u == nil {
		return 0
	}
	return u.CardID
}

func (u *UpdatePostersResponse) GetCollectEmail() bool {
	if u == nil {
		return false
	}
	return u.CollectEmail
}

func (u *UpdatePostersResponse) GetCollectPhone() bool {
	if u == nil {
		return false
	}
	return u.CollectPhone
}

func (u *UpdatePostersResponse) GetContactCollectionMode() string {
	if u == nil {
		return ""
	}
	return u.ContactCollectionMode
}

func (u *UpdatePostersResponse) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdatePostersResponse) GetDisplayURL() string {
	if u == nil {
		return ""
	}
	return u.DisplayURL
}

func (u *UpdatePostersResponse) GetID() int {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdatePostersResponse) GetMinimumAge() float64 {
	if u == nil {
		return 0
	}
	return u.MinimumAge
}

func (u *UpdatePostersResponse) GetPaperSize() string {
	if u == nil {
		return ""
	}
	return u.PaperSize
}

func (u *UpdatePostersResponse) GetPrimaryColor() string {
	if u == nil {
		return ""
	}
	return u.PrimaryColor
}

func (u *UpdatePostersResponse) GetQrCodeURL() string {
	if u == nil {
		return ""
	}
	return u.QrCodeURL
}

func (u *UpdatePostersResponse) GetRequireBirthday() bool {
	if u == nil {
		return false
	}
	return u.RequireBirthday
}

func (u *UpdatePostersResponse) GetRequireEmail() bool {
	if u == nil {
		return false
	}
	return u.RequireEmail
}

func (u *UpdatePostersResponse) GetRequirePhone() bool {
	if u == nil {
		return false
	}
	return u.RequirePhone
}

func (u *UpdatePostersResponse) GetSecondaryColor() string {
	if u == nil {
		return ""
	}
	return u.SecondaryColor
}

func (u *UpdatePostersResponse) GetSignupURL() string {
	if u == nil {
		return ""
	}
	return u.SignupURL
}

func (u *UpdatePostersResponse) GetTextColor() string {
	if u == nil {
		return ""
	}
	return u.TextColor
}

func (u *UpdatePostersResponse) GetTitle() string {
	if u == nil {
		return ""
	}
	return u.Title
}

func (u *UpdatePostersResponse) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdatePostersResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePostersResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updatePostersResponseFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetActive(active bool) {
	u.Active = active
	u.require(updatePostersResponseFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetCardID(cardID int) {
	u.CardID = cardID
	u.require(updatePostersResponseFieldCardID)
}

// SetCollectEmail sets the CollectEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetCollectEmail(collectEmail bool) {
	u.CollectEmail = collectEmail
	u.require(updatePostersResponseFieldCollectEmail)
}

// SetCollectPhone sets the CollectPhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetCollectPhone(collectPhone bool) {
	u.CollectPhone = collectPhone
	u.require(updatePostersResponseFieldCollectPhone)
}

// SetContactCollectionMode sets the ContactCollectionMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetContactCollectionMode(contactCollectionMode string) {
	u.ContactCollectionMode = contactCollectionMode
	u.require(updatePostersResponseFieldContactCollectionMode)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updatePostersResponseFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetDisplayURL(displayURL string) {
	u.DisplayURL = displayURL
	u.require(updatePostersResponseFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetID(id int) {
	u.ID = id
	u.require(updatePostersResponseFieldID)
}

// SetMinimumAge sets the MinimumAge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetMinimumAge(minimumAge float64) {
	u.MinimumAge = minimumAge
	u.require(updatePostersResponseFieldMinimumAge)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetPaperSize(paperSize string) {
	u.PaperSize = paperSize
	u.require(updatePostersResponseFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetPrimaryColor(primaryColor string) {
	u.PrimaryColor = primaryColor
	u.require(updatePostersResponseFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetQrCodeURL(qrCodeURL string) {
	u.QrCodeURL = qrCodeURL
	u.require(updatePostersResponseFieldQrCodeURL)
}

// SetRequireBirthday sets the RequireBirthday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetRequireBirthday(requireBirthday bool) {
	u.RequireBirthday = requireBirthday
	u.require(updatePostersResponseFieldRequireBirthday)
}

// SetRequireEmail sets the RequireEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetRequireEmail(requireEmail bool) {
	u.RequireEmail = requireEmail
	u.require(updatePostersResponseFieldRequireEmail)
}

// SetRequirePhone sets the RequirePhone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetRequirePhone(requirePhone bool) {
	u.RequirePhone = requirePhone
	u.require(updatePostersResponseFieldRequirePhone)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetSecondaryColor(secondaryColor string) {
	u.SecondaryColor = secondaryColor
	u.require(updatePostersResponseFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetSignupURL(signupURL string) {
	u.SignupURL = signupURL
	u.require(updatePostersResponseFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetTextColor(textColor string) {
	u.TextColor = textColor
	u.require(updatePostersResponseFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetTitle(title string) {
	u.Title = title
	u.require(updatePostersResponseFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updatePostersResponseFieldUpdatedAt)
}

func (u *UpdatePostersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePostersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePostersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePostersResponse) MarshalJSON() ([]byte, error) {
	type embed UpdatePostersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePostersResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updatePostersRequestFieldAccountID = big.NewInt(1 << 0)
	updatePostersRequestFieldID        = big.NewInt(1 << 1)
	updatePostersRequestFieldPoster    = big.NewInt(1 << 2)
)

type UpdatePostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Poster ID
	ID     int                         `json:"-" url:"-"`
	Poster *UpdatePostersRequestPoster `json:"poster" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdatePostersRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequest) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updatePostersRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequest) SetID(id int) {
	u.ID = id
	u.require(updatePostersRequestFieldID)
}

// SetPoster sets the Poster field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequest) SetPoster(poster *UpdatePostersRequestPoster) {
	u.Poster = poster
	u.require(updatePostersRequestFieldPoster)
}

func (u *UpdatePostersRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePostersRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdatePostersRequest(body)
	return nil
}

func (u *UpdatePostersRequest) MarshalJSON() ([]byte, error) {
	type embed UpdatePostersRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
