// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

var (
	createPostersRequestFieldAccountID = big.NewInt(1 << 0)
	createPostersRequestFieldPoster    = big.NewInt(1 << 1)
)

type CreatePostersRequest struct {
	// Store (account) ID
	AccountID int                         `json:"-" url:"-"`
	Poster    *CreatePostersRequestPoster `json:"poster" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePostersRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequest) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createPostersRequestFieldAccountID)
}

// SetPoster sets the Poster field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequest) SetPoster(poster *CreatePostersRequestPoster) {
	c.Poster = poster
	c.require(createPostersRequestFieldPoster)
}

func (c *CreatePostersRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePostersRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePostersRequest(body)
	return nil
}

func (c *CreatePostersRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePostersRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deletePostersRequestFieldAccountID = big.NewInt(1 << 0)
	deletePostersRequestFieldID        = big.NewInt(1 << 1)
)

type DeletePostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Poster ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePostersRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePostersRequest) SetAccountID(accountID int) {
	d.AccountID = accountID
	d.require(deletePostersRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePostersRequest) SetID(id int) {
	d.ID = id
	d.require(deletePostersRequestFieldID)
}

var (
	getPostersRequestFieldAccountID = big.NewInt(1 << 0)
	getPostersRequestFieldID        = big.NewInt(1 << 1)
)

type GetPostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Poster ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPostersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersRequest) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getPostersRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersRequest) SetID(id int) {
	g.ID = id
	g.require(getPostersRequestFieldID)
}

var (
	listPostersRequestFieldAccountID = big.NewInt(1 << 0)
	listPostersRequestFieldCardID    = big.NewInt(1 << 1)
	listPostersRequestFieldActive    = big.NewInt(1 << 2)
)

type ListPostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Filter posters belonging to a specific card
	CardID *int `json:"-" url:"card_id,omitempty"`
	// When present, return only active posters
	Active *string `json:"-" url:"active,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPostersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersRequest) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listPostersRequestFieldAccountID)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersRequest) SetCardID(cardID *int) {
	l.CardID = cardID
	l.require(listPostersRequestFieldCardID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersRequest) SetActive(active *string) {
	l.Active = active
	l.require(listPostersRequestFieldActive)
}

var (
	createPostersRequestPosterFieldActive         = big.NewInt(1 << 0)
	createPostersRequestPosterFieldCardID         = big.NewInt(1 << 1)
	createPostersRequestPosterFieldPaperSize      = big.NewInt(1 << 2)
	createPostersRequestPosterFieldPrimaryColor   = big.NewInt(1 << 3)
	createPostersRequestPosterFieldSecondaryColor = big.NewInt(1 << 4)
	createPostersRequestPosterFieldTextColor      = big.NewInt(1 << 5)
	createPostersRequestPosterFieldTitle          = big.NewInt(1 << 6)
)

type CreatePostersRequestPoster struct {
	// Whether the poster is active (defaults to true)
	Active *bool `json:"active,omitempty" url:"active,omitempty"`
	// ID of the loyalty card this poster links to
	CardID int `json:"card_id" url:"card_id"`
	// Print size – one of: a4, a5, a6, letter
	PaperSize *string `json:"paper_size,omitempty" url:"paper_size,omitempty"`
	// Primary brand color as a hex string (e.g. '#FF5733')
	PrimaryColor *string `json:"primary_color,omitempty" url:"primary_color,omitempty"`
	// Secondary brand color as a hex string
	SecondaryColor *string `json:"secondary_color,omitempty" url:"secondary_color,omitempty"`
	// Text color as a hex string
	TextColor *string `json:"text_color,omitempty" url:"text_color,omitempty"`
	// Headline text displayed on the poster
	Title *string `json:"title,omitempty" url:"title,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePostersRequestPoster) GetActive() *bool {
	if c == nil {
		return nil
	}
	return c.Active
}

func (c *CreatePostersRequestPoster) GetCardID() int {
	if c == nil {
		return 0
	}
	return c.CardID
}

func (c *CreatePostersRequestPoster) GetPaperSize() *string {
	if c == nil {
		return nil
	}
	return c.PaperSize
}

func (c *CreatePostersRequestPoster) GetPrimaryColor() *string {
	if c == nil {
		return nil
	}
	return c.PrimaryColor
}

func (c *CreatePostersRequestPoster) GetSecondaryColor() *string {
	if c == nil {
		return nil
	}
	return c.SecondaryColor
}

func (c *CreatePostersRequestPoster) GetTextColor() *string {
	if c == nil {
		return nil
	}
	return c.TextColor
}

func (c *CreatePostersRequestPoster) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *CreatePostersRequestPoster) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePostersRequestPoster) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetActive(active *bool) {
	c.Active = active
	c.require(createPostersRequestPosterFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetCardID(cardID int) {
	c.CardID = cardID
	c.require(createPostersRequestPosterFieldCardID)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetPaperSize(paperSize *string) {
	c.PaperSize = paperSize
	c.require(createPostersRequestPosterFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetPrimaryColor(primaryColor *string) {
	c.PrimaryColor = primaryColor
	c.require(createPostersRequestPosterFieldPrimaryColor)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetSecondaryColor(secondaryColor *string) {
	c.SecondaryColor = secondaryColor
	c.require(createPostersRequestPosterFieldSecondaryColor)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetTextColor(textColor *string) {
	c.TextColor = textColor
	c.require(createPostersRequestPosterFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersRequestPoster) SetTitle(title *string) {
	c.Title = title
	c.require(createPostersRequestPosterFieldTitle)
}

func (c *CreatePostersRequestPoster) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePostersRequestPoster
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePostersRequestPoster(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePostersRequestPoster) MarshalJSON() ([]byte, error) {
	type embed CreatePostersRequestPoster
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePostersRequestPoster) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createPostersResponseFieldAccountID      = big.NewInt(1 << 0)
	createPostersResponseFieldActive         = big.NewInt(1 << 1)
	createPostersResponseFieldCardID         = big.NewInt(1 << 2)
	createPostersResponseFieldCreatedAt      = big.NewInt(1 << 3)
	createPostersResponseFieldDisplayURL     = big.NewInt(1 << 4)
	createPostersResponseFieldID             = big.NewInt(1 << 5)
	createPostersResponseFieldPaperSize      = big.NewInt(1 << 6)
	createPostersResponseFieldPrimaryColor   = big.NewInt(1 << 7)
	createPostersResponseFieldQrCodeURL      = big.NewInt(1 << 8)
	createPostersResponseFieldSecondaryColor = big.NewInt(1 << 9)
	createPostersResponseFieldSignupURL      = big.NewInt(1 << 10)
	createPostersResponseFieldTextColor      = big.NewInt(1 << 11)
	createPostersResponseFieldTitle          = big.NewInt(1 << 12)
	createPostersResponseFieldUpdatedAt      = big.NewInt(1 << 13)
)

type CreatePostersResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePostersResponse) GetAccountID() int {
	if c == nil {
		return 0
	}
	return c.AccountID
}

func (c *CreatePostersResponse) GetActive() bool {
	if c == nil {
		return false
	}
	return c.Active
}

func (c *CreatePostersResponse) GetCardID() int {
	if c == nil {
		return 0
	}
	return c.CardID
}

func (c *CreatePostersResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreatePostersResponse) GetDisplayURL() string {
	if c == nil {
		return ""
	}
	return c.DisplayURL
}

func (c *CreatePostersResponse) GetID() int {
	if c == nil {
		return 0
	}
	return c.ID
}

func (c *CreatePostersResponse) GetPaperSize() string {
	if c == nil {
		return ""
	}
	return c.PaperSize
}

func (c *CreatePostersResponse) GetPrimaryColor() string {
	if c == nil {
		return ""
	}
	return c.PrimaryColor
}

func (c *CreatePostersResponse) GetQrCodeURL() string {
	if c == nil {
		return ""
	}
	return c.QrCodeURL
}

func (c *CreatePostersResponse) GetSecondaryColor() string {
	if c == nil {
		return ""
	}
	return c.SecondaryColor
}

func (c *CreatePostersResponse) GetSignupURL() string {
	if c == nil {
		return ""
	}
	return c.SignupURL
}

func (c *CreatePostersResponse) GetTextColor() string {
	if c == nil {
		return ""
	}
	return c.TextColor
}

func (c *CreatePostersResponse) GetTitle() string {
	if c == nil {
		return ""
	}
	return c.Title
}

func (c *CreatePostersResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreatePostersResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePostersResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetAccountID(accountID int) {
	c.AccountID = accountID
	c.require(createPostersResponseFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetActive(active bool) {
	c.Active = active
	c.require(createPostersResponseFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetCardID(cardID int) {
	c.CardID = cardID
	c.require(createPostersResponseFieldCardID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createPostersResponseFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetDisplayURL(displayURL string) {
	c.DisplayURL = displayURL
	c.require(createPostersResponseFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetID(id int) {
	c.ID = id
	c.require(createPostersResponseFieldID)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetPaperSize(paperSize string) {
	c.PaperSize = paperSize
	c.require(createPostersResponseFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetPrimaryColor(primaryColor string) {
	c.PrimaryColor = primaryColor
	c.require(createPostersResponseFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetQrCodeURL(qrCodeURL string) {
	c.QrCodeURL = qrCodeURL
	c.require(createPostersResponseFieldQrCodeURL)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetSecondaryColor(secondaryColor string) {
	c.SecondaryColor = secondaryColor
	c.require(createPostersResponseFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetSignupURL(signupURL string) {
	c.SignupURL = signupURL
	c.require(createPostersResponseFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetTextColor(textColor string) {
	c.TextColor = textColor
	c.require(createPostersResponseFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetTitle(title string) {
	c.Title = title
	c.require(createPostersResponseFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePostersResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createPostersResponseFieldUpdatedAt)
}

func (c *CreatePostersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePostersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePostersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePostersResponse) MarshalJSON() ([]byte, error) {
	type embed CreatePostersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePostersResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getPostersResponseFieldAccountID      = big.NewInt(1 << 0)
	getPostersResponseFieldActive         = big.NewInt(1 << 1)
	getPostersResponseFieldCardID         = big.NewInt(1 << 2)
	getPostersResponseFieldCreatedAt      = big.NewInt(1 << 3)
	getPostersResponseFieldDisplayURL     = big.NewInt(1 << 4)
	getPostersResponseFieldID             = big.NewInt(1 << 5)
	getPostersResponseFieldPaperSize      = big.NewInt(1 << 6)
	getPostersResponseFieldPrimaryColor   = big.NewInt(1 << 7)
	getPostersResponseFieldQrCodeURL      = big.NewInt(1 << 8)
	getPostersResponseFieldSecondaryColor = big.NewInt(1 << 9)
	getPostersResponseFieldSignupURL      = big.NewInt(1 << 10)
	getPostersResponseFieldTextColor      = big.NewInt(1 << 11)
	getPostersResponseFieldTitle          = big.NewInt(1 << 12)
	getPostersResponseFieldUpdatedAt      = big.NewInt(1 << 13)
)

type GetPostersResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPostersResponse) GetAccountID() int {
	if g == nil {
		return 0
	}
	return g.AccountID
}

func (g *GetPostersResponse) GetActive() bool {
	if g == nil {
		return false
	}
	return g.Active
}

func (g *GetPostersResponse) GetCardID() int {
	if g == nil {
		return 0
	}
	return g.CardID
}

func (g *GetPostersResponse) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetPostersResponse) GetDisplayURL() string {
	if g == nil {
		return ""
	}
	return g.DisplayURL
}

func (g *GetPostersResponse) GetID() int {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetPostersResponse) GetPaperSize() string {
	if g == nil {
		return ""
	}
	return g.PaperSize
}

func (g *GetPostersResponse) GetPrimaryColor() string {
	if g == nil {
		return ""
	}
	return g.PrimaryColor
}

func (g *GetPostersResponse) GetQrCodeURL() string {
	if g == nil {
		return ""
	}
	return g.QrCodeURL
}

func (g *GetPostersResponse) GetSecondaryColor() string {
	if g == nil {
		return ""
	}
	return g.SecondaryColor
}

func (g *GetPostersResponse) GetSignupURL() string {
	if g == nil {
		return ""
	}
	return g.SignupURL
}

func (g *GetPostersResponse) GetTextColor() string {
	if g == nil {
		return ""
	}
	return g.TextColor
}

func (g *GetPostersResponse) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GetPostersResponse) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetPostersResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetPostersResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetAccountID(accountID int) {
	g.AccountID = accountID
	g.require(getPostersResponseFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetActive(active bool) {
	g.Active = active
	g.require(getPostersResponseFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetCardID(cardID int) {
	g.CardID = cardID
	g.require(getPostersResponseFieldCardID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getPostersResponseFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetDisplayURL(displayURL string) {
	g.DisplayURL = displayURL
	g.require(getPostersResponseFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetID(id int) {
	g.ID = id
	g.require(getPostersResponseFieldID)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetPaperSize(paperSize string) {
	g.PaperSize = paperSize
	g.require(getPostersResponseFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetPrimaryColor(primaryColor string) {
	g.PrimaryColor = primaryColor
	g.require(getPostersResponseFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetQrCodeURL(qrCodeURL string) {
	g.QrCodeURL = qrCodeURL
	g.require(getPostersResponseFieldQrCodeURL)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetSecondaryColor(secondaryColor string) {
	g.SecondaryColor = secondaryColor
	g.require(getPostersResponseFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetSignupURL(signupURL string) {
	g.SignupURL = signupURL
	g.require(getPostersResponseFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetTextColor(textColor string) {
	g.TextColor = textColor
	g.require(getPostersResponseFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetTitle(title string) {
	g.Title = title
	g.require(getPostersResponseFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPostersResponse) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getPostersResponseFieldUpdatedAt)
}

func (g *GetPostersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPostersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPostersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPostersResponse) MarshalJSON() ([]byte, error) {
	type embed GetPostersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPostersResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listPostersResponseItemFieldAccountID      = big.NewInt(1 << 0)
	listPostersResponseItemFieldActive         = big.NewInt(1 << 1)
	listPostersResponseItemFieldCardID         = big.NewInt(1 << 2)
	listPostersResponseItemFieldCreatedAt      = big.NewInt(1 << 3)
	listPostersResponseItemFieldDisplayURL     = big.NewInt(1 << 4)
	listPostersResponseItemFieldID             = big.NewInt(1 << 5)
	listPostersResponseItemFieldPaperSize      = big.NewInt(1 << 6)
	listPostersResponseItemFieldPrimaryColor   = big.NewInt(1 << 7)
	listPostersResponseItemFieldQrCodeURL      = big.NewInt(1 << 8)
	listPostersResponseItemFieldSecondaryColor = big.NewInt(1 << 9)
	listPostersResponseItemFieldSignupURL      = big.NewInt(1 << 10)
	listPostersResponseItemFieldTextColor      = big.NewInt(1 << 11)
	listPostersResponseItemFieldTitle          = big.NewInt(1 << 12)
	listPostersResponseItemFieldUpdatedAt      = big.NewInt(1 << 13)
)

type ListPostersResponseItem struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPostersResponseItem) GetAccountID() int {
	if l == nil {
		return 0
	}
	return l.AccountID
}

func (l *ListPostersResponseItem) GetActive() bool {
	if l == nil {
		return false
	}
	return l.Active
}

func (l *ListPostersResponseItem) GetCardID() int {
	if l == nil {
		return 0
	}
	return l.CardID
}

func (l *ListPostersResponseItem) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListPostersResponseItem) GetDisplayURL() string {
	if l == nil {
		return ""
	}
	return l.DisplayURL
}

func (l *ListPostersResponseItem) GetID() int {
	if l == nil {
		return 0
	}
	return l.ID
}

func (l *ListPostersResponseItem) GetPaperSize() string {
	if l == nil {
		return ""
	}
	return l.PaperSize
}

func (l *ListPostersResponseItem) GetPrimaryColor() string {
	if l == nil {
		return ""
	}
	return l.PrimaryColor
}

func (l *ListPostersResponseItem) GetQrCodeURL() string {
	if l == nil {
		return ""
	}
	return l.QrCodeURL
}

func (l *ListPostersResponseItem) GetSecondaryColor() string {
	if l == nil {
		return ""
	}
	return l.SecondaryColor
}

func (l *ListPostersResponseItem) GetSignupURL() string {
	if l == nil {
		return ""
	}
	return l.SignupURL
}

func (l *ListPostersResponseItem) GetTextColor() string {
	if l == nil {
		return ""
	}
	return l.TextColor
}

func (l *ListPostersResponseItem) GetTitle() string {
	if l == nil {
		return ""
	}
	return l.Title
}

func (l *ListPostersResponseItem) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListPostersResponseItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListPostersResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetAccountID(accountID int) {
	l.AccountID = accountID
	l.require(listPostersResponseItemFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetActive(active bool) {
	l.Active = active
	l.require(listPostersResponseItemFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetCardID(cardID int) {
	l.CardID = cardID
	l.require(listPostersResponseItemFieldCardID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetCreatedAt(createdAt string) {
	l.CreatedAt = createdAt
	l.require(listPostersResponseItemFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetDisplayURL(displayURL string) {
	l.DisplayURL = displayURL
	l.require(listPostersResponseItemFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetID(id int) {
	l.ID = id
	l.require(listPostersResponseItemFieldID)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetPaperSize(paperSize string) {
	l.PaperSize = paperSize
	l.require(listPostersResponseItemFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetPrimaryColor(primaryColor string) {
	l.PrimaryColor = primaryColor
	l.require(listPostersResponseItemFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetQrCodeURL(qrCodeURL string) {
	l.QrCodeURL = qrCodeURL
	l.require(listPostersResponseItemFieldQrCodeURL)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetSecondaryColor(secondaryColor string) {
	l.SecondaryColor = secondaryColor
	l.require(listPostersResponseItemFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetSignupURL(signupURL string) {
	l.SignupURL = signupURL
	l.require(listPostersResponseItemFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetTextColor(textColor string) {
	l.TextColor = textColor
	l.require(listPostersResponseItemFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetTitle(title string) {
	l.Title = title
	l.require(listPostersResponseItemFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPostersResponseItem) SetUpdatedAt(updatedAt string) {
	l.UpdatedAt = updatedAt
	l.require(listPostersResponseItemFieldUpdatedAt)
}

func (l *ListPostersResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPostersResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPostersResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPostersResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListPostersResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPostersResponseItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	updatePostersRequestPosterFieldActive         = big.NewInt(1 << 0)
	updatePostersRequestPosterFieldPaperSize      = big.NewInt(1 << 1)
	updatePostersRequestPosterFieldPrimaryColor   = big.NewInt(1 << 2)
	updatePostersRequestPosterFieldSecondaryColor = big.NewInt(1 << 3)
	updatePostersRequestPosterFieldTextColor      = big.NewInt(1 << 4)
	updatePostersRequestPosterFieldTitle          = big.NewInt(1 << 5)
)

type UpdatePostersRequestPoster struct {
	// Whether the poster is active
	Active *bool `json:"active,omitempty" url:"active,omitempty"`
	// Print size – one of: a4, a5, a6, letter
	PaperSize *string `json:"paper_size,omitempty" url:"paper_size,omitempty"`
	// Primary brand color as a hex string
	PrimaryColor *string `json:"primary_color,omitempty" url:"primary_color,omitempty"`
	// Secondary brand color as a hex string
	SecondaryColor *string `json:"secondary_color,omitempty" url:"secondary_color,omitempty"`
	// Text color as a hex string
	TextColor *string `json:"text_color,omitempty" url:"text_color,omitempty"`
	// Headline text displayed on the poster
	Title *string `json:"title,omitempty" url:"title,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePostersRequestPoster) GetActive() *bool {
	if u == nil {
		return nil
	}
	return u.Active
}

func (u *UpdatePostersRequestPoster) GetPaperSize() *string {
	if u == nil {
		return nil
	}
	return u.PaperSize
}

func (u *UpdatePostersRequestPoster) GetPrimaryColor() *string {
	if u == nil {
		return nil
	}
	return u.PrimaryColor
}

func (u *UpdatePostersRequestPoster) GetSecondaryColor() *string {
	if u == nil {
		return nil
	}
	return u.SecondaryColor
}

func (u *UpdatePostersRequestPoster) GetTextColor() *string {
	if u == nil {
		return nil
	}
	return u.TextColor
}

func (u *UpdatePostersRequestPoster) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdatePostersRequestPoster) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePostersRequestPoster) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetActive(active *bool) {
	u.Active = active
	u.require(updatePostersRequestPosterFieldActive)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetPaperSize(paperSize *string) {
	u.PaperSize = paperSize
	u.require(updatePostersRequestPosterFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetPrimaryColor(primaryColor *string) {
	u.PrimaryColor = primaryColor
	u.require(updatePostersRequestPosterFieldPrimaryColor)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetSecondaryColor(secondaryColor *string) {
	u.SecondaryColor = secondaryColor
	u.require(updatePostersRequestPosterFieldSecondaryColor)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetTextColor(textColor *string) {
	u.TextColor = textColor
	u.require(updatePostersRequestPosterFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequestPoster) SetTitle(title *string) {
	u.Title = title
	u.require(updatePostersRequestPosterFieldTitle)
}

func (u *UpdatePostersRequestPoster) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePostersRequestPoster
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePostersRequestPoster(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePostersRequestPoster) MarshalJSON() ([]byte, error) {
	type embed UpdatePostersRequestPoster
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePostersRequestPoster) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updatePostersResponseFieldAccountID      = big.NewInt(1 << 0)
	updatePostersResponseFieldActive         = big.NewInt(1 << 1)
	updatePostersResponseFieldCardID         = big.NewInt(1 << 2)
	updatePostersResponseFieldCreatedAt      = big.NewInt(1 << 3)
	updatePostersResponseFieldDisplayURL     = big.NewInt(1 << 4)
	updatePostersResponseFieldID             = big.NewInt(1 << 5)
	updatePostersResponseFieldPaperSize      = big.NewInt(1 << 6)
	updatePostersResponseFieldPrimaryColor   = big.NewInt(1 << 7)
	updatePostersResponseFieldQrCodeURL      = big.NewInt(1 << 8)
	updatePostersResponseFieldSecondaryColor = big.NewInt(1 << 9)
	updatePostersResponseFieldSignupURL      = big.NewInt(1 << 10)
	updatePostersResponseFieldTextColor      = big.NewInt(1 << 11)
	updatePostersResponseFieldTitle          = big.NewInt(1 << 12)
	updatePostersResponseFieldUpdatedAt      = big.NewInt(1 << 13)
)

type UpdatePostersResponse struct {
	// Parent store ID
	AccountID int `json:"account_id" url:"account_id"`
	// Whether the public signup URL is live
	Active bool `json:"active" url:"active"`
	// Loyalty card customers are signed up to
	CardID int `json:"card_id" url:"card_id"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at" url:"created_at"`
	// URL of the on screen version of the poster
	DisplayURL string `json:"display_url" url:"display_url"`
	// Unique poster ID
	ID int `json:"id" url:"id"`
	// Paper size the poster is laid out for
	PaperSize string `json:"paper_size" url:"paper_size"`
	// Hex colour for the poster background
	PrimaryColor string `json:"primary_color" url:"primary_color"`
	// URL encoded in the QR code
	QrCodeURL string `json:"qr_code_url" url:"qr_code_url"`
	// Hex accent colour
	SecondaryColor string `json:"secondary_color" url:"secondary_color"`
	// Public URL the QR code points at
	SignupURL string `json:"signup_url" url:"signup_url"`
	// Hex colour for poster text
	TextColor string `json:"text_color" url:"text_color"`
	// Heading printed on the poster
	Title string `json:"title" url:"title"`
	// ISO 8601 last-update timestamp
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePostersResponse) GetAccountID() int {
	if u == nil {
		return 0
	}
	return u.AccountID
}

func (u *UpdatePostersResponse) GetActive() bool {
	if u == nil {
		return false
	}
	return u.Active
}

func (u *UpdatePostersResponse) GetCardID() int {
	if u == nil {
		return 0
	}
	return u.CardID
}

func (u *UpdatePostersResponse) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdatePostersResponse) GetDisplayURL() string {
	if u == nil {
		return ""
	}
	return u.DisplayURL
}

func (u *UpdatePostersResponse) GetID() int {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdatePostersResponse) GetPaperSize() string {
	if u == nil {
		return ""
	}
	return u.PaperSize
}

func (u *UpdatePostersResponse) GetPrimaryColor() string {
	if u == nil {
		return ""
	}
	return u.PrimaryColor
}

func (u *UpdatePostersResponse) GetQrCodeURL() string {
	if u == nil {
		return ""
	}
	return u.QrCodeURL
}

func (u *UpdatePostersResponse) GetSecondaryColor() string {
	if u == nil {
		return ""
	}
	return u.SecondaryColor
}

func (u *UpdatePostersResponse) GetSignupURL() string {
	if u == nil {
		return ""
	}
	return u.SignupURL
}

func (u *UpdatePostersResponse) GetTextColor() string {
	if u == nil {
		return ""
	}
	return u.TextColor
}

func (u *UpdatePostersResponse) GetTitle() string {
	if u == nil {
		return ""
	}
	return u.Title
}

func (u *UpdatePostersResponse) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdatePostersResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePostersResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updatePostersResponseFieldAccountID)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetActive(active bool) {
	u.Active = active
	u.require(updatePostersResponseFieldActive)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetCardID(cardID int) {
	u.CardID = cardID
	u.require(updatePostersResponseFieldCardID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updatePostersResponseFieldCreatedAt)
}

// SetDisplayURL sets the DisplayURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetDisplayURL(displayURL string) {
	u.DisplayURL = displayURL
	u.require(updatePostersResponseFieldDisplayURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetID(id int) {
	u.ID = id
	u.require(updatePostersResponseFieldID)
}

// SetPaperSize sets the PaperSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetPaperSize(paperSize string) {
	u.PaperSize = paperSize
	u.require(updatePostersResponseFieldPaperSize)
}

// SetPrimaryColor sets the PrimaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetPrimaryColor(primaryColor string) {
	u.PrimaryColor = primaryColor
	u.require(updatePostersResponseFieldPrimaryColor)
}

// SetQrCodeURL sets the QrCodeURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetQrCodeURL(qrCodeURL string) {
	u.QrCodeURL = qrCodeURL
	u.require(updatePostersResponseFieldQrCodeURL)
}

// SetSecondaryColor sets the SecondaryColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetSecondaryColor(secondaryColor string) {
	u.SecondaryColor = secondaryColor
	u.require(updatePostersResponseFieldSecondaryColor)
}

// SetSignupURL sets the SignupURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetSignupURL(signupURL string) {
	u.SignupURL = signupURL
	u.require(updatePostersResponseFieldSignupURL)
}

// SetTextColor sets the TextColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetTextColor(textColor string) {
	u.TextColor = textColor
	u.require(updatePostersResponseFieldTextColor)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetTitle(title string) {
	u.Title = title
	u.require(updatePostersResponseFieldTitle)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersResponse) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updatePostersResponseFieldUpdatedAt)
}

func (u *UpdatePostersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePostersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePostersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePostersResponse) MarshalJSON() ([]byte, error) {
	type embed UpdatePostersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePostersResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updatePostersRequestFieldAccountID = big.NewInt(1 << 0)
	updatePostersRequestFieldID        = big.NewInt(1 << 1)
	updatePostersRequestFieldPoster    = big.NewInt(1 << 2)
)

type UpdatePostersRequest struct {
	// Store (account) ID
	AccountID int `json:"-" url:"-"`
	// Poster ID
	ID     int                         `json:"-" url:"-"`
	Poster *UpdatePostersRequestPoster `json:"poster" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdatePostersRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequest) SetAccountID(accountID int) {
	u.AccountID = accountID
	u.require(updatePostersRequestFieldAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequest) SetID(id int) {
	u.ID = id
	u.require(updatePostersRequestFieldID)
}

// SetPoster sets the Poster field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePostersRequest) SetPoster(poster *UpdatePostersRequestPoster) {
	u.Poster = poster
	u.require(updatePostersRequestFieldPoster)
}

func (u *UpdatePostersRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePostersRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdatePostersRequest(body)
	return nil
}

func (u *UpdatePostersRequest) MarshalJSON() ([]byte, error) {
	type embed UpdatePostersRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
