// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

var (
	checkStatusResponseFieldAPIVersion         = big.NewInt(1 << 0)
	checkStatusResponseFieldAuthentication     = big.NewInt(1 << 1)
	checkStatusResponseFieldDeveloperPortalURL = big.NewInt(1 << 2)
	checkStatusResponseFieldDocumentationURL   = big.NewInt(1 << 3)
	checkStatusResponseFieldOpenapiURL         = big.NewInt(1 << 4)
	checkStatusResponseFieldRateLimit          = big.NewInt(1 << 5)
	checkStatusResponseFieldStatus             = big.NewInt(1 << 6)
)

type CheckStatusResponse struct {
	// Current API version
	APIVersion string `json:"api_version" url:"api_version"`
	// How to authenticate a request
	Authentication string `json:"authentication" url:"authentication"`
	// Developer portal: quickstart, auth, webhooks
	DeveloperPortalURL string `json:"developer_portal_url" url:"developer_portal_url"`
	// Human readable API reference
	DocumentationURL string `json:"documentation_url" url:"documentation_url"`
	// OpenAPI description of this API
	OpenapiURL string                        `json:"openapi_url" url:"openapi_url"`
	RateLimit  *CheckStatusResponseRateLimit `json:"rate_limit" url:"rate_limit"`
	// 'ok' while the API is serving requests
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CheckStatusResponse) GetAPIVersion() string {
	if c == nil {
		return ""
	}
	return c.APIVersion
}

func (c *CheckStatusResponse) GetAuthentication() string {
	if c == nil {
		return ""
	}
	return c.Authentication
}

func (c *CheckStatusResponse) GetDeveloperPortalURL() string {
	if c == nil {
		return ""
	}
	return c.DeveloperPortalURL
}

func (c *CheckStatusResponse) GetDocumentationURL() string {
	if c == nil {
		return ""
	}
	return c.DocumentationURL
}

func (c *CheckStatusResponse) GetOpenapiURL() string {
	if c == nil {
		return ""
	}
	return c.OpenapiURL
}

func (c *CheckStatusResponse) GetRateLimit() *CheckStatusResponseRateLimit {
	if c == nil {
		return nil
	}
	return c.RateLimit
}

func (c *CheckStatusResponse) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CheckStatusResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CheckStatusResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAPIVersion sets the APIVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetAPIVersion(apiVersion string) {
	c.APIVersion = apiVersion
	c.require(checkStatusResponseFieldAPIVersion)
}

// SetAuthentication sets the Authentication field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetAuthentication(authentication string) {
	c.Authentication = authentication
	c.require(checkStatusResponseFieldAuthentication)
}

// SetDeveloperPortalURL sets the DeveloperPortalURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetDeveloperPortalURL(developerPortalURL string) {
	c.DeveloperPortalURL = developerPortalURL
	c.require(checkStatusResponseFieldDeveloperPortalURL)
}

// SetDocumentationURL sets the DocumentationURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetDocumentationURL(documentationURL string) {
	c.DocumentationURL = documentationURL
	c.require(checkStatusResponseFieldDocumentationURL)
}

// SetOpenapiURL sets the OpenapiURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetOpenapiURL(openapiURL string) {
	c.OpenapiURL = openapiURL
	c.require(checkStatusResponseFieldOpenapiURL)
}

// SetRateLimit sets the RateLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetRateLimit(rateLimit *CheckStatusResponseRateLimit) {
	c.RateLimit = rateLimit
	c.require(checkStatusResponseFieldRateLimit)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponse) SetStatus(status string) {
	c.Status = status
	c.require(checkStatusResponseFieldStatus)
}

func (c *CheckStatusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckStatusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckStatusResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckStatusResponse) MarshalJSON() ([]byte, error) {
	type embed CheckStatusResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CheckStatusResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	checkStatusResponseRateLimitFieldLimit         = big.NewInt(1 << 0)
	checkStatusResponseRateLimitFieldScope         = big.NewInt(1 << 1)
	checkStatusResponseRateLimitFieldWindowSeconds = big.NewInt(1 << 2)
)

type CheckStatusResponseRateLimit struct {
	// Requests allowed per window
	Limit int `json:"limit" url:"limit"`
	// What the limit is counted against
	Scope string `json:"scope" url:"scope"`
	// Length of the window in seconds
	WindowSeconds int `json:"window_seconds" url:"window_seconds"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CheckStatusResponseRateLimit) GetLimit() int {
	if c == nil {
		return 0
	}
	return c.Limit
}

func (c *CheckStatusResponseRateLimit) GetScope() string {
	if c == nil {
		return ""
	}
	return c.Scope
}

func (c *CheckStatusResponseRateLimit) GetWindowSeconds() int {
	if c == nil {
		return 0
	}
	return c.WindowSeconds
}

func (c *CheckStatusResponseRateLimit) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CheckStatusResponseRateLimit) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponseRateLimit) SetLimit(limit int) {
	c.Limit = limit
	c.require(checkStatusResponseRateLimitFieldLimit)
}

// SetScope sets the Scope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponseRateLimit) SetScope(scope string) {
	c.Scope = scope
	c.require(checkStatusResponseRateLimitFieldScope)
}

// SetWindowSeconds sets the WindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CheckStatusResponseRateLimit) SetWindowSeconds(windowSeconds int) {
	c.WindowSeconds = windowSeconds
	c.require(checkStatusResponseRateLimitFieldWindowSeconds)
}

func (c *CheckStatusResponseRateLimit) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckStatusResponseRateLimit
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckStatusResponseRateLimit(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckStatusResponseRateLimit) MarshalJSON() ([]byte, error) {
	type embed CheckStatusResponseRateLimit
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CheckStatusResponseRateLimit) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
