// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCheckStatusResponse(t *testing.T) {
	t.Run("SetAPIVersion", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueAPIVersion string
		obj.SetAPIVersion(fernTestValueAPIVersion)
		assert.Equal(t, fernTestValueAPIVersion, obj.APIVersion)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAuthentication", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueAuthentication string
		obj.SetAuthentication(fernTestValueAuthentication)
		assert.Equal(t, fernTestValueAuthentication, obj.Authentication)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDeveloperPortalURL", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueDeveloperPortalURL string
		obj.SetDeveloperPortalURL(fernTestValueDeveloperPortalURL)
		assert.Equal(t, fernTestValueDeveloperPortalURL, obj.DeveloperPortalURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocumentationURL", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueDocumentationURL string
		obj.SetDocumentationURL(fernTestValueDocumentationURL)
		assert.Equal(t, fernTestValueDocumentationURL, obj.DocumentationURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOpenapiURL", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueOpenapiURL string
		obj.SetOpenapiURL(fernTestValueOpenapiURL)
		assert.Equal(t, fernTestValueOpenapiURL, obj.OpenapiURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRateLimit", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueRateLimit *CheckStatusResponseRateLimit
		obj.SetRateLimit(fernTestValueRateLimit)
		assert.Equal(t, fernTestValueRateLimit, obj.RateLimit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &CheckStatusResponse{}
		var fernTestValueStatus string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCheckStatusResponse(t *testing.T) {
	t.Run("GetAPIVersion", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected string
		obj.APIVersion = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAPIVersion(), "getter should return the property value")
	})

	t.Run("GetAPIVersion_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAPIVersion() // Should return zero value
	})

	t.Run("GetAuthentication", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected string
		obj.Authentication = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAuthentication(), "getter should return the property value")
	})

	t.Run("GetAuthentication_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAuthentication() // Should return zero value
	})

	t.Run("GetDeveloperPortalURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected string
		obj.DeveloperPortalURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDeveloperPortalURL(), "getter should return the property value")
	})

	t.Run("GetDeveloperPortalURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDeveloperPortalURL() // Should return zero value
	})

	t.Run("GetDocumentationURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected string
		obj.DocumentationURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDocumentationURL(), "getter should return the property value")
	})

	t.Run("GetDocumentationURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDocumentationURL() // Should return zero value
	})

	t.Run("GetOpenapiURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected string
		obj.OpenapiURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOpenapiURL(), "getter should return the property value")
	})

	t.Run("GetOpenapiURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOpenapiURL() // Should return zero value
	})

	t.Run("GetRateLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected *CheckStatusResponseRateLimit
		obj.RateLimit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRateLimit(), "getter should return the property value")
	})

	t.Run("GetRateLimit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		obj.RateLimit = nil

		// Act & Assert
		assert.Nil(t, obj.GetRateLimit(), "getter should return nil when property is nil")
	})

	t.Run("GetRateLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRateLimit() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var expected string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

}

func TestSettersMarkExplicitCheckStatusResponse(t *testing.T) {
	t.Run("SetAPIVersion_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueAPIVersion string

		// Act
		obj.SetAPIVersion(fernTestValueAPIVersion)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAuthentication_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueAuthentication string

		// Act
		obj.SetAuthentication(fernTestValueAuthentication)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDeveloperPortalURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueDeveloperPortalURL string

		// Act
		obj.SetDeveloperPortalURL(fernTestValueDeveloperPortalURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocumentationURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueDocumentationURL string

		// Act
		obj.SetDocumentationURL(fernTestValueDocumentationURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOpenapiURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueOpenapiURL string

		// Act
		obj.SetOpenapiURL(fernTestValueOpenapiURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRateLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueRateLimit *CheckStatusResponseRateLimit

		// Act
		obj.SetRateLimit(fernTestValueRateLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}
		var fernTestValueStatus string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCheckStatusResponseRateLimit(t *testing.T) {
	t.Run("SetLimit", func(t *testing.T) {
		obj := &CheckStatusResponseRateLimit{}
		var fernTestValueLimit int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetScope", func(t *testing.T) {
		obj := &CheckStatusResponseRateLimit{}
		var fernTestValueScope string
		obj.SetScope(fernTestValueScope)
		assert.Equal(t, fernTestValueScope, obj.Scope)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWindowSeconds", func(t *testing.T) {
		obj := &CheckStatusResponseRateLimit{}
		var fernTestValueWindowSeconds int
		obj.SetWindowSeconds(fernTestValueWindowSeconds)
		assert.Equal(t, fernTestValueWindowSeconds, obj.WindowSeconds)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCheckStatusResponseRateLimit(t *testing.T) {
	t.Run("GetLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}
		var expected int
		obj.Limit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLimit(), "getter should return the property value")
	})

	t.Run("GetLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponseRateLimit
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLimit() // Should return zero value
	})

	t.Run("GetScope", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}
		var expected string
		obj.Scope = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetScope(), "getter should return the property value")
	})

	t.Run("GetScope_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponseRateLimit
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetScope() // Should return zero value
	})

	t.Run("GetWindowSeconds", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}
		var expected int
		obj.WindowSeconds = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWindowSeconds(), "getter should return the property value")
	})

	t.Run("GetWindowSeconds_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponseRateLimit
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWindowSeconds() // Should return zero value
	})

}

func TestSettersMarkExplicitCheckStatusResponseRateLimit(t *testing.T) {
	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}
		var fernTestValueLimit int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetScope_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}
		var fernTestValueScope string

		// Act
		obj.SetScope(fernTestValueScope)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWindowSeconds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}
		var fernTestValueWindowSeconds int

		// Act
		obj.SetWindowSeconds(fernTestValueWindowSeconds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCheckStatusResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CheckStatusResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CheckStatusResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CheckStatusResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCheckStatusResponseRateLimit(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckStatusResponseRateLimit{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CheckStatusResponseRateLimit
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CheckStatusResponseRateLimit
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CheckStatusResponseRateLimit
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCheckStatusResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CheckStatusResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCheckStatusResponseRateLimit(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CheckStatusResponseRateLimit{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponseRateLimit
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesCheckStatusResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CheckStatusResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCheckStatusResponseRateLimit(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CheckStatusResponseRateLimit{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckStatusResponseRateLimit
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
