// Code generated by Fern. DO NOT EDIT.

package leal

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lealhq/leal-go-sdk/internal"
	big "math/big"
)

// A JSON error payload. Agents should read `error` for a human readable summary and `errors` for per field validation messages when present.
var (
	errorFieldError  = big.NewInt(1 << 0)
	errorFieldErrors = big.NewInt(1 << 1)
)

type Error struct {
	// Human readable description of what went wrong.
	Error *string `json:"error,omitempty" url:"error,omitempty"`
	// Validation messages, either a list of strings or an object keyed by field name.
	Errors *ErrorErrors `json:"errors,omitempty" url:"errors,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (e *Error) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *Error) GetErrors() *ErrorErrors {
	if e == nil {
		return nil
	}
	return e.Errors
}

func (e *Error) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.ExtraProperties
}

func (e *Error) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Error) SetError(error_ *string) {
	e.Error = error_
	e.require(errorFieldError)
}

// SetErrors sets the Errors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Error) SetErrors(errors *ErrorErrors) {
	e.Errors = errors
	e.require(errorFieldErrors)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	type embed Error
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = Error(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.ExtraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Error) MarshalJSON() ([]byte, error) {
	type embed Error
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, e.ExtraProperties)
}

func (e *Error) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Validation messages, either a list of strings or an object keyed by field name.
type ErrorErrors struct {
	StringList          []string
	StringStringListMap map[string][]string

	typ string
}

func (e *ErrorErrors) GetStringList() []string {
	if e == nil {
		return nil
	}
	return e.StringList
}

func (e *ErrorErrors) GetStringStringListMap() map[string][]string {
	if e == nil {
		return nil
	}
	return e.StringStringListMap
}

func (e *ErrorErrors) UnmarshalJSON(data []byte) error {
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		e.typ = "StringList"
		e.StringList = valueStringList
		return nil
	}
	var valueStringStringListMap map[string][]string
	if err := json.Unmarshal(data, &valueStringStringListMap); err == nil {
		e.typ = "StringStringListMap"
		e.StringStringListMap = valueStringStringListMap
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, e)
}

func (e ErrorErrors) MarshalJSON() ([]byte, error) {
	if e.typ == "StringList" || e.StringList != nil {
		return json.Marshal(e.StringList)
	}
	if e.typ == "StringStringListMap" || e.StringStringListMap != nil {
		return json.Marshal(e.StringStringListMap)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", e)
}

type ErrorErrorsVisitor interface {
	VisitStringList([]string) error
	VisitStringStringListMap(map[string][]string) error
}

func (e *ErrorErrors) Accept(visitor ErrorErrorsVisitor) error {
	if e.typ == "StringList" || e.StringList != nil {
		return visitor.VisitStringList(e.StringList)
	}
	if e.typ == "StringStringListMap" || e.StringStringListMap != nil {
		return visitor.VisitStringStringListMap(e.StringStringListMap)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", e)
}
