// Code generated by Fern. DO NOT EDIT.

package customercards

import (
	context "context"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns all loyalty cards enrolled for a specific customer, including stamp progress,
// status, wallet pass installation state, and wallet pass URLs (`apple_wallet_url` and
// `google_wallet_url`) that you can use to let customers add their loyalty card to
// Apple Wallet or Google Wallet from your own app or website.
//
// Example:
//
//	request := &leal.ListCustomerCardsRequest{
//	    AccountID: 1,
//	    CustomerID: 1,
//	}
//	client.CustomerCards.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *leal.ListCustomerCardsRequest,
	opts ...option.RequestOption,
) ([]*leal.ListCustomerCardsResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns detailed information about a specific customer card, including stamp progress,
// a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
// (`apple_wallet_url` and `google_wallet_url`) for adding the card to Apple Wallet or
// Google Wallet.
//
// Example:
//
//	request := &leal.GetCustomerCardsRequest{
//	    AccountID: 1,
//	    CustomerID: 1,
//	    ID: 1,
//	}
//	client.CustomerCards.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *leal.GetCustomerCardsRequest,
	opts ...option.RequestOption,
) (*leal.GetCustomerCardsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Redeems a reward for a customer, deducting the required stamps from their card.
// The customer must have enough stamps on this card to cover the reward's cost.
// Triggers wallet pass updates and push notifications.
//
// Example:
//
//	request := &leal.RedeemCustomerCardsRequest{
//	    AccountID: 1,
//	    CustomerID: 1,
//	    ID: 1,
//	    RewardID: 1,
//	}
//	client.CustomerCards.Redeem(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Redeem(
	ctx context.Context,
	request *leal.RedeemCustomerCardsRequest,
	opts ...option.RequestOption,
) (*leal.RedeemCustomerCardsResponse, error) {
	response, err := c.WithRawResponse.Redeem(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Adds stamps to a customer's loyalty card. Triggers ledger entries, wallet pass updates,
// and push notifications. Pass `skip_notifications` to stamp silently.
//
// Example:
//
//	request := &leal.StampCustomerCardsRequest{
//	    AccountID: 1,
//	    CustomerID: 1,
//	    ID: 1,
//	    Stamps: 1,
//	}
//	client.CustomerCards.Stamp(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Stamp(
	ctx context.Context,
	request *leal.StampCustomerCardsRequest,
	opts ...option.RequestOption,
) (*leal.StampCustomerCardsResponse, error) {
	response, err := c.WithRawResponse.Stamp(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
