// Code generated by Fern. DO NOT EDIT.

// Customer cards represent a customer's instance of a loyalty card template. They track
// stamp progress, status, and wallet pass installation. Use these endpoints to view a
// customer's enrolled loyalty cards and their current progress toward rewards.
package customercards
