// Code generated by Fern. DO NOT EDIT.

// Cards are loyalty stamp card templates that define the look, feel, and rules
// for a store's loyalty program. Each card specifies how many stamps are required,
// which icon to use, the colour scheme, and the strip image style.
//
// Customers receive individual instances of a card (CustomerCards) and collect
// stamps toward rewards. A store may have multiple active card templates
// (e.g. a coffee card and a haircut card).
//
// Cards can be archived to hide them from the default listing without deleting
// historical data. Use the `scope` query parameter on the index endpoint to
// control which cards are returned.
//
// All card endpoints are scoped to a store via the `:account_id` URL parameter.
package cards
