// Code generated by Fern. DO NOT EDIT.

// Customers represent the people who visit your store and participate in your loyalty program.
// Each customer requires a `first_name` and at least one of `email` or `phone`. Both `email`
// and `phone` are unique within a store. Customers can be enrolled in loyalty cards and have
// their stamp counts managed through this API.
//
// # External references and metadata
//
// Every customer can carry two kinds of integration-friendly data so you can match them up with
// records in other systems (Square, Shopify, Mailchimp, your own POS, etc.) without depending on
// email or phone:
//
// `external_references`: a list of `source`/`external_id` pairs. `source` is a free-form
// lowercase slug that identifies the foreign system (e.g. `square`, `shopify`,
// `mailchimp`, `hubspot`, or anything custom like `my_pos`). Each
// `source`/`external_id` pair is unique per store, indexed for fast lookups, and can be used
// to find or upsert a customer.
//
// `metadata`: a free-form JSON object for any other per-customer data you want to attach
// (preferred drink, segment tags, "last seen at counter", etc.). Not indexed; not unique;
// merged on update.
//
// Use `GET /customers?source=...&external_id=...` to look up a customer by an external
// reference.
package customers
