// Code generated by Fern. DO NOT EDIT.

package stores

import (
	context "context"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.
//
// Example:
//
//	client.Stores.List(
//	    context.TODO(),
//	)
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*leal.ListStoresResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns detailed information for a single store, including summary counts for its associated resources.
//
// Example:
//
//	request := &leal.GetStoresRequest{
//	    ID: 1,
//	}
//	client.Stores.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *leal.GetStoresRequest,
	opts ...option.RequestOption,
) (*leal.GetStoresResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the store's name or store_name. Use `store_name` for the public-facing name displayed to customers.
//
// Example:
//
//	request := &leal.UpdateStoresRequest{
//	    ID: 1,
//	    Account: &leal.UpdateStoresRequestAccount{},
//	}
//	client.Stores.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *leal.UpdateStoresRequest,
	opts ...option.RequestOption,
) (*leal.UpdateStoresResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
