// Code generated by Fern. DO NOT EDIT.

// In this API, every Account represents a Store. Stores are the top-level tenant
// object that owns locations, loyalty cards, customers, and posters.
//
// Each authenticated user may belong to one or more stores. Use these endpoints
// to list the stores you have access to, view store details (including summary
// counts), and update store settings.
package stores
