// Code generated by Fern. DO NOT EDIT.

package rewards

import (
	context "context"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns all rewards for the store. Optionally filter by card or active status.
//
// Example:
//
//	request := &leal.ListRewardsRequest{
//	    AccountID: 1,
//	}
//	client.Rewards.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *leal.ListRewardsRequest,
	opts ...option.RequestOption,
) ([]*leal.ListRewardsResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new reward for a loyalty card. The card must belong to the same store.
// The `card_id` is required on create but cannot be changed afterwards.
//
// Example:
//
//	request := &leal.CreateRewardsRequest{
//	    AccountID: 1,
//	    Reward: &leal.CreateRewardsRequestReward{
//	        CardID: 1,
//	        Name: "name",
//	        StampsRequired: 1,
//	    },
//	}
//	client.Rewards.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *leal.CreateRewardsRequest,
	opts ...option.RequestOption,
) (*leal.CreateRewardsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single reward by ID.
//
// Example:
//
//	request := &leal.GetRewardsRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.Rewards.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *leal.GetRewardsRequest,
	opts ...option.RequestOption,
) (*leal.GetRewardsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently deletes a reward. This cannot be undone.
//
// Example:
//
//	request := &leal.DeleteRewardsRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.Rewards.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *leal.DeleteRewardsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Updates an existing reward. The `card_id` cannot be changed after creation.
//
// Example:
//
//	request := &leal.UpdateRewardsRequest{
//	    AccountID: 1,
//	    ID: 1,
//	    Reward: &leal.UpdateRewardsRequestReward{},
//	}
//	client.Rewards.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *leal.UpdateRewardsRequest,
	opts ...option.RequestOption,
) (*leal.UpdateRewardsResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
