// Code generated by Fern. DO NOT EDIT.

// Rewards are redeemable milestones tied to a loyalty card. When a customer reaches the
// required number of stamps, they become eligible to redeem the reward. Each reward belongs
// to a specific card.
package rewards
