// Code generated by Fern. DO NOT EDIT.

package status

import (
	context "context"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the status of the API. No authentication required.
//
// Every response from this API, including this one, carries `RateLimit-Limit`,
// `RateLimit-Remaining`, `RateLimit-Reset` and `RateLimit-Policy`. Exceeding
// the limit returns 429 with `Retry-After` in seconds.
//
// Example:
//
//	client.Status.Check(
//	    context.TODO(),
//	)
func (c *Client) Check(
	ctx context.Context,
	opts ...option.RequestOption,
) (*leal.CheckStatusResponse, error) {
	response, err := c.WithRawResponse.Check(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
