// Code generated by Fern. DO NOT EDIT.

// A single unauthenticated endpoint. Use it to check that the API is
// reachable, to discover the documentation and the OpenAPI description, and
// to read the rate limit headers before you start making authenticated
// calls.
package status
