// Code generated by Fern. DO NOT EDIT.

package webhooksubscriptions

import (
	context "context"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns every webhook subscription for the store, oldest first. Signing secrets are not included; fetch a single subscription to read its secret.
//
// Example:
//
//	request := &leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsRequest{
//	    AccountID: 1,
//	}
//	client.WebhookSubscriptions.GetAPIV1AccountsAccountIDWebhookSubscriptions(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetAPIV1AccountsAccountIDWebhookSubscriptions(
	ctx context.Context,
	request *leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsRequest,
	opts ...option.RequestOption,
) ([]*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsResponseItem, error) {
	response, err := c.WithRawResponse.GetAPIV1AccountsAccountIDWebhookSubscriptions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Subscribes a URL to one or more events. The response includes the signing `secret`; store it to
// verify deliveries. The URL must be publicly reachable over https.
//
// Events: `customer.created`, `customer.updated`, `customer_card.created`, `stamp.earned`, `stamp.removed`, `reward.unlocked`, `reward.redeemed`, or `*` for all of them.
//
// Example:
//
//	request := &leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsRequest{
//	    AccountID: 1,
//	    TargetURL: "target_url",
//	}
//	client.WebhookSubscriptions.PostAPIV1AccountsAccountIDWebhookSubscriptions(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PostAPIV1AccountsAccountIDWebhookSubscriptions(
	ctx context.Context,
	request *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsRequest,
	opts ...option.RequestOption,
) (*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsResponse, error) {
	response, err := c.WithRawResponse.PostAPIV1AccountsAccountIDWebhookSubscriptions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single subscription, including its signing secret and the result of the most recent delivery.
//
// Example:
//
//	request := &leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.WebhookSubscriptions.GetAPIV1AccountsAccountIDWebhookSubscriptionsID(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetAPIV1AccountsAccountIDWebhookSubscriptionsID(
	ctx context.Context,
	request *leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest,
	opts ...option.RequestOption,
) (*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse, error) {
	response, err := c.WithRawResponse.GetAPIV1AccountsAccountIDWebhookSubscriptionsID(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Stops deliveries and deletes the subscription. This cannot be undone.
//
// Example:
//
//	request := &leal.DeleteAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.WebhookSubscriptions.DeleteAPIV1AccountsAccountIDWebhookSubscriptionsID(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteAPIV1AccountsAccountIDWebhookSubscriptionsID(
	ctx context.Context,
	request *leal.DeleteAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteAPIV1AccountsAccountIDWebhookSubscriptionsID(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Changes the URL, events, label or payload format, or turns the subscription off and on. Re-enabling a subscription that was disabled for failing clears its failure state.
//
// Example:
//
//	request := &leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.WebhookSubscriptions.PatchAPIV1AccountsAccountIDWebhookSubscriptionsID(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PatchAPIV1AccountsAccountIDWebhookSubscriptionsID(
	ctx context.Context,
	request *leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest,
	opts ...option.RequestOption,
) (*leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse, error) {
	response, err := c.WithRawResponse.PatchAPIV1AccountsAccountIDWebhookSubscriptionsID(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Replaces the subscription's signing secret. Deliveries are signed with the new secret straight away, so update your receiver at the same time.
//
// Example:
//
//	request := &leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.WebhookSubscriptions.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecret(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecret(
	ctx context.Context,
	request *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretRequest,
	opts ...option.RequestOption,
) (*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretResponse, error) {
	response, err := c.WithRawResponse.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecret(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Immediately sends a signed `webhook.test` event to the subscription's URL and reports what
// happened, so you can check your endpoint and signature verification without waiting for real
// activity. Test events are not retried and do not count towards disabling the subscription.
//
// Example:
//
//	request := &leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.WebhookSubscriptions.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTest(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTest(
	ctx context.Context,
	request *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestRequest,
	opts ...option.RequestOption,
) (*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestResponse, error) {
	response, err := c.WithRawResponse.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
