// Code generated by Fern. DO NOT EDIT.

// A webhook subscription tells Leal to POST a JSON payload to your URL whenever an event
// happens in the store, so you don't have to poll. Subscribe to a list of `events`, or to
// `["*"]` for every event (including ones added later). The full guide, with payload examples and
// signature verification code, is at https://www.getleal.com/developers/webhooks.
//
// # Events
//
// - `customer.created`: A customer joined the loyalty program.
// - `customer.updated`: A customer's name, email, phone, birthday, metadata or marketing and SMS consent changed.
// - `customer_card.created`: A customer was issued a loyalty card. Includes the Apple Wallet and Google Wallet links.
// - `stamp.earned`: Stamps were added to a customer's card, from a scan, the API or an adjustment.
// - `stamp.removed`: Stamps were taken off a customer's card by an adjustment. Redeeming a reward sends reward.redeemed instead.
// - `reward.unlocked`: A customer now has enough stamps to redeem a reward. Sent once per reward, when the threshold is crossed.
// - `reward.redeemed`: A customer redeemed a reward.
//
// # Payload
//
// Each delivery is an envelope: `{"id": "evt_...", "type": "stamp.earned", "timestamp": "...",
// "account_id": 1, "data": {...}}`. `id` is unique per event and stays the same across
// retries, so use it to ignore duplicates. `customer.updated` also carries
// `previous_attributes` with the old values of the fields that changed.
//
// Subscriptions created from Zapier (and all subscriptions created before signing was
// introduced) use `payload_format: "flat"`, which sends the `data` object on its own. The
// event name is still available in the `Leal-Event` header. A flat subscription has exactly
// one event.
//
// Older integrations send and read a single `event` string. That still works: `event` sets
// `events` to that one event, and responses include `event` whenever there is exactly one.
//
// # Verifying requests
//
// Every delivery is signed using the Standard Webhooks scheme (https://www.standardwebhooks.com)
// with the subscription's `secret`, via the `webhook-id`, `webhook-timestamp` and
// `webhook-signature` headers. Any Standard Webhooks library can verify it.
//
// # Retries
//
// Respond with any 2xx status within 10 seconds. Anything else, or no response, is retried
// with increasing delays, up to 10 attempts over about four hours.
// Responding `410 Gone` deletes the subscription. A subscription that has not had a
// successful delivery for 3 days is disabled
// (`enabled: false`, `disabled_reason: "failing"`); re-enable it with `PATCH` once fixed.
package webhooksubscriptions
