// Code generated by Fern. DO NOT EDIT.

package webhooksubscriptions

import (
	context "context"
	http "net/http"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) GetAPIV1AccountsAccountIDWebhookSubscriptions(
	ctx context.Context,
	request *leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsResponseItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions",
		request.AccountID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsResponseItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsResponseItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostAPIV1AccountsAccountIDWebhookSubscriptions(
	ctx context.Context,
	request *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsRequest,
	opts ...option.RequestOption,
) (*core.Response[*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions",
		request.AccountID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetAPIV1AccountsAccountIDWebhookSubscriptionsID(
	ctx context.Context,
	request *leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions/%v",
		request.AccountID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*leal.GetAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteAPIV1AccountsAccountIDWebhookSubscriptionsID(
	ctx context.Context,
	request *leal.DeleteAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions/%v",
		request.AccountID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) PatchAPIV1AccountsAccountIDWebhookSubscriptionsID(
	ctx context.Context,
	request *leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions/%v",
		request.AccountID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*leal.PatchAPIV1AccountsAccountIDWebhookSubscriptionsIDResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecret(
	ctx context.Context,
	request *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretRequest,
	opts ...option.RequestOption,
) (*core.Response[*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions/%v/rotate_secret",
		request.AccountID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDRotateSecretResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTest(
	ctx context.Context,
	request *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestRequest,
	opts ...option.RequestOption,
) (*core.Response[*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.getleal.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/accounts/%v/webhook_subscriptions/%v/test",
		request.AccountID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(leal.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*leal.PostAPIV1AccountsAccountIDWebhookSubscriptionsIDTestResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
