// Code generated by Fern. DO NOT EDIT.

package locations

import (
	context "context"

	leal "github.com/lealhq/leal-go-sdk"
	core "github.com/lealhq/leal-go-sdk/core"
	internal "github.com/lealhq/leal-go-sdk/internal"
	option "github.com/lealhq/leal-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns every physical location belonging to the specified store.
//
// Example:
//
//	request := &leal.ListLocationsRequest{
//	    AccountID: 1,
//	}
//	client.Locations.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *leal.ListLocationsRequest,
	opts ...option.RequestOption,
) ([]*leal.ListLocationsResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new physical location for the store. The provided address is
// automatically geocoded to latitude and longitude coordinates in the background.
//
// Example:
//
//	request := &leal.CreateLocationsRequest{
//	    AccountID: 1,
//	    Location: &leal.CreateLocationsRequestLocation{
//	        Address: "address",
//	        Name: "name",
//	    },
//	}
//	client.Locations.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *leal.CreateLocationsRequest,
	opts ...option.RequestOption,
) (*leal.CreateLocationsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single location by ID.
//
// Example:
//
//	request := &leal.GetLocationsRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.Locations.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *leal.GetLocationsRequest,
	opts ...option.RequestOption,
) (*leal.GetLocationsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently deletes a location. This action cannot be undone.
//
// Example:
//
//	request := &leal.DeleteLocationsRequest{
//	    AccountID: 1,
//	    ID: 1,
//	}
//	client.Locations.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *leal.DeleteLocationsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Updates an existing location. If the address is changed, it will be re-geocoded automatically.
//
// Example:
//
//	request := &leal.UpdateLocationsRequest{
//	    AccountID: 1,
//	    ID: 1,
//	    Location: &leal.UpdateLocationsRequestLocation{},
//	}
//	client.Locations.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *leal.UpdateLocationsRequest,
	opts ...option.RequestOption,
) (*leal.UpdateLocationsResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
