// Code generated by Fern. DO NOT EDIT.

// Locations represent the physical addresses of a store. Each store can have
// multiple locations (e.g. branches, pop-ups).
//
// When you create or update a location with an address, the address is
// automatically geocoded to latitude/longitude coordinates. These coordinates
// are used for Apple Wallet relevance - customers receive lock-screen
// notifications when they are near one of your locations.
//
// All location endpoints are scoped to a store via the `:account_id` URL
// parameter. You must have access to the parent store.
package locations
